// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type WidgetsSuite struct {
	suite.Suite
}

func TestWidgetsSuite(t *testing.T) {
	suite.Run(t, new(WidgetsSuite))
}

func (s *WidgetsSuite) TestList() {
	g := loadGolden(s.T(), "WidgetService_ListWidgets")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.Widgets().List(ctx, (&cadenya.WidgetListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		AgentID("sample").
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widgets", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Widgets().List(ctx, (&cadenya.WidgetListBuilder{}).
			Limit(1).
			Cursor("sample").
			AgentID("sample").
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetsSuite) TestCreate() {
	g := loadGolden(s.T(), "WidgetService_CreateWidget")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Widgets().Create(ctx, (&cadenya.WidgetCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.WidgetSpec{AgentID: "sample"}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widgets", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Widgets().Create(ctx, (&cadenya.WidgetCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.WidgetSpec{AgentID: "sample"}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "WidgetService_GetWidget")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Widgets().Retrieve(ctx, "sample", (&cadenya.WidgetRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widgets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Widgets().Retrieve(ctx, "sample", (&cadenya.WidgetRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetsSuite) TestDelete() {
	g := loadGolden(s.T(), "WidgetService_DeleteWidget")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.Widgets().Delete(ctx, "sample", (&cadenya.WidgetDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widgets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.Widgets().Delete(ctx, "sample", (&cadenya.WidgetDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetsSuite) TestUpdate() {
	g := loadGolden(s.T(), "WidgetService_UpdateWidget")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Widgets().Update(ctx, "sample", (&cadenya.WidgetUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.WidgetSpec{AgentID: "sample"}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widgets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Widgets().Update(ctx, "sample", (&cadenya.WidgetUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.WidgetSpec{AgentID: "sample"}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetsSuite) TestArchive() {
	g := loadGolden(s.T(), "WidgetService_ArchiveWidget")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Widgets().Archive(ctx, "sample", (&cadenya.WidgetArchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widgets/sample:archive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Widgets().Archive(ctx, "sample", (&cadenya.WidgetArchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetsSuite) TestUnarchive() {
	g := loadGolden(s.T(), "WidgetService_UnarchiveWidget")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Widgets().Unarchive(ctx, "sample", (&cadenya.WidgetUnarchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widgets/sample:unarchive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Widgets().Unarchive(ctx, "sample", (&cadenya.WidgetUnarchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
