// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"
)

type AccountsSuite struct {
	suite.Suite
}

func TestAccountsSuite(t *testing.T) {
	suite.Run(t, new(AccountsSuite))
}

func (s *AccountsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "AccountService_GetAccount")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Accounts().Retrieve(ctx)
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *AccountsSuite) TestRotateChallengeToken() {
	g := loadGolden(s.T(), "AccountService_RotateChallengeToken")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Accounts().RotateChallengeToken(ctx)
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *AccountsSuite) TestRotateWebhookSigningKey() {
	g := loadGolden(s.T(), "AccountService_RotateWebhookSigningKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Accounts().RotateWebhookSigningKey(ctx)
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}
