// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

type ObjectiveListParams struct {
	WorkspaceID       *string                              `json:"workspaceId,omitempty"`
	Limit             *int32                               `json:"limit,omitempty"`
	Cursor            *string                              `json:"cursor,omitempty"`
	AgentID           *string                              `json:"agentId,omitempty"`
	ParentObjectiveID *string                              `json:"parentObjectiveId,omitempty"`
	State             *ObjectiveServiceListObjectivesState `json:"state,omitempty"`
	ProfileID         *string                              `json:"profileId,omitempty"`
	SortOrder         *string                              `json:"sortOrder,omitempty"`
	IncludeInfo       *bool                                `json:"includeInfo,omitempty"`
	AgentScheduleID   *string                              `json:"agentScheduleId,omitempty"`
	Labels            *string                              `json:"labels,omitempty"`
	TenantID          *string                              `json:"tenantId,omitempty"`
	SubjectID         *string                              `json:"subjectId,omitempty"`
	WidgetID          *string                              `json:"widgetId,omitempty"`
	WidgetSessionID   *string                              `json:"widgetSessionId,omitempty"`
}

// ObjectiveListBuilder builds a ObjectiveListParams fluently.
type ObjectiveListBuilder struct {
	params ObjectiveListParams
}

func (b *ObjectiveListBuilder) WorkspaceID(v string) *ObjectiveListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveListBuilder) Limit(v int32) *ObjectiveListBuilder {
	b.params.Limit = &v
	return b
}

func (b *ObjectiveListBuilder) Cursor(v string) *ObjectiveListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ObjectiveListBuilder) AgentID(v string) *ObjectiveListBuilder {
	b.params.AgentID = &v
	return b
}

func (b *ObjectiveListBuilder) ParentObjectiveID(v string) *ObjectiveListBuilder {
	b.params.ParentObjectiveID = &v
	return b
}

func (b *ObjectiveListBuilder) State(v ObjectiveServiceListObjectivesState) *ObjectiveListBuilder {
	b.params.State = &v
	return b
}

func (b *ObjectiveListBuilder) ProfileID(v string) *ObjectiveListBuilder {
	b.params.ProfileID = &v
	return b
}

func (b *ObjectiveListBuilder) SortOrder(v string) *ObjectiveListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *ObjectiveListBuilder) IncludeInfo(v bool) *ObjectiveListBuilder {
	b.params.IncludeInfo = &v
	return b
}

func (b *ObjectiveListBuilder) AgentScheduleID(v string) *ObjectiveListBuilder {
	b.params.AgentScheduleID = &v
	return b
}

func (b *ObjectiveListBuilder) Labels(v string) *ObjectiveListBuilder {
	b.params.Labels = &v
	return b
}

func (b *ObjectiveListBuilder) TenantID(v string) *ObjectiveListBuilder {
	b.params.TenantID = &v
	return b
}

func (b *ObjectiveListBuilder) SubjectID(v string) *ObjectiveListBuilder {
	b.params.SubjectID = &v
	return b
}

func (b *ObjectiveListBuilder) WidgetID(v string) *ObjectiveListBuilder {
	b.params.WidgetID = &v
	return b
}

func (b *ObjectiveListBuilder) WidgetSessionID(v string) *ObjectiveListBuilder {
	b.params.WidgetSessionID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveListBuilder) ToParams() *ObjectiveListParams {
	p := b.params
	return &p
}

type ObjectiveCreateParams struct {
	WorkspaceID          *string                         `json:"workspaceId,omitempty"`
	AgentID              string                          `json:"agentId"`
	VariationID          *string                         `json:"variationId,omitempty"`
	Metadata             *CreateOperationMetadata        `json:"metadata,omitempty"`
	SystemPromptData     map[string]any                  `json:"systemPromptData"`
	FirstUserMessage     *string                         `json:"firstUserMessage,omitempty"`
	Secrets              []CreateObjectiveRequest_Secret `json:"secrets,omitempty"`
	MemoryCascade        []MemoryReference               `json:"memoryCascade,omitempty"`
	FirstUserMessageData map[string]any                  `json:"firstUserMessageData,omitempty"`
	EpisodicMemory       *ObjectiveEpisodicConfigParam   `json:"episodicMemory,omitempty"`
	Tenant               *TenantAssertion                `json:"tenant,omitempty"`
	Subject              *SubjectAssertion               `json:"subject,omitempty"`
	PinnedParameters     map[string]string               `json:"pinnedParameters,omitempty"`
}

// ObjectiveCreateBuilder builds a ObjectiveCreateParams fluently.
type ObjectiveCreateBuilder struct {
	params ObjectiveCreateParams
}

func (b *ObjectiveCreateBuilder) WorkspaceID(v string) *ObjectiveCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveCreateBuilder) AgentID(v string) *ObjectiveCreateBuilder {
	b.params.AgentID = v
	return b
}

func (b *ObjectiveCreateBuilder) VariationID(v string) *ObjectiveCreateBuilder {
	b.params.VariationID = &v
	return b
}

func (b *ObjectiveCreateBuilder) Metadata(v *CreateOperationMetadata) *ObjectiveCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *ObjectiveCreateBuilder) SystemPromptData(v map[string]any) *ObjectiveCreateBuilder {
	b.params.SystemPromptData = v
	return b
}

func (b *ObjectiveCreateBuilder) FirstUserMessage(v string) *ObjectiveCreateBuilder {
	b.params.FirstUserMessage = &v
	return b
}

func (b *ObjectiveCreateBuilder) Secrets(v ...CreateObjectiveRequest_Secret) *ObjectiveCreateBuilder {
	b.params.Secrets = v
	return b
}

func (b *ObjectiveCreateBuilder) MemoryCascade(v ...MemoryReference) *ObjectiveCreateBuilder {
	b.params.MemoryCascade = v
	return b
}

func (b *ObjectiveCreateBuilder) FirstUserMessageData(v map[string]any) *ObjectiveCreateBuilder {
	b.params.FirstUserMessageData = v
	return b
}

func (b *ObjectiveCreateBuilder) EpisodicMemory(v *ObjectiveEpisodicConfigParam) *ObjectiveCreateBuilder {
	b.params.EpisodicMemory = v
	return b
}

func (b *ObjectiveCreateBuilder) Tenant(v *TenantAssertion) *ObjectiveCreateBuilder {
	b.params.Tenant = v
	return b
}

func (b *ObjectiveCreateBuilder) Subject(v *SubjectAssertion) *ObjectiveCreateBuilder {
	b.params.Subject = v
	return b
}

func (b *ObjectiveCreateBuilder) PinnedParameters(v map[string]string) *ObjectiveCreateBuilder {
	b.params.PinnedParameters = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveCreateBuilder) ToParams() *ObjectiveCreateParams {
	p := b.params
	return &p
}

type ObjectiveRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ObjectiveRetrieveBuilder builds a ObjectiveRetrieveParams fluently.
type ObjectiveRetrieveBuilder struct {
	params ObjectiveRetrieveParams
}

func (b *ObjectiveRetrieveBuilder) WorkspaceID(v string) *ObjectiveRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveRetrieveBuilder) ToParams() *ObjectiveRetrieveParams {
	p := b.params
	return &p
}

type ObjectiveListContextWindowsParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
	Labels      *string `json:"labels,omitempty"`
}

// ObjectiveListContextWindowsBuilder builds a ObjectiveListContextWindowsParams fluently.
type ObjectiveListContextWindowsBuilder struct {
	params ObjectiveListContextWindowsParams
}

func (b *ObjectiveListContextWindowsBuilder) WorkspaceID(v string) *ObjectiveListContextWindowsBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveListContextWindowsBuilder) Limit(v int32) *ObjectiveListContextWindowsBuilder {
	b.params.Limit = &v
	return b
}

func (b *ObjectiveListContextWindowsBuilder) Cursor(v string) *ObjectiveListContextWindowsBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ObjectiveListContextWindowsBuilder) IncludeInfo(v bool) *ObjectiveListContextWindowsBuilder {
	b.params.IncludeInfo = &v
	return b
}

func (b *ObjectiveListContextWindowsBuilder) Labels(v string) *ObjectiveListContextWindowsBuilder {
	b.params.Labels = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveListContextWindowsBuilder) ToParams() *ObjectiveListContextWindowsParams {
	p := b.params
	return &p
}

type ObjectiveRetrieveDiagnosticsParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ObjectiveRetrieveDiagnosticsBuilder builds a ObjectiveRetrieveDiagnosticsParams fluently.
type ObjectiveRetrieveDiagnosticsBuilder struct {
	params ObjectiveRetrieveDiagnosticsParams
}

func (b *ObjectiveRetrieveDiagnosticsBuilder) WorkspaceID(v string) *ObjectiveRetrieveDiagnosticsBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveRetrieveDiagnosticsBuilder) ToParams() *ObjectiveRetrieveDiagnosticsParams {
	p := b.params
	return &p
}

type ObjectiveListEventsParams struct {
	WorkspaceID  *string `json:"workspaceId,omitempty"`
	Limit        *int32  `json:"limit,omitempty"`
	Cursor       *string `json:"cursor,omitempty"`
	SortOrder    *string `json:"sortOrder,omitempty"`
	IncludeInfo  *bool   `json:"includeInfo,omitempty"`
	WindowID     *string `json:"windowId,omitempty"`
	SinceEventID *string `json:"sinceEventId,omitempty"`
	Labels       *string `json:"labels,omitempty"`
}

// ObjectiveListEventsBuilder builds a ObjectiveListEventsParams fluently.
type ObjectiveListEventsBuilder struct {
	params ObjectiveListEventsParams
}

func (b *ObjectiveListEventsBuilder) WorkspaceID(v string) *ObjectiveListEventsBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveListEventsBuilder) Limit(v int32) *ObjectiveListEventsBuilder {
	b.params.Limit = &v
	return b
}

func (b *ObjectiveListEventsBuilder) Cursor(v string) *ObjectiveListEventsBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ObjectiveListEventsBuilder) SortOrder(v string) *ObjectiveListEventsBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *ObjectiveListEventsBuilder) IncludeInfo(v bool) *ObjectiveListEventsBuilder {
	b.params.IncludeInfo = &v
	return b
}

func (b *ObjectiveListEventsBuilder) WindowID(v string) *ObjectiveListEventsBuilder {
	b.params.WindowID = &v
	return b
}

func (b *ObjectiveListEventsBuilder) SinceEventID(v string) *ObjectiveListEventsBuilder {
	b.params.SinceEventID = &v
	return b
}

func (b *ObjectiveListEventsBuilder) Labels(v string) *ObjectiveListEventsBuilder {
	b.params.Labels = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveListEventsBuilder) ToParams() *ObjectiveListEventsParams {
	p := b.params
	return &p
}

type ObjectiveStreamEventsParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ObjectiveStreamEventsBuilder builds a ObjectiveStreamEventsParams fluently.
type ObjectiveStreamEventsBuilder struct {
	params ObjectiveStreamEventsParams
}

func (b *ObjectiveStreamEventsBuilder) WorkspaceID(v string) *ObjectiveStreamEventsBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveStreamEventsBuilder) ToParams() *ObjectiveStreamEventsParams {
	p := b.params
	return &p
}

type ObjectiveListFeedbackParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	Labels      *string `json:"labels,omitempty"`
}

// ObjectiveListFeedbackBuilder builds a ObjectiveListFeedbackParams fluently.
type ObjectiveListFeedbackBuilder struct {
	params ObjectiveListFeedbackParams
}

func (b *ObjectiveListFeedbackBuilder) WorkspaceID(v string) *ObjectiveListFeedbackBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveListFeedbackBuilder) Limit(v int32) *ObjectiveListFeedbackBuilder {
	b.params.Limit = &v
	return b
}

func (b *ObjectiveListFeedbackBuilder) Cursor(v string) *ObjectiveListFeedbackBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ObjectiveListFeedbackBuilder) Labels(v string) *ObjectiveListFeedbackBuilder {
	b.params.Labels = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveListFeedbackBuilder) ToParams() *ObjectiveListFeedbackParams {
	p := b.params
	return &p
}

type ObjectiveCreateFeedbackParams struct {
	WorkspaceID *string                  `json:"workspaceId,omitempty"`
	Metadata    *CreateOperationMetadata `json:"metadata"`
	Data        *ObjectiveFeedbackData   `json:"data"`
}

// ObjectiveCreateFeedbackBuilder builds a ObjectiveCreateFeedbackParams fluently.
type ObjectiveCreateFeedbackBuilder struct {
	params ObjectiveCreateFeedbackParams
}

func (b *ObjectiveCreateFeedbackBuilder) WorkspaceID(v string) *ObjectiveCreateFeedbackBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveCreateFeedbackBuilder) Metadata(v *CreateOperationMetadata) *ObjectiveCreateFeedbackBuilder {
	b.params.Metadata = v
	return b
}

func (b *ObjectiveCreateFeedbackBuilder) Data(v *ObjectiveFeedbackData) *ObjectiveCreateFeedbackBuilder {
	b.params.Data = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveCreateFeedbackBuilder) ToParams() *ObjectiveCreateFeedbackParams {
	p := b.params
	return &p
}

type ObjectiveListTasksParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
}

// ObjectiveListTasksBuilder builds a ObjectiveListTasksParams fluently.
type ObjectiveListTasksBuilder struct {
	params ObjectiveListTasksParams
}

func (b *ObjectiveListTasksBuilder) WorkspaceID(v string) *ObjectiveListTasksBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveListTasksBuilder) Limit(v int32) *ObjectiveListTasksBuilder {
	b.params.Limit = &v
	return b
}

func (b *ObjectiveListTasksBuilder) Cursor(v string) *ObjectiveListTasksBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ObjectiveListTasksBuilder) SortOrder(v string) *ObjectiveListTasksBuilder {
	b.params.SortOrder = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveListTasksBuilder) ToParams() *ObjectiveListTasksParams {
	p := b.params
	return &p
}

type ObjectiveRetrieveTaskParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ObjectiveRetrieveTaskBuilder builds a ObjectiveRetrieveTaskParams fluently.
type ObjectiveRetrieveTaskBuilder struct {
	params ObjectiveRetrieveTaskParams
}

func (b *ObjectiveRetrieveTaskBuilder) WorkspaceID(v string) *ObjectiveRetrieveTaskBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveRetrieveTaskBuilder) ToParams() *ObjectiveRetrieveTaskParams {
	p := b.params
	return &p
}

type ObjectiveListToolCallsParams struct {
	WorkspaceID     *string                                                `json:"workspaceId,omitempty"`
	Limit           *int32                                                 `json:"limit,omitempty"`
	Cursor          *string                                                `json:"cursor,omitempty"`
	Status          *ObjectiveServiceListObjectiveToolCallsStatus          `json:"status,omitempty"`
	IncludeInfo     *bool                                                  `json:"includeInfo,omitempty"`
	ExecutionStatus *ObjectiveServiceListObjectiveToolCallsExecutionStatus `json:"executionStatus,omitempty"`
	Labels          *string                                                `json:"labels,omitempty"`
}

// ObjectiveListToolCallsBuilder builds a ObjectiveListToolCallsParams fluently.
type ObjectiveListToolCallsBuilder struct {
	params ObjectiveListToolCallsParams
}

func (b *ObjectiveListToolCallsBuilder) WorkspaceID(v string) *ObjectiveListToolCallsBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveListToolCallsBuilder) Limit(v int32) *ObjectiveListToolCallsBuilder {
	b.params.Limit = &v
	return b
}

func (b *ObjectiveListToolCallsBuilder) Cursor(v string) *ObjectiveListToolCallsBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ObjectiveListToolCallsBuilder) Status(v ObjectiveServiceListObjectiveToolCallsStatus) *ObjectiveListToolCallsBuilder {
	b.params.Status = &v
	return b
}

func (b *ObjectiveListToolCallsBuilder) IncludeInfo(v bool) *ObjectiveListToolCallsBuilder {
	b.params.IncludeInfo = &v
	return b
}

func (b *ObjectiveListToolCallsBuilder) ExecutionStatus(v ObjectiveServiceListObjectiveToolCallsExecutionStatus) *ObjectiveListToolCallsBuilder {
	b.params.ExecutionStatus = &v
	return b
}

func (b *ObjectiveListToolCallsBuilder) Labels(v string) *ObjectiveListToolCallsBuilder {
	b.params.Labels = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveListToolCallsBuilder) ToParams() *ObjectiveListToolCallsParams {
	p := b.params
	return &p
}

type ObjectiveRetrieveToolCallParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ObjectiveRetrieveToolCallBuilder builds a ObjectiveRetrieveToolCallParams fluently.
type ObjectiveRetrieveToolCallBuilder struct {
	params ObjectiveRetrieveToolCallParams
}

func (b *ObjectiveRetrieveToolCallBuilder) WorkspaceID(v string) *ObjectiveRetrieveToolCallBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveRetrieveToolCallBuilder) ToParams() *ObjectiveRetrieveToolCallParams {
	p := b.params
	return &p
}

type ObjectiveApproveToolCallParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ObjectiveApproveToolCallBuilder builds a ObjectiveApproveToolCallParams fluently.
type ObjectiveApproveToolCallBuilder struct {
	params ObjectiveApproveToolCallParams
}

func (b *ObjectiveApproveToolCallBuilder) WorkspaceID(v string) *ObjectiveApproveToolCallBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveApproveToolCallBuilder) ToParams() *ObjectiveApproveToolCallParams {
	p := b.params
	return &p
}

type ObjectiveDenyToolCallParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Memo        *string `json:"memo,omitempty"`
}

// ObjectiveDenyToolCallBuilder builds a ObjectiveDenyToolCallParams fluently.
type ObjectiveDenyToolCallBuilder struct {
	params ObjectiveDenyToolCallParams
}

func (b *ObjectiveDenyToolCallBuilder) WorkspaceID(v string) *ObjectiveDenyToolCallBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveDenyToolCallBuilder) Memo(v string) *ObjectiveDenyToolCallBuilder {
	b.params.Memo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveDenyToolCallBuilder) ToParams() *ObjectiveDenyToolCallParams {
	p := b.params
	return &p
}

type ObjectiveSetToolCallContentParams struct {
	WorkspaceID *string                                  `json:"workspaceId,omitempty"`
	Content     []SetToolCallContentRequest_ContentBlock `json:"content"`
}

// ObjectiveSetToolCallContentBuilder builds a ObjectiveSetToolCallContentParams fluently.
type ObjectiveSetToolCallContentBuilder struct {
	params ObjectiveSetToolCallContentParams
}

func (b *ObjectiveSetToolCallContentBuilder) WorkspaceID(v string) *ObjectiveSetToolCallContentBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveSetToolCallContentBuilder) Content(v ...SetToolCallContentRequest_ContentBlock) *ObjectiveSetToolCallContentBuilder {
	b.params.Content = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveSetToolCallContentBuilder) ToParams() *ObjectiveSetToolCallContentParams {
	p := b.params
	return &p
}

type ObjectiveListToolsParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
}

// ObjectiveListToolsBuilder builds a ObjectiveListToolsParams fluently.
type ObjectiveListToolsBuilder struct {
	params ObjectiveListToolsParams
}

func (b *ObjectiveListToolsBuilder) WorkspaceID(v string) *ObjectiveListToolsBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveListToolsBuilder) Limit(v int32) *ObjectiveListToolsBuilder {
	b.params.Limit = &v
	return b
}

func (b *ObjectiveListToolsBuilder) Cursor(v string) *ObjectiveListToolsBuilder {
	b.params.Cursor = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveListToolsBuilder) ToParams() *ObjectiveListToolsParams {
	p := b.params
	return &p
}

type ObjectiveCancelParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Reason      *string `json:"reason,omitempty"`
}

// ObjectiveCancelBuilder builds a ObjectiveCancelParams fluently.
type ObjectiveCancelBuilder struct {
	params ObjectiveCancelParams
}

func (b *ObjectiveCancelBuilder) WorkspaceID(v string) *ObjectiveCancelBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveCancelBuilder) Reason(v string) *ObjectiveCancelBuilder {
	b.params.Reason = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveCancelBuilder) ToParams() *ObjectiveCancelParams {
	p := b.params
	return &p
}

type ObjectiveCompactParams struct {
	WorkspaceID      *string                              `json:"workspaceId,omitempty"`
	CompactionConfig *AgentVariationSpec_CompactionConfig `json:"compactionConfig,omitempty"`
}

// ObjectiveCompactBuilder builds a ObjectiveCompactParams fluently.
type ObjectiveCompactBuilder struct {
	params ObjectiveCompactParams
}

func (b *ObjectiveCompactBuilder) WorkspaceID(v string) *ObjectiveCompactBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveCompactBuilder) CompactionConfig(v *AgentVariationSpec_CompactionConfig) *ObjectiveCompactBuilder {
	b.params.CompactionConfig = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveCompactBuilder) ToParams() *ObjectiveCompactParams {
	p := b.params
	return &p
}

type ObjectiveContinueParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Message     string  `json:"message"`
	Enqueue     *bool   `json:"enqueue,omitempty"`
}

// ObjectiveContinueBuilder builds a ObjectiveContinueParams fluently.
type ObjectiveContinueBuilder struct {
	params ObjectiveContinueParams
}

func (b *ObjectiveContinueBuilder) WorkspaceID(v string) *ObjectiveContinueBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ObjectiveContinueBuilder) Message(v string) *ObjectiveContinueBuilder {
	b.params.Message = v
	return b
}

func (b *ObjectiveContinueBuilder) Enqueue(v bool) *ObjectiveContinueBuilder {
	b.params.Enqueue = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ObjectiveContinueBuilder) ToParams() *ObjectiveContinueParams {
	p := b.params
	return &p
}

// ObjectiveResources is implemented by the SDK and easy to mock in tests.
type ObjectiveResources interface {
	// List objectives
	List(ctx context.Context, params *ObjectiveListParams, opts ...RequestOption) (*Page[Objective], error)
	// Create a new objective
	Create(ctx context.Context, params *ObjectiveCreateParams, opts ...RequestOption) (*Objective, error)
	// Get an objective by ID
	Retrieve(ctx context.Context, id string, params *ObjectiveRetrieveParams, opts ...RequestOption) (*Objective, error)
	// List objective context windows
	ListContextWindows(ctx context.Context, objectiveID string, params *ObjectiveListContextWindowsParams, opts ...RequestOption) (*Page[ObjectiveContextWindow], error)
	// Get objective context usage
	RetrieveDiagnostics(ctx context.Context, objectiveID string, params *ObjectiveRetrieveDiagnosticsParams, opts ...RequestOption) (*GetObjectiveDiagnosticsResponse, error)
	// List objective events
	ListEvents(ctx context.Context, objectiveID string, params *ObjectiveListEventsParams, opts ...RequestOption) (*Page[ObjectiveEvent], error)
	// Stream objective events
	StreamEvents(ctx context.Context, objectiveID string, params *ObjectiveStreamEventsParams, opts ...RequestOption) (*Stream[ObjectiveEvent], error)
	// List feedback for an objective
	ListFeedback(ctx context.Context, objectiveID string, params *ObjectiveListFeedbackParams, opts ...RequestOption) (*Page[ObjectiveFeedback], error)
	// Submit feedback for an objective
	CreateFeedback(ctx context.Context, objectiveID string, params *ObjectiveCreateFeedbackParams, opts ...RequestOption) (*ObjectiveFeedback, error)
	// List objective tasks
	ListTasks(ctx context.Context, objectiveID string, params *ObjectiveListTasksParams, opts ...RequestOption) (*Page[ObjectiveTask], error)
	// Get an objective task by ID
	RetrieveTask(ctx context.Context, objectiveID string, id string, params *ObjectiveRetrieveTaskParams, opts ...RequestOption) (*ObjectiveTask, error)
	// List objective tool calls
	ListToolCalls(ctx context.Context, objectiveID string, params *ObjectiveListToolCallsParams, opts ...RequestOption) (*Page[ObjectiveToolCall], error)
	// Get an objective tool call by ID
	RetrieveToolCall(ctx context.Context, objectiveID string, toolCallID string, params *ObjectiveRetrieveToolCallParams, opts ...RequestOption) (*ObjectiveToolCallWithResult, error)
	// Approve a tool call
	ApproveToolCall(ctx context.Context, objectiveID string, toolCallID string, params *ObjectiveApproveToolCallParams, opts ...RequestOption) (*ObjectiveToolCall, error)
	// Deny a tool call
	DenyToolCall(ctx context.Context, objectiveID string, toolCallID string, params *ObjectiveDenyToolCallParams, opts ...RequestOption) (*ObjectiveToolCall, error)
	// Set a bare tool call's content
	SetToolCallContent(ctx context.Context, objectiveID string, toolCallID string, params *ObjectiveSetToolCallContentParams, opts ...RequestOption) (*ObjectiveToolCall, error)
	// List objective tools
	ListTools(ctx context.Context, objectiveID string, params *ObjectiveListToolsParams, opts ...RequestOption) (*Page[ObjectiveTool], error)
	// Cancel an objective
	Cancel(ctx context.Context, objectiveID string, params *ObjectiveCancelParams, opts ...RequestOption) (*Objective, error)
	// Compact an objective
	Compact(ctx context.Context, objectiveID string, params *ObjectiveCompactParams, opts ...RequestOption) (*CompactObjectiveResponse, error)
	// Continue an objective
	Continue(ctx context.Context, objectiveID string, params *ObjectiveContinueParams, opts ...RequestOption) (*ObjectiveEvent, error)
}

type objectivesService struct{ core *core }

var _ ObjectiveResources = (*objectivesService)(nil)

func (s *objectivesService) List(ctx context.Context, params *ObjectiveListParams, opts ...RequestOption) (*Page[Objective], error) {
	if params == nil {
		params = &ObjectiveListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.AgentID != nil {
		q.Set("agentId", (*params.AgentID))
	}
	if params.ParentObjectiveID != nil {
		q.Set("parentObjectiveId", (*params.ParentObjectiveID))
	}
	if params.State != nil {
		q.Set("state", string(*params.State))
	}
	if params.ProfileID != nil {
		q.Set("profileId", (*params.ProfileID))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	if params.AgentScheduleID != nil {
		q.Set("agentScheduleId", (*params.AgentScheduleID))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.TenantID != nil {
		q.Set("tenantId", (*params.TenantID))
	}
	if params.SubjectID != nil {
		q.Set("subjectId", (*params.SubjectID))
	}
	if params.WidgetID != nil {
		q.Set("widgetId", (*params.WidgetID))
	}
	if params.WidgetSessionID != nil {
		q.Set("widgetSessionId", (*params.WidgetSessionID))
	}
	var out ListObjectivesResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[Objective], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *objectivesService) Create(ctx context.Context, params *ObjectiveCreateParams, opts ...RequestOption) (*Objective, error) {
	if params == nil {
		params = &ObjectiveCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives", segWorkspaceID)
	body := map[string]any{}
	body["agentId"] = params.AgentID
	if params.VariationID != nil {
		body["variationId"] = params.VariationID
	}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.SystemPromptData != nil {
		body["systemPromptData"] = params.SystemPromptData
	}
	if params.FirstUserMessage != nil {
		body["firstUserMessage"] = params.FirstUserMessage
	}
	if params.Secrets != nil {
		body["secrets"] = params.Secrets
	}
	if params.MemoryCascade != nil {
		body["memoryCascade"] = params.MemoryCascade
	}
	if params.FirstUserMessageData != nil {
		body["firstUserMessageData"] = params.FirstUserMessageData
	}
	if params.EpisodicMemory != nil {
		body["episodicMemory"] = params.EpisodicMemory
	}
	if params.Tenant != nil {
		body["tenant"] = params.Tenant
	}
	if params.Subject != nil {
		body["subject"] = params.Subject
	}
	if params.PinnedParameters != nil {
		body["pinnedParameters"] = params.PinnedParameters
	}
	var out Objective
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) Retrieve(ctx context.Context, id string, params *ObjectiveRetrieveParams, opts ...RequestOption) (*Objective, error) {
	if params == nil {
		params = &ObjectiveRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s", segWorkspaceID, segID)
	var out Objective
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) ListContextWindows(ctx context.Context, objectiveID string, params *ObjectiveListContextWindowsParams, opts ...RequestOption) (*Page[ObjectiveContextWindow], error) {
	if params == nil {
		params = &ObjectiveListContextWindowsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/context_windows", segWorkspaceID, segObjectiveID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	var out ListObjectiveContextWindowsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ObjectiveContextWindow], error) {
		p := base
		p.Cursor = &cursor
		return s.ListContextWindows(ctx, objectiveID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *objectivesService) RetrieveDiagnostics(ctx context.Context, objectiveID string, params *ObjectiveRetrieveDiagnosticsParams, opts ...RequestOption) (*GetObjectiveDiagnosticsResponse, error) {
	if params == nil {
		params = &ObjectiveRetrieveDiagnosticsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/diagnostics", segWorkspaceID, segObjectiveID)
	var out GetObjectiveDiagnosticsResponse
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) ListEvents(ctx context.Context, objectiveID string, params *ObjectiveListEventsParams, opts ...RequestOption) (*Page[ObjectiveEvent], error) {
	if params == nil {
		params = &ObjectiveListEventsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/events", segWorkspaceID, segObjectiveID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	if params.WindowID != nil {
		q.Set("windowId", (*params.WindowID))
	}
	if params.SinceEventID != nil {
		q.Set("sinceEventId", (*params.SinceEventID))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	var out ListObjectiveEventsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ObjectiveEvent], error) {
		p := base
		p.Cursor = &cursor
		return s.ListEvents(ctx, objectiveID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *objectivesService) StreamEvents(ctx context.Context, objectiveID string, params *ObjectiveStreamEventsParams, opts ...RequestOption) (*Stream[ObjectiveEvent], error) {
	if params == nil {
		params = &ObjectiveStreamEventsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/events:stream", segWorkspaceID, segObjectiveID)
	rc := buildRequestConfig(opts)
	resp, err := s.core.rawConfig(ctx, "GET", path, nil, nil, true, rc)
	if err != nil {
		return nil, err
	}
	_reconnect := func(lastEventID string) (*http.Response, error) {
		rc2 := *rc
		rc2.headers = rc.headers.Clone()
		if lastEventID != "" {
			rc2.headers.Set("Last-Event-ID", lastEventID)
		} else {
			rc2.headers.Del("Last-Event-ID")
		}
		return s.core.rawConfig(ctx, "GET", path, nil, nil, true, &rc2)
	}
	if rc.reconnect != nil && !*rc.reconnect {
		_reconnect = nil
	}
	return newStream[ObjectiveEvent](ctx, resp, rc.headers.Get("Last-Event-ID"), []string{"ping", "open"}, _reconnect), nil
}

func (s *objectivesService) ListFeedback(ctx context.Context, objectiveID string, params *ObjectiveListFeedbackParams, opts ...RequestOption) (*Page[ObjectiveFeedback], error) {
	if params == nil {
		params = &ObjectiveListFeedbackParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/feedback", segWorkspaceID, segObjectiveID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	var out ListObjectiveFeedbackResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ObjectiveFeedback], error) {
		p := base
		p.Cursor = &cursor
		return s.ListFeedback(ctx, objectiveID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *objectivesService) CreateFeedback(ctx context.Context, objectiveID string, params *ObjectiveCreateFeedbackParams, opts ...RequestOption) (*ObjectiveFeedback, error) {
	if params == nil {
		params = &ObjectiveCreateFeedbackParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/feedback", segWorkspaceID, segObjectiveID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Data != nil {
		body["data"] = params.Data
	}
	var out ObjectiveFeedback
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) ListTasks(ctx context.Context, objectiveID string, params *ObjectiveListTasksParams, opts ...RequestOption) (*Page[ObjectiveTask], error) {
	if params == nil {
		params = &ObjectiveListTasksParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/tasks", segWorkspaceID, segObjectiveID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	var out ListObjectiveTasksResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ObjectiveTask], error) {
		p := base
		p.Cursor = &cursor
		return s.ListTasks(ctx, objectiveID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *objectivesService) RetrieveTask(ctx context.Context, objectiveID string, id string, params *ObjectiveRetrieveTaskParams, opts ...RequestOption) (*ObjectiveTask, error) {
	if params == nil {
		params = &ObjectiveRetrieveTaskParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/tasks/%s", segWorkspaceID, segObjectiveID, segID)
	var out ObjectiveTask
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) ListToolCalls(ctx context.Context, objectiveID string, params *ObjectiveListToolCallsParams, opts ...RequestOption) (*Page[ObjectiveToolCall], error) {
	if params == nil {
		params = &ObjectiveListToolCallsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/tool_calls", segWorkspaceID, segObjectiveID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Status != nil {
		q.Set("status", string(*params.Status))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	if params.ExecutionStatus != nil {
		q.Set("executionStatus", string(*params.ExecutionStatus))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	var out ListObjectiveToolCallsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ObjectiveToolCall], error) {
		p := base
		p.Cursor = &cursor
		return s.ListToolCalls(ctx, objectiveID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *objectivesService) RetrieveToolCall(ctx context.Context, objectiveID string, toolCallID string, params *ObjectiveRetrieveToolCallParams, opts ...RequestOption) (*ObjectiveToolCallWithResult, error) {
	if params == nil {
		params = &ObjectiveRetrieveToolCallParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	segToolCallID, err := pathSegment("toolCallId", toolCallID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/tool_calls/%s", segWorkspaceID, segObjectiveID, segToolCallID)
	var out ObjectiveToolCallWithResult
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) ApproveToolCall(ctx context.Context, objectiveID string, toolCallID string, params *ObjectiveApproveToolCallParams, opts ...RequestOption) (*ObjectiveToolCall, error) {
	if params == nil {
		params = &ObjectiveApproveToolCallParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	segToolCallID, err := pathSegment("toolCallId", toolCallID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/tool_calls/%s:approve", segWorkspaceID, segObjectiveID, segToolCallID)
	var out ObjectiveToolCall
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) DenyToolCall(ctx context.Context, objectiveID string, toolCallID string, params *ObjectiveDenyToolCallParams, opts ...RequestOption) (*ObjectiveToolCall, error) {
	if params == nil {
		params = &ObjectiveDenyToolCallParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	segToolCallID, err := pathSegment("toolCallId", toolCallID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/tool_calls/%s:deny", segWorkspaceID, segObjectiveID, segToolCallID)
	body := map[string]any{}
	if params.Memo != nil {
		body["memo"] = params.Memo
	}
	var out ObjectiveToolCall
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) SetToolCallContent(ctx context.Context, objectiveID string, toolCallID string, params *ObjectiveSetToolCallContentParams, opts ...RequestOption) (*ObjectiveToolCall, error) {
	if params == nil {
		params = &ObjectiveSetToolCallContentParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	segToolCallID, err := pathSegment("toolCallId", toolCallID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/tool_calls/%s:setContent", segWorkspaceID, segObjectiveID, segToolCallID)
	body := map[string]any{}
	if params.Content != nil {
		body["content"] = params.Content
	}
	var out ObjectiveToolCall
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) ListTools(ctx context.Context, objectiveID string, params *ObjectiveListToolsParams, opts ...RequestOption) (*Page[ObjectiveTool], error) {
	if params == nil {
		params = &ObjectiveListToolsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s/tools", segWorkspaceID, segObjectiveID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	var out ListObjectiveToolsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ObjectiveTool], error) {
		p := base
		p.Cursor = &cursor
		return s.ListTools(ctx, objectiveID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *objectivesService) Cancel(ctx context.Context, objectiveID string, params *ObjectiveCancelParams, opts ...RequestOption) (*Objective, error) {
	if params == nil {
		params = &ObjectiveCancelParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s:cancel", segWorkspaceID, segObjectiveID)
	body := map[string]any{}
	if params.Reason != nil {
		body["reason"] = params.Reason
	}
	var out Objective
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) Compact(ctx context.Context, objectiveID string, params *ObjectiveCompactParams, opts ...RequestOption) (*CompactObjectiveResponse, error) {
	if params == nil {
		params = &ObjectiveCompactParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s:compact", segWorkspaceID, segObjectiveID)
	body := map[string]any{}
	if params.CompactionConfig != nil {
		body["compactionConfig"] = params.CompactionConfig
	}
	var out CompactObjectiveResponse
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *objectivesService) Continue(ctx context.Context, objectiveID string, params *ObjectiveContinueParams, opts ...RequestOption) (*ObjectiveEvent, error) {
	if params == nil {
		params = &ObjectiveContinueParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segObjectiveID, err := pathSegment("objectiveId", objectiveID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/objectives/%s:continue", segWorkspaceID, segObjectiveID)
	body := map[string]any{}
	body["message"] = params.Message
	if params.Enqueue != nil {
		body["enqueue"] = params.Enqueue
	}
	var out ObjectiveEvent
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
