// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type ToolSetListParams struct {
	WorkspaceID *string                       `json:"workspaceId,omitempty"`
	Limit       *int32                        `json:"limit,omitempty"`
	Cursor      *string                       `json:"cursor,omitempty"`
	Prefix      *string                       `json:"prefix,omitempty"`
	Query       *string                       `json:"query,omitempty"`
	State       *ToolServiceListToolSetsState `json:"state,omitempty"`
	Labels      *string                       `json:"labels,omitempty"`
	SortOrder   *string                       `json:"sortOrder,omitempty"`
	IncludeInfo *bool                         `json:"includeInfo,omitempty"`
}

// ToolSetListBuilder builds a ToolSetListParams fluently.
type ToolSetListBuilder struct {
	params ToolSetListParams
}

func (b *ToolSetListBuilder) WorkspaceID(v string) *ToolSetListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ToolSetListBuilder) Limit(v int32) *ToolSetListBuilder {
	b.params.Limit = &v
	return b
}

func (b *ToolSetListBuilder) Cursor(v string) *ToolSetListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ToolSetListBuilder) Prefix(v string) *ToolSetListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *ToolSetListBuilder) Query(v string) *ToolSetListBuilder {
	b.params.Query = &v
	return b
}

func (b *ToolSetListBuilder) State(v ToolServiceListToolSetsState) *ToolSetListBuilder {
	b.params.State = &v
	return b
}

func (b *ToolSetListBuilder) Labels(v string) *ToolSetListBuilder {
	b.params.Labels = &v
	return b
}

func (b *ToolSetListBuilder) SortOrder(v string) *ToolSetListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *ToolSetListBuilder) IncludeInfo(v bool) *ToolSetListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetListBuilder) ToParams() *ToolSetListParams {
	p := b.params
	return &p
}

type ToolSetCreateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *CreateResourceMetadata `json:"metadata"`
	Spec        *ToolSetSpec            `json:"spec"`
}

// ToolSetCreateBuilder builds a ToolSetCreateParams fluently.
type ToolSetCreateBuilder struct {
	params ToolSetCreateParams
}

func (b *ToolSetCreateBuilder) WorkspaceID(v string) *ToolSetCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ToolSetCreateBuilder) Metadata(v *CreateResourceMetadata) *ToolSetCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *ToolSetCreateBuilder) Spec(v *ToolSetSpec) *ToolSetCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetCreateBuilder) ToParams() *ToolSetCreateParams {
	p := b.params
	return &p
}

type ToolSetRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ToolSetRetrieveBuilder builds a ToolSetRetrieveParams fluently.
type ToolSetRetrieveBuilder struct {
	params ToolSetRetrieveParams
}

func (b *ToolSetRetrieveBuilder) WorkspaceID(v string) *ToolSetRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetRetrieveBuilder) ToParams() *ToolSetRetrieveParams {
	p := b.params
	return &p
}

type ToolSetDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ToolSetDeleteBuilder builds a ToolSetDeleteParams fluently.
type ToolSetDeleteBuilder struct {
	params ToolSetDeleteParams
}

func (b *ToolSetDeleteBuilder) WorkspaceID(v string) *ToolSetDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetDeleteBuilder) ToParams() *ToolSetDeleteParams {
	p := b.params
	return &p
}

type ToolSetUpdateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *UpdateResourceMetadata `json:"metadata,omitempty"`
	Spec        *ToolSetSpec            `json:"spec,omitempty"`
	UpdateMask  *string                 `json:"updateMask,omitempty"`
}

// ToolSetUpdateBuilder builds a ToolSetUpdateParams fluently.
type ToolSetUpdateBuilder struct {
	params ToolSetUpdateParams
}

func (b *ToolSetUpdateBuilder) WorkspaceID(v string) *ToolSetUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ToolSetUpdateBuilder) Metadata(v *UpdateResourceMetadata) *ToolSetUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *ToolSetUpdateBuilder) Spec(v *ToolSetSpec) *ToolSetUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *ToolSetUpdateBuilder) UpdateMask(v string) *ToolSetUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetUpdateBuilder) ToParams() *ToolSetUpdateParams {
	p := b.params
	return &p
}

type ToolSetArchiveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ToolSetArchiveBuilder builds a ToolSetArchiveParams fluently.
type ToolSetArchiveBuilder struct {
	params ToolSetArchiveParams
}

func (b *ToolSetArchiveBuilder) WorkspaceID(v string) *ToolSetArchiveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetArchiveBuilder) ToParams() *ToolSetArchiveParams {
	p := b.params
	return &p
}

type ToolSetUnarchiveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ToolSetUnarchiveBuilder builds a ToolSetUnarchiveParams fluently.
type ToolSetUnarchiveBuilder struct {
	params ToolSetUnarchiveParams
}

func (b *ToolSetUnarchiveBuilder) WorkspaceID(v string) *ToolSetUnarchiveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetUnarchiveBuilder) ToParams() *ToolSetUnarchiveParams {
	p := b.params
	return &p
}

type ToolSetListEventsParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
	Labels      *string `json:"labels,omitempty"`
}

// ToolSetListEventsBuilder builds a ToolSetListEventsParams fluently.
type ToolSetListEventsBuilder struct {
	params ToolSetListEventsParams
}

func (b *ToolSetListEventsBuilder) WorkspaceID(v string) *ToolSetListEventsBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ToolSetListEventsBuilder) Limit(v int32) *ToolSetListEventsBuilder {
	b.params.Limit = &v
	return b
}

func (b *ToolSetListEventsBuilder) Cursor(v string) *ToolSetListEventsBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ToolSetListEventsBuilder) SortOrder(v string) *ToolSetListEventsBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *ToolSetListEventsBuilder) IncludeInfo(v bool) *ToolSetListEventsBuilder {
	b.params.IncludeInfo = &v
	return b
}

func (b *ToolSetListEventsBuilder) Labels(v string) *ToolSetListEventsBuilder {
	b.params.Labels = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetListEventsBuilder) ToParams() *ToolSetListEventsParams {
	p := b.params
	return &p
}

type ToolSetRetrieveOpenAPISpecParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ToolSetRetrieveOpenAPISpecBuilder builds a ToolSetRetrieveOpenAPISpecParams fluently.
type ToolSetRetrieveOpenAPISpecBuilder struct {
	params ToolSetRetrieveOpenAPISpecParams
}

func (b *ToolSetRetrieveOpenAPISpecBuilder) WorkspaceID(v string) *ToolSetRetrieveOpenAPISpecBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetRetrieveOpenAPISpecBuilder) ToParams() *ToolSetRetrieveOpenAPISpecParams {
	p := b.params
	return &p
}

type ToolSetListUsageParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	ToolID      *string `json:"toolId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
}

// ToolSetListUsageBuilder builds a ToolSetListUsageParams fluently.
type ToolSetListUsageBuilder struct {
	params ToolSetListUsageParams
}

func (b *ToolSetListUsageBuilder) WorkspaceID(v string) *ToolSetListUsageBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ToolSetListUsageBuilder) ToolID(v string) *ToolSetListUsageBuilder {
	b.params.ToolID = &v
	return b
}

func (b *ToolSetListUsageBuilder) Limit(v int32) *ToolSetListUsageBuilder {
	b.params.Limit = &v
	return b
}

func (b *ToolSetListUsageBuilder) Cursor(v string) *ToolSetListUsageBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ToolSetListUsageBuilder) SortOrder(v string) *ToolSetListUsageBuilder {
	b.params.SortOrder = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetListUsageBuilder) ToParams() *ToolSetListUsageParams {
	p := b.params
	return &p
}

// ToolSetResources is implemented by the SDK and easy to mock in tests.
type ToolSetResources interface {
	// List tool sets
	List(ctx context.Context, params *ToolSetListParams, opts ...RequestOption) (*Page[ToolSet], error)
	// Create a new tool set
	Create(ctx context.Context, params *ToolSetCreateParams, opts ...RequestOption) (*ToolSet, error)
	// Get a tool set by ID
	Retrieve(ctx context.Context, id string, params *ToolSetRetrieveParams, opts ...RequestOption) (*ToolSet, error)
	// Delete a tool set
	Delete(ctx context.Context, id string, params *ToolSetDeleteParams, opts ...RequestOption) error
	// Update a tool set
	Update(ctx context.Context, id string, params *ToolSetUpdateParams, opts ...RequestOption) (*ToolSet, error)
	// Archive a tool set
	Archive(ctx context.Context, id string, params *ToolSetArchiveParams, opts ...RequestOption) (*ToolSet, error)
	// Unarchive a tool set
	Unarchive(ctx context.Context, id string, params *ToolSetUnarchiveParams, opts ...RequestOption) (*ToolSet, error)
	// List tool set events
	ListEvents(ctx context.Context, toolSetID string, params *ToolSetListEventsParams, opts ...RequestOption) (*Page[ToolSetEvent], error)
	// Get consumed OpenAPI spec
	RetrieveOpenAPISpec(ctx context.Context, toolSetID string, params *ToolSetRetrieveOpenAPISpecParams, opts ...RequestOption) (*GetToolSetOpenAPISpecResponse, error)
	// List tool set usage
	ListUsage(ctx context.Context, toolSetID string, params *ToolSetListUsageParams, opts ...RequestOption) (*Page[ToolSetUsage], error)
	// Secrets returns the nested secrets resource group.
	Secrets() ToolSetSecretResources
	// Tools returns the nested tools resource group.
	Tools() ToolResources
}

type toolSetsService struct{ core *core }

var _ ToolSetResources = (*toolSetsService)(nil)

func (s *toolSetsService) Secrets() ToolSetSecretResources {
	return &toolSetSecretsService{core: s.core}
}

func (s *toolSetsService) Tools() ToolResources { return &toolsService{core: s.core} }

func (s *toolSetsService) List(ctx context.Context, params *ToolSetListParams, opts ...RequestOption) (*Page[ToolSet], error) {
	if params == nil {
		params = &ToolSetListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.State != nil {
		q.Set("state", string(*params.State))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListToolSetsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ToolSet], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *toolSetsService) Create(ctx context.Context, params *ToolSetCreateParams, opts ...RequestOption) (*ToolSet, error) {
	if params == nil {
		params = &ToolSetCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets", segWorkspaceID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out ToolSet
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *toolSetsService) Retrieve(ctx context.Context, id string, params *ToolSetRetrieveParams, opts ...RequestOption) (*ToolSet, error) {
	if params == nil {
		params = &ToolSetRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s", segWorkspaceID, segID)
	var out ToolSet
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *toolSetsService) Delete(ctx context.Context, id string, params *ToolSetDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &ToolSetDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s", segWorkspaceID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *toolSetsService) Update(ctx context.Context, id string, params *ToolSetUpdateParams, opts ...RequestOption) (*ToolSet, error) {
	if params == nil {
		params = &ToolSetUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s", segWorkspaceID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out ToolSet
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *toolSetsService) Archive(ctx context.Context, id string, params *ToolSetArchiveParams, opts ...RequestOption) (*ToolSet, error) {
	if params == nil {
		params = &ToolSetArchiveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s:archive", segWorkspaceID, segID)
	var out ToolSet
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *toolSetsService) Unarchive(ctx context.Context, id string, params *ToolSetUnarchiveParams, opts ...RequestOption) (*ToolSet, error) {
	if params == nil {
		params = &ToolSetUnarchiveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s:unarchive", segWorkspaceID, segID)
	var out ToolSet
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *toolSetsService) ListEvents(ctx context.Context, toolSetID string, params *ToolSetListEventsParams, opts ...RequestOption) (*Page[ToolSetEvent], error) {
	if params == nil {
		params = &ToolSetListEventsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segToolSetID, err := pathSegment("toolSetId", toolSetID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s/events", segWorkspaceID, segToolSetID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	var out ListToolSetEventsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ToolSetEvent], error) {
		p := base
		p.Cursor = &cursor
		return s.ListEvents(ctx, toolSetID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *toolSetsService) RetrieveOpenAPISpec(ctx context.Context, toolSetID string, params *ToolSetRetrieveOpenAPISpecParams, opts ...RequestOption) (*GetToolSetOpenAPISpecResponse, error) {
	if params == nil {
		params = &ToolSetRetrieveOpenAPISpecParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segToolSetID, err := pathSegment("toolSetId", toolSetID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s/openapi_spec", segWorkspaceID, segToolSetID)
	var out GetToolSetOpenAPISpecResponse
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *toolSetsService) ListUsage(ctx context.Context, toolSetID string, params *ToolSetListUsageParams, opts ...RequestOption) (*Page[ToolSetUsage], error) {
	if params == nil {
		params = &ToolSetListUsageParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segToolSetID, err := pathSegment("toolSetId", toolSetID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s/usage", segWorkspaceID, segToolSetID)
	q := url.Values{}
	if params.ToolID != nil {
		q.Set("toolId", (*params.ToolID))
	}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	var out ListToolSetUsageResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ToolSetUsage], error) {
		p := base
		p.Cursor = &cursor
		return s.ListUsage(ctx, toolSetID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}
