// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type WidgetSessionsSuite struct {
	suite.Suite
}

func TestWidgetSessionsSuite(t *testing.T) {
	suite.Run(t, new(WidgetSessionsSuite))
}

func (s *WidgetSessionsSuite) TestList() {
	g := loadGolden(s.T(), "WidgetSessionService_ListWidgetSessions")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.WidgetSessions().List(ctx, (&cadenya.WidgetSessionListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		WidgetID("sample").
		TenantID("sample").
		SubjectID("sample").
		State(cadenya.WidgetSessionServiceListWidgetSessionsState("STATE_ACTIVE")).
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widget_sessions", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WidgetSessions().List(ctx, (&cadenya.WidgetSessionListBuilder{}).
			Limit(1).
			Cursor("sample").
			WidgetID("sample").
			TenantID("sample").
			SubjectID("sample").
			State(cadenya.WidgetSessionServiceListWidgetSessionsState("STATE_ACTIVE")).
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetSessionsSuite) TestCreate() {
	g := loadGolden(s.T(), "WidgetSessionService_CreateWidgetSession")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WidgetSessions().Create(ctx, (&cadenya.WidgetSessionCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateOperationMetadata{}).
		Spec(&cadenya.WidgetSessionSpecParam{WidgetID: "sample"}).
		Secrets(cadenya.CreateWidgetSessionRequest_Secret{}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widget_sessions", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WidgetSessions().Create(ctx, (&cadenya.WidgetSessionCreateBuilder{}).
			Metadata(&cadenya.CreateOperationMetadata{}).
			Spec(&cadenya.WidgetSessionSpecParam{WidgetID: "sample"}).
			Secrets(cadenya.CreateWidgetSessionRequest_Secret{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetSessionsSuite) TestDeleteTenant() {
	g := loadGolden(s.T(), "WidgetSessionService_DeleteTenantWidgetSessions")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WidgetSessions().DeleteTenant(ctx, (&cadenya.WidgetSessionDeleteTenantBuilder{}).
		WorkspaceID("sample").
		TenantID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widget_sessions", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WidgetSessions().DeleteTenant(ctx, (&cadenya.WidgetSessionDeleteTenantBuilder{}).
			TenantID("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetSessionsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "WidgetSessionService_GetWidgetSession")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WidgetSessions().Retrieve(ctx, "sample", (&cadenya.WidgetSessionRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widget_sessions/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WidgetSessions().Retrieve(ctx, "sample", (&cadenya.WidgetSessionRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetSessionsSuite) TestDelete() {
	g := loadGolden(s.T(), "WidgetSessionService_DeleteWidgetSession")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.WidgetSessions().Delete(ctx, "sample", (&cadenya.WidgetSessionDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widget_sessions/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.WidgetSessions().Delete(ctx, "sample", (&cadenya.WidgetSessionDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WidgetSessionsSuite) TestRevoke() {
	g := loadGolden(s.T(), "WidgetSessionService_RevokeWidgetSession")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WidgetSessions().Revoke(ctx, "sample", (&cadenya.WidgetSessionRevokeBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/widget_sessions/sample:revoke", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WidgetSessions().Revoke(ctx, "sample", (&cadenya.WidgetSessionRevokeBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
