// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type AiProviderKeysSuite struct {
	suite.Suite
}

func TestAiProviderKeysSuite(t *testing.T) {
	suite.Run(t, new(AiProviderKeysSuite))
}

func (s *AiProviderKeysSuite) TestList() {
	g := loadGolden(s.T(), "AIProviderKeyService_ListAIProviderKeys")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.AIProviderKeys().List(ctx, (&cadenya.AIProviderKeyListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		Promotional(true).
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/ai_provider_keys", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AIProviderKeys().List(ctx, (&cadenya.AIProviderKeyListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			Promotional(true).
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AiProviderKeysSuite) TestCreate() {
	g := loadGolden(s.T(), "AIProviderKeyService_CreateAIProviderKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AIProviderKeys().Create(ctx, (&cadenya.AIProviderKeyCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AIProviderKeySpec{}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/ai_provider_keys", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AIProviderKeys().Create(ctx, (&cadenya.AIProviderKeyCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AIProviderKeySpec{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AiProviderKeysSuite) TestRetrieve() {
	g := loadGolden(s.T(), "AIProviderKeyService_GetAIProviderKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AIProviderKeys().Retrieve(ctx, "sample", (&cadenya.AIProviderKeyRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/ai_provider_keys/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AIProviderKeys().Retrieve(ctx, "sample", (&cadenya.AIProviderKeyRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AiProviderKeysSuite) TestDelete() {
	g := loadGolden(s.T(), "AIProviderKeyService_DeleteAIProviderKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.AIProviderKeys().Delete(ctx, "sample", (&cadenya.AIProviderKeyDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/ai_provider_keys/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.AIProviderKeys().Delete(ctx, "sample", (&cadenya.AIProviderKeyDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AiProviderKeysSuite) TestUpdate() {
	g := loadGolden(s.T(), "AIProviderKeyService_UpdateAIProviderKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AIProviderKeys().Update(ctx, "sample", (&cadenya.AIProviderKeyUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AIProviderKeySpec{}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/ai_provider_keys/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AIProviderKeys().Update(ctx, "sample", (&cadenya.AIProviderKeyUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AIProviderKeySpec{}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
