// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"net/url"
	"strconv"
)

type WorkspaceListParams struct {
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
	Labels      *string `json:"labels,omitempty"`
}

// WorkspaceListBuilder builds a WorkspaceListParams fluently.
type WorkspaceListBuilder struct {
	params WorkspaceListParams
}

func (b *WorkspaceListBuilder) Limit(v int32) *WorkspaceListBuilder {
	b.params.Limit = &v
	return b
}

func (b *WorkspaceListBuilder) Cursor(v string) *WorkspaceListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *WorkspaceListBuilder) SortOrder(v string) *WorkspaceListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *WorkspaceListBuilder) IncludeInfo(v bool) *WorkspaceListBuilder {
	b.params.IncludeInfo = &v
	return b
}

func (b *WorkspaceListBuilder) Labels(v string) *WorkspaceListBuilder {
	b.params.Labels = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WorkspaceListBuilder) ToParams() *WorkspaceListParams {
	p := b.params
	return &p
}

// WorkspaceResources is implemented by the SDK and easy to mock in tests.
type WorkspaceResources interface {
	// List workspaces
	List(ctx context.Context, params *WorkspaceListParams, opts ...RequestOption) (*Page[Workspace], error)
}

type workspacesService struct{ core *core }

var _ WorkspaceResources = (*workspacesService)(nil)

func (s *workspacesService) List(ctx context.Context, params *WorkspaceListParams, opts ...RequestOption) (*Page[Workspace], error) {
	if params == nil {
		params = &WorkspaceListParams{}
	}
	path := "/v1/workspaces"
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	var out ListWorkspacesResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[Workspace], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}
