// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type AgentPoolListParams struct {
	WorkspaceID *string                              `json:"workspaceId,omitempty"`
	Limit       *int32                               `json:"limit,omitempty"`
	Cursor      *string                              `json:"cursor,omitempty"`
	Prefix      *string                              `json:"prefix,omitempty"`
	Query       *string                              `json:"query,omitempty"`
	State       *AgentPoolServiceListAgentPoolsState `json:"state,omitempty"`
	Labels      *string                              `json:"labels,omitempty"`
	SortOrder   *string                              `json:"sortOrder,omitempty"`
	IncludeInfo *bool                                `json:"includeInfo,omitempty"`
}

// AgentPoolListBuilder builds a AgentPoolListParams fluently.
type AgentPoolListBuilder struct {
	params AgentPoolListParams
}

func (b *AgentPoolListBuilder) WorkspaceID(v string) *AgentPoolListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentPoolListBuilder) Limit(v int32) *AgentPoolListBuilder {
	b.params.Limit = &v
	return b
}

func (b *AgentPoolListBuilder) Cursor(v string) *AgentPoolListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *AgentPoolListBuilder) Prefix(v string) *AgentPoolListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *AgentPoolListBuilder) Query(v string) *AgentPoolListBuilder {
	b.params.Query = &v
	return b
}

func (b *AgentPoolListBuilder) State(v AgentPoolServiceListAgentPoolsState) *AgentPoolListBuilder {
	b.params.State = &v
	return b
}

func (b *AgentPoolListBuilder) Labels(v string) *AgentPoolListBuilder {
	b.params.Labels = &v
	return b
}

func (b *AgentPoolListBuilder) SortOrder(v string) *AgentPoolListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *AgentPoolListBuilder) IncludeInfo(v bool) *AgentPoolListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolListBuilder) ToParams() *AgentPoolListParams {
	p := b.params
	return &p
}

type AgentPoolCreateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *CreateResourceMetadata `json:"metadata"`
	Spec        *AgentPoolSpec          `json:"spec"`
}

// AgentPoolCreateBuilder builds a AgentPoolCreateParams fluently.
type AgentPoolCreateBuilder struct {
	params AgentPoolCreateParams
}

func (b *AgentPoolCreateBuilder) WorkspaceID(v string) *AgentPoolCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentPoolCreateBuilder) Metadata(v *CreateResourceMetadata) *AgentPoolCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AgentPoolCreateBuilder) Spec(v *AgentPoolSpec) *AgentPoolCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolCreateBuilder) ToParams() *AgentPoolCreateParams {
	p := b.params
	return &p
}

type AgentPoolRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentPoolRetrieveBuilder builds a AgentPoolRetrieveParams fluently.
type AgentPoolRetrieveBuilder struct {
	params AgentPoolRetrieveParams
}

func (b *AgentPoolRetrieveBuilder) WorkspaceID(v string) *AgentPoolRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolRetrieveBuilder) ToParams() *AgentPoolRetrieveParams {
	p := b.params
	return &p
}

type AgentPoolDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentPoolDeleteBuilder builds a AgentPoolDeleteParams fluently.
type AgentPoolDeleteBuilder struct {
	params AgentPoolDeleteParams
}

func (b *AgentPoolDeleteBuilder) WorkspaceID(v string) *AgentPoolDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolDeleteBuilder) ToParams() *AgentPoolDeleteParams {
	p := b.params
	return &p
}

type AgentPoolUpdateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *UpdateResourceMetadata `json:"metadata,omitempty"`
	Spec        *AgentPoolUpdateSpec    `json:"spec,omitempty"`
	UpdateMask  *string                 `json:"updateMask,omitempty"`
}

// AgentPoolUpdateBuilder builds a AgentPoolUpdateParams fluently.
type AgentPoolUpdateBuilder struct {
	params AgentPoolUpdateParams
}

func (b *AgentPoolUpdateBuilder) WorkspaceID(v string) *AgentPoolUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentPoolUpdateBuilder) Metadata(v *UpdateResourceMetadata) *AgentPoolUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AgentPoolUpdateBuilder) Spec(v *AgentPoolUpdateSpec) *AgentPoolUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *AgentPoolUpdateBuilder) UpdateMask(v string) *AgentPoolUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolUpdateBuilder) ToParams() *AgentPoolUpdateParams {
	p := b.params
	return &p
}

type AgentPoolActivateParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentPoolActivateBuilder builds a AgentPoolActivateParams fluently.
type AgentPoolActivateBuilder struct {
	params AgentPoolActivateParams
}

func (b *AgentPoolActivateBuilder) WorkspaceID(v string) *AgentPoolActivateBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolActivateBuilder) ToParams() *AgentPoolActivateParams {
	p := b.params
	return &p
}

type AgentPoolArchiveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentPoolArchiveBuilder builds a AgentPoolArchiveParams fluently.
type AgentPoolArchiveBuilder struct {
	params AgentPoolArchiveParams
}

func (b *AgentPoolArchiveBuilder) WorkspaceID(v string) *AgentPoolArchiveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolArchiveBuilder) ToParams() *AgentPoolArchiveParams {
	p := b.params
	return &p
}

type AgentPoolDeactivateParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentPoolDeactivateBuilder builds a AgentPoolDeactivateParams fluently.
type AgentPoolDeactivateBuilder struct {
	params AgentPoolDeactivateParams
}

func (b *AgentPoolDeactivateBuilder) WorkspaceID(v string) *AgentPoolDeactivateBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolDeactivateBuilder) ToParams() *AgentPoolDeactivateParams {
	p := b.params
	return &p
}

type AgentPoolUnarchiveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentPoolUnarchiveBuilder builds a AgentPoolUnarchiveParams fluently.
type AgentPoolUnarchiveBuilder struct {
	params AgentPoolUnarchiveParams
}

func (b *AgentPoolUnarchiveBuilder) WorkspaceID(v string) *AgentPoolUnarchiveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPoolUnarchiveBuilder) ToParams() *AgentPoolUnarchiveParams {
	p := b.params
	return &p
}

// AgentPoolResources is implemented by the SDK and easy to mock in tests.
type AgentPoolResources interface {
	// List agent pools
	List(ctx context.Context, params *AgentPoolListParams, opts ...RequestOption) (*Page[AgentPool], error)
	// Create a new agent pool
	Create(ctx context.Context, params *AgentPoolCreateParams, opts ...RequestOption) (*AgentPool, error)
	// Get an agent pool by ID
	Retrieve(ctx context.Context, id string, params *AgentPoolRetrieveParams, opts ...RequestOption) (*AgentPool, error)
	// Delete an agent pool
	Delete(ctx context.Context, id string, params *AgentPoolDeleteParams, opts ...RequestOption) error
	// Update an agent pool
	Update(ctx context.Context, id string, params *AgentPoolUpdateParams, opts ...RequestOption) (*AgentPool, error)
	// Activate an agent pool
	Activate(ctx context.Context, id string, params *AgentPoolActivateParams, opts ...RequestOption) (*AgentPool, error)
	// Archive an agent pool
	Archive(ctx context.Context, id string, params *AgentPoolArchiveParams, opts ...RequestOption) (*AgentPool, error)
	// Deactivate an agent pool
	Deactivate(ctx context.Context, id string, params *AgentPoolDeactivateParams, opts ...RequestOption) (*AgentPool, error)
	// Unarchive an agent pool
	Unarchive(ctx context.Context, id string, params *AgentPoolUnarchiveParams, opts ...RequestOption) (*AgentPool, error)
}

type agentPoolsService struct{ core *core }

var _ AgentPoolResources = (*agentPoolsService)(nil)

func (s *agentPoolsService) List(ctx context.Context, params *AgentPoolListParams, opts ...RequestOption) (*Page[AgentPool], error) {
	if params == nil {
		params = &AgentPoolListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.State != nil {
		q.Set("state", string(*params.State))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListAgentPoolsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[AgentPool], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *agentPoolsService) Create(ctx context.Context, params *AgentPoolCreateParams, opts ...RequestOption) (*AgentPool, error) {
	if params == nil {
		params = &AgentPoolCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools", segWorkspaceID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out AgentPool
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentPoolsService) Retrieve(ctx context.Context, id string, params *AgentPoolRetrieveParams, opts ...RequestOption) (*AgentPool, error) {
	if params == nil {
		params = &AgentPoolRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools/%s", segWorkspaceID, segID)
	var out AgentPool
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentPoolsService) Delete(ctx context.Context, id string, params *AgentPoolDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &AgentPoolDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools/%s", segWorkspaceID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *agentPoolsService) Update(ctx context.Context, id string, params *AgentPoolUpdateParams, opts ...RequestOption) (*AgentPool, error) {
	if params == nil {
		params = &AgentPoolUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools/%s", segWorkspaceID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out AgentPool
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentPoolsService) Activate(ctx context.Context, id string, params *AgentPoolActivateParams, opts ...RequestOption) (*AgentPool, error) {
	if params == nil {
		params = &AgentPoolActivateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools/%s:activate", segWorkspaceID, segID)
	var out AgentPool
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentPoolsService) Archive(ctx context.Context, id string, params *AgentPoolArchiveParams, opts ...RequestOption) (*AgentPool, error) {
	if params == nil {
		params = &AgentPoolArchiveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools/%s:archive", segWorkspaceID, segID)
	var out AgentPool
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentPoolsService) Deactivate(ctx context.Context, id string, params *AgentPoolDeactivateParams, opts ...RequestOption) (*AgentPool, error) {
	if params == nil {
		params = &AgentPoolDeactivateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools/%s:deactivate", segWorkspaceID, segID)
	var out AgentPool
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentPoolsService) Unarchive(ctx context.Context, id string, params *AgentPoolUnarchiveParams, opts ...RequestOption) (*AgentPool, error) {
	if params == nil {
		params = &AgentPoolUnarchiveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agent_pools/%s:unarchive", segWorkspaceID, segID)
	var out AgentPool
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
