// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type TenantListParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	Query       *string `json:"query,omitempty"`
	Labels      *string `json:"labels,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
}

// TenantListBuilder builds a TenantListParams fluently.
type TenantListBuilder struct {
	params TenantListParams
}

func (b *TenantListBuilder) WorkspaceID(v string) *TenantListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *TenantListBuilder) Limit(v int32) *TenantListBuilder {
	b.params.Limit = &v
	return b
}

func (b *TenantListBuilder) Cursor(v string) *TenantListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *TenantListBuilder) Query(v string) *TenantListBuilder {
	b.params.Query = &v
	return b
}

func (b *TenantListBuilder) Labels(v string) *TenantListBuilder {
	b.params.Labels = &v
	return b
}

func (b *TenantListBuilder) SortOrder(v string) *TenantListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *TenantListBuilder) IncludeInfo(v bool) *TenantListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *TenantListBuilder) ToParams() *TenantListParams {
	p := b.params
	return &p
}

type TenantRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
}

// TenantRetrieveBuilder builds a TenantRetrieveParams fluently.
type TenantRetrieveBuilder struct {
	params TenantRetrieveParams
}

func (b *TenantRetrieveBuilder) WorkspaceID(v string) *TenantRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *TenantRetrieveBuilder) IncludeInfo(v bool) *TenantRetrieveBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *TenantRetrieveBuilder) ToParams() *TenantRetrieveParams {
	p := b.params
	return &p
}

type TenantDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// TenantDeleteBuilder builds a TenantDeleteParams fluently.
type TenantDeleteBuilder struct {
	params TenantDeleteParams
}

func (b *TenantDeleteBuilder) WorkspaceID(v string) *TenantDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *TenantDeleteBuilder) ToParams() *TenantDeleteParams {
	p := b.params
	return &p
}

type TenantListSubjectsParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	Query       *string `json:"query,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
}

// TenantListSubjectsBuilder builds a TenantListSubjectsParams fluently.
type TenantListSubjectsBuilder struct {
	params TenantListSubjectsParams
}

func (b *TenantListSubjectsBuilder) WorkspaceID(v string) *TenantListSubjectsBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *TenantListSubjectsBuilder) Limit(v int32) *TenantListSubjectsBuilder {
	b.params.Limit = &v
	return b
}

func (b *TenantListSubjectsBuilder) Cursor(v string) *TenantListSubjectsBuilder {
	b.params.Cursor = &v
	return b
}

func (b *TenantListSubjectsBuilder) Query(v string) *TenantListSubjectsBuilder {
	b.params.Query = &v
	return b
}

func (b *TenantListSubjectsBuilder) SortOrder(v string) *TenantListSubjectsBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *TenantListSubjectsBuilder) IncludeInfo(v bool) *TenantListSubjectsBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *TenantListSubjectsBuilder) ToParams() *TenantListSubjectsParams {
	p := b.params
	return &p
}

// TenantResources is implemented by the SDK and easy to mock in tests.
type TenantResources interface {
	// List tenants
	List(ctx context.Context, params *TenantListParams, opts ...RequestOption) (*Page[Tenant], error)
	// Get a tenant by ID
	Retrieve(ctx context.Context, id string, params *TenantRetrieveParams, opts ...RequestOption) (*Tenant, error)
	// Erase a tenant
	Delete(ctx context.Context, id string, params *TenantDeleteParams, opts ...RequestOption) (*Tenant, error)
	// List a tenant's subjects
	ListSubjects(ctx context.Context, tenantID string, params *TenantListSubjectsParams, opts ...RequestOption) (*Page[Subject], error)
}

type tenantsService struct{ core *core }

var _ TenantResources = (*tenantsService)(nil)

func (s *tenantsService) List(ctx context.Context, params *TenantListParams, opts ...RequestOption) (*Page[Tenant], error) {
	if params == nil {
		params = &TenantListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tenants", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListTenantsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[Tenant], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *tenantsService) Retrieve(ctx context.Context, id string, params *TenantRetrieveParams, opts ...RequestOption) (*Tenant, error) {
	if params == nil {
		params = &TenantRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tenants/%s", segWorkspaceID, segID)
	q := url.Values{}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out Tenant
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *tenantsService) Delete(ctx context.Context, id string, params *TenantDeleteParams, opts ...RequestOption) (*Tenant, error) {
	if params == nil {
		params = &TenantDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tenants/%s", segWorkspaceID, segID)
	var out Tenant
	if err := s.core.do(ctx, "DELETE", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *tenantsService) ListSubjects(ctx context.Context, tenantID string, params *TenantListSubjectsParams, opts ...RequestOption) (*Page[Subject], error) {
	if params == nil {
		params = &TenantListSubjectsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segTenantID, err := pathSegment("tenantId", tenantID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tenants/%s/subjects", segWorkspaceID, segTenantID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListTenantSubjectsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[Subject], error) {
		p := base
		p.Cursor = &cursor
		return s.ListSubjects(ctx, tenantID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}
