// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type MemoryLayersSuite struct {
	suite.Suite
}

func TestMemoryLayersSuite(t *testing.T) {
	suite.Run(t, new(MemoryLayersSuite))
}

func (s *MemoryLayersSuite) TestList() {
	g := loadGolden(s.T(), "MemoryService_ListMemoryLayers")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.MemoryLayers().List(ctx, (&cadenya.MemoryLayerListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		Type(cadenya.MemoryServiceListMemoryLayersType("MEMORY_LAYER_TYPE_EPISODIC")).
		AgentID("sample").
		EpisodicKeyPrefix("sample").
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.MemoryLayers().List(ctx, (&cadenya.MemoryLayerListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			Type(cadenya.MemoryServiceListMemoryLayersType("MEMORY_LAYER_TYPE_EPISODIC")).
			AgentID("sample").
			EpisodicKeyPrefix("sample").
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *MemoryLayersSuite) TestCreate() {
	g := loadGolden(s.T(), "MemoryService_CreateMemoryLayer")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.MemoryLayers().Create(ctx, (&cadenya.MemoryLayerCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.MemoryLayerSpecParam{
			Type:        cadenya.MemoryLayerSpecType("MEMORY_LAYER_TYPE_EPISODIC"),
			EpisodicKey: "customer/42",
		}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.MemoryLayers().Create(ctx, (&cadenya.MemoryLayerCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.MemoryLayerSpecParam{Type: cadenya.MemoryLayerSpecType("MEMORY_LAYER_TYPE_EPISODIC")}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *MemoryLayersSuite) TestRetrieve() {
	g := loadGolden(s.T(), "MemoryService_GetMemoryLayer")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.MemoryLayers().Retrieve(ctx, "sample", (&cadenya.MemoryLayerRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.MemoryLayers().Retrieve(ctx, "sample", (&cadenya.MemoryLayerRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *MemoryLayersSuite) TestDelete() {
	g := loadGolden(s.T(), "MemoryService_DeleteMemoryLayer")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.MemoryLayers().Delete(ctx, "sample", (&cadenya.MemoryLayerDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.MemoryLayers().Delete(ctx, "sample", (&cadenya.MemoryLayerDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *MemoryLayersSuite) TestUpdate() {
	g := loadGolden(s.T(), "MemoryService_UpdateMemoryLayer")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.MemoryLayers().Update(ctx, "sample", (&cadenya.MemoryLayerUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.MemoryLayerSpecParam{
			Type:        cadenya.MemoryLayerSpecType("MEMORY_LAYER_TYPE_EPISODIC"),
			EpisodicKey: "customer/42",
		}).
		UpdateMask("spec.episodic_key").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.MemoryLayers().Update(ctx, "sample", (&cadenya.MemoryLayerUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.MemoryLayerSpecParam{Type: cadenya.MemoryLayerSpecType("MEMORY_LAYER_TYPE_EPISODIC")}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
