// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type AgentSchedulesSuite struct {
	suite.Suite
}

func TestAgentSchedulesSuite(t *testing.T) {
	suite.Run(t, new(AgentSchedulesSuite))
}

func (s *AgentSchedulesSuite) TestList() {
	g := loadGolden(s.T(), "AgentScheduleService_ListAgentSchedules")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.Agents().Schedules().List(ctx, "sample", (&cadenya.AgentScheduleListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/schedules", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Schedules().List(ctx, "sample", (&cadenya.AgentScheduleListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentSchedulesSuite) TestCreate() {
	g := loadGolden(s.T(), "AgentScheduleService_CreateAgentSchedule")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Schedules().Create(ctx, "sample", (&cadenya.AgentScheduleCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AgentScheduleSpec{Schedule: &cadenya.AgentScheduleSpec_Schedule{}}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/schedules", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Schedules().Create(ctx, "sample", (&cadenya.AgentScheduleCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AgentScheduleSpec{Schedule: &cadenya.AgentScheduleSpec_Schedule{}}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentSchedulesSuite) TestRetrieve() {
	g := loadGolden(s.T(), "AgentScheduleService_GetAgentSchedule")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Schedules().Retrieve(ctx, "sample", "sample", (&cadenya.AgentScheduleRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/schedules/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Schedules().Retrieve(ctx, "sample", "sample", (&cadenya.AgentScheduleRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentSchedulesSuite) TestDelete() {
	g := loadGolden(s.T(), "AgentScheduleService_DeleteAgentSchedule")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.Agents().Schedules().Delete(ctx, "sample", "sample", (&cadenya.AgentScheduleDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/schedules/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.Agents().Schedules().Delete(ctx, "sample", "sample", (&cadenya.AgentScheduleDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentSchedulesSuite) TestUpdate() {
	g := loadGolden(s.T(), "AgentScheduleService_UpdateAgentSchedule")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Schedules().Update(ctx, "sample", "sample", (&cadenya.AgentScheduleUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AgentScheduleSpec{Schedule: &cadenya.AgentScheduleSpec_Schedule{}}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/schedules/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Schedules().Update(ctx, "sample", "sample", (&cadenya.AgentScheduleUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AgentScheduleSpec{Schedule: &cadenya.AgentScheduleSpec_Schedule{}}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentSchedulesSuite) TestArchive() {
	g := loadGolden(s.T(), "AgentScheduleService_ArchiveAgentSchedule")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Schedules().Archive(ctx, "sample", "sample", (&cadenya.AgentScheduleArchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/schedules/sample:archive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Schedules().Archive(ctx, "sample", "sample", (&cadenya.AgentScheduleArchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentSchedulesSuite) TestPause() {
	g := loadGolden(s.T(), "AgentScheduleService_PauseAgentSchedule")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Schedules().Pause(ctx, "sample", "sample", (&cadenya.AgentSchedulePauseBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/schedules/sample:pause", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Schedules().Pause(ctx, "sample", "sample", (&cadenya.AgentSchedulePauseBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentSchedulesSuite) TestResume() {
	g := loadGolden(s.T(), "AgentScheduleService_ResumeAgentSchedule")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Schedules().Resume(ctx, "sample", "sample", (&cadenya.AgentScheduleResumeBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/schedules/sample:resume", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Schedules().Resume(ctx, "sample", "sample", (&cadenya.AgentScheduleResumeBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
