// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type AgentVariationListParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
	Labels      *string `json:"labels,omitempty"`
}

// AgentVariationListBuilder builds a AgentVariationListParams fluently.
type AgentVariationListBuilder struct {
	params AgentVariationListParams
}

func (b *AgentVariationListBuilder) WorkspaceID(v string) *AgentVariationListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentVariationListBuilder) Limit(v int32) *AgentVariationListBuilder {
	b.params.Limit = &v
	return b
}

func (b *AgentVariationListBuilder) Cursor(v string) *AgentVariationListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *AgentVariationListBuilder) SortOrder(v string) *AgentVariationListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *AgentVariationListBuilder) IncludeInfo(v bool) *AgentVariationListBuilder {
	b.params.IncludeInfo = &v
	return b
}

func (b *AgentVariationListBuilder) Labels(v string) *AgentVariationListBuilder {
	b.params.Labels = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationListBuilder) ToParams() *AgentVariationListParams {
	p := b.params
	return &p
}

type AgentVariationCreateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *CreateResourceMetadata `json:"metadata"`
	Spec        *AgentVariationSpec     `json:"spec"`
}

// AgentVariationCreateBuilder builds a AgentVariationCreateParams fluently.
type AgentVariationCreateBuilder struct {
	params AgentVariationCreateParams
}

func (b *AgentVariationCreateBuilder) WorkspaceID(v string) *AgentVariationCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentVariationCreateBuilder) Metadata(v *CreateResourceMetadata) *AgentVariationCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AgentVariationCreateBuilder) Spec(v *AgentVariationSpec) *AgentVariationCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationCreateBuilder) ToParams() *AgentVariationCreateParams {
	p := b.params
	return &p
}

type AgentVariationRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentVariationRetrieveBuilder builds a AgentVariationRetrieveParams fluently.
type AgentVariationRetrieveBuilder struct {
	params AgentVariationRetrieveParams
}

func (b *AgentVariationRetrieveBuilder) WorkspaceID(v string) *AgentVariationRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationRetrieveBuilder) ToParams() *AgentVariationRetrieveParams {
	p := b.params
	return &p
}

type AgentVariationDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentVariationDeleteBuilder builds a AgentVariationDeleteParams fluently.
type AgentVariationDeleteBuilder struct {
	params AgentVariationDeleteParams
}

func (b *AgentVariationDeleteBuilder) WorkspaceID(v string) *AgentVariationDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationDeleteBuilder) ToParams() *AgentVariationDeleteParams {
	p := b.params
	return &p
}

type AgentVariationUpdateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *UpdateResourceMetadata `json:"metadata,omitempty"`
	Spec        *AgentVariationSpec     `json:"spec,omitempty"`
	UpdateMask  *string                 `json:"updateMask,omitempty"`
}

// AgentVariationUpdateBuilder builds a AgentVariationUpdateParams fluently.
type AgentVariationUpdateBuilder struct {
	params AgentVariationUpdateParams
}

func (b *AgentVariationUpdateBuilder) WorkspaceID(v string) *AgentVariationUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentVariationUpdateBuilder) Metadata(v *UpdateResourceMetadata) *AgentVariationUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AgentVariationUpdateBuilder) Spec(v *AgentVariationSpec) *AgentVariationUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *AgentVariationUpdateBuilder) UpdateMask(v string) *AgentVariationUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationUpdateBuilder) ToParams() *AgentVariationUpdateParams {
	p := b.params
	return &p
}

type AgentVariationAddAssignmentParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	// Body is sent as the entire request body.
	Body *AddAgentVariationAssignmentRequestParam `json:"body"`
}

// AgentVariationAddAssignmentBuilder builds a AgentVariationAddAssignmentParams fluently.
type AgentVariationAddAssignmentBuilder struct {
	params AgentVariationAddAssignmentParams
}

func (b *AgentVariationAddAssignmentBuilder) WorkspaceID(v string) *AgentVariationAddAssignmentBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentVariationAddAssignmentBuilder) Body(v *AddAgentVariationAssignmentRequestParam) *AgentVariationAddAssignmentBuilder {
	b.params.Body = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationAddAssignmentBuilder) ToParams() *AgentVariationAddAssignmentParams {
	p := b.params
	return &p
}

type AgentVariationRemoveAssignmentParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentVariationRemoveAssignmentBuilder builds a AgentVariationRemoveAssignmentParams fluently.
type AgentVariationRemoveAssignmentBuilder struct {
	params AgentVariationRemoveAssignmentParams
}

func (b *AgentVariationRemoveAssignmentBuilder) WorkspaceID(v string) *AgentVariationRemoveAssignmentBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationRemoveAssignmentBuilder) ToParams() *AgentVariationRemoveAssignmentParams {
	p := b.params
	return &p
}

type AgentVariationAddMemoryLayerParams struct {
	WorkspaceID   *string `json:"workspaceId,omitempty"`
	MemoryLayerID string  `json:"memoryLayerId"`
	Position      *int32  `json:"position,omitempty"`
}

// AgentVariationAddMemoryLayerBuilder builds a AgentVariationAddMemoryLayerParams fluently.
type AgentVariationAddMemoryLayerBuilder struct {
	params AgentVariationAddMemoryLayerParams
}

func (b *AgentVariationAddMemoryLayerBuilder) WorkspaceID(v string) *AgentVariationAddMemoryLayerBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentVariationAddMemoryLayerBuilder) MemoryLayerID(v string) *AgentVariationAddMemoryLayerBuilder {
	b.params.MemoryLayerID = v
	return b
}

func (b *AgentVariationAddMemoryLayerBuilder) Position(v int32) *AgentVariationAddMemoryLayerBuilder {
	b.params.Position = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationAddMemoryLayerBuilder) ToParams() *AgentVariationAddMemoryLayerParams {
	p := b.params
	return &p
}

type AgentVariationRemoveMemoryLayerParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentVariationRemoveMemoryLayerBuilder builds a AgentVariationRemoveMemoryLayerParams fluently.
type AgentVariationRemoveMemoryLayerBuilder struct {
	params AgentVariationRemoveMemoryLayerParams
}

func (b *AgentVariationRemoveMemoryLayerBuilder) WorkspaceID(v string) *AgentVariationRemoveMemoryLayerBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationRemoveMemoryLayerBuilder) ToParams() *AgentVariationRemoveMemoryLayerParams {
	p := b.params
	return &p
}

type AgentVariationUpdateMemoryLayerParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Position    *int32  `json:"position,omitempty"`
}

// AgentVariationUpdateMemoryLayerBuilder builds a AgentVariationUpdateMemoryLayerParams fluently.
type AgentVariationUpdateMemoryLayerBuilder struct {
	params AgentVariationUpdateMemoryLayerParams
}

func (b *AgentVariationUpdateMemoryLayerBuilder) WorkspaceID(v string) *AgentVariationUpdateMemoryLayerBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentVariationUpdateMemoryLayerBuilder) Position(v int32) *AgentVariationUpdateMemoryLayerBuilder {
	b.params.Position = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentVariationUpdateMemoryLayerBuilder) ToParams() *AgentVariationUpdateMemoryLayerParams {
	p := b.params
	return &p
}

// AgentVariationResources is implemented by the SDK and easy to mock in tests.
type AgentVariationResources interface {
	// List variations
	List(ctx context.Context, agentID string, params *AgentVariationListParams, opts ...RequestOption) (*Page[AgentVariation], error)
	// Create a new variation
	Create(ctx context.Context, agentID string, params *AgentVariationCreateParams, opts ...RequestOption) (*AgentVariation, error)
	// Get a variation by ID
	Retrieve(ctx context.Context, agentID string, id string, params *AgentVariationRetrieveParams, opts ...RequestOption) (*AgentVariation, error)
	// Delete a variation
	Delete(ctx context.Context, agentID string, id string, params *AgentVariationDeleteParams, opts ...RequestOption) error
	// Update a variation
	Update(ctx context.Context, agentID string, id string, params *AgentVariationUpdateParams, opts ...RequestOption) (*AgentVariation, error)
	// Add an assignment to a variation
	AddAssignment(ctx context.Context, agentID string, variationID string, params *AgentVariationAddAssignmentParams, opts ...RequestOption) (*VariationAssignment, error)
	// Remove an assignment from a variation
	RemoveAssignment(ctx context.Context, agentID string, variationID string, id string, params *AgentVariationRemoveAssignmentParams, opts ...RequestOption) error
	// Attach a memory layer to a variation
	AddMemoryLayer(ctx context.Context, agentID string, variationID string, params *AgentVariationAddMemoryLayerParams, opts ...RequestOption) (*VariationMemoryLayerAssignment, error)
	// Remove a memory layer assignment from a variation
	RemoveMemoryLayer(ctx context.Context, agentID string, variationID string, id string, params *AgentVariationRemoveMemoryLayerParams, opts ...RequestOption) error
	// Update a variation's memory layer assignment
	UpdateMemoryLayer(ctx context.Context, agentID string, variationID string, id string, params *AgentVariationUpdateMemoryLayerParams, opts ...RequestOption) (*VariationMemoryLayerAssignment, error)
}

type agentVariationsService struct{ core *core }

var _ AgentVariationResources = (*agentVariationsService)(nil)

func (s *agentVariationsService) List(ctx context.Context, agentID string, params *AgentVariationListParams, opts ...RequestOption) (*Page[AgentVariation], error) {
	if params == nil {
		params = &AgentVariationListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations", segWorkspaceID, segAgentID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	var out ListAgentVariationsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[AgentVariation], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, agentID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *agentVariationsService) Create(ctx context.Context, agentID string, params *AgentVariationCreateParams, opts ...RequestOption) (*AgentVariation, error) {
	if params == nil {
		params = &AgentVariationCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations", segWorkspaceID, segAgentID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out AgentVariation
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentVariationsService) Retrieve(ctx context.Context, agentID string, id string, params *AgentVariationRetrieveParams, opts ...RequestOption) (*AgentVariation, error) {
	if params == nil {
		params = &AgentVariationRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations/%s", segWorkspaceID, segAgentID, segID)
	var out AgentVariation
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentVariationsService) Delete(ctx context.Context, agentID string, id string, params *AgentVariationDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &AgentVariationDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations/%s", segWorkspaceID, segAgentID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *agentVariationsService) Update(ctx context.Context, agentID string, id string, params *AgentVariationUpdateParams, opts ...RequestOption) (*AgentVariation, error) {
	if params == nil {
		params = &AgentVariationUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations/%s", segWorkspaceID, segAgentID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out AgentVariation
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentVariationsService) AddAssignment(ctx context.Context, agentID string, variationID string, params *AgentVariationAddAssignmentParams, opts ...RequestOption) (*VariationAssignment, error) {
	if params == nil {
		params = &AgentVariationAddAssignmentParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segVariationID, err := pathSegment("variationId", variationID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations/%s/assignments", segWorkspaceID, segAgentID, segVariationID)
	var out VariationAssignment
	if err := s.core.do(ctx, "POST", path, nil, params.Body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentVariationsService) RemoveAssignment(ctx context.Context, agentID string, variationID string, id string, params *AgentVariationRemoveAssignmentParams, opts ...RequestOption) error {
	if params == nil {
		params = &AgentVariationRemoveAssignmentParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return err
	}
	segVariationID, err := pathSegment("variationId", variationID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations/%s/assignments/%s", segWorkspaceID, segAgentID, segVariationID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *agentVariationsService) AddMemoryLayer(ctx context.Context, agentID string, variationID string, params *AgentVariationAddMemoryLayerParams, opts ...RequestOption) (*VariationMemoryLayerAssignment, error) {
	if params == nil {
		params = &AgentVariationAddMemoryLayerParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segVariationID, err := pathSegment("variationId", variationID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations/%s/memory_layer_assignments", segWorkspaceID, segAgentID, segVariationID)
	body := map[string]any{}
	body["memoryLayerId"] = params.MemoryLayerID
	if params.Position != nil {
		body["position"] = params.Position
	}
	var out VariationMemoryLayerAssignment
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentVariationsService) RemoveMemoryLayer(ctx context.Context, agentID string, variationID string, id string, params *AgentVariationRemoveMemoryLayerParams, opts ...RequestOption) error {
	if params == nil {
		params = &AgentVariationRemoveMemoryLayerParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return err
	}
	segVariationID, err := pathSegment("variationId", variationID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations/%s/memory_layer_assignments/%s", segWorkspaceID, segAgentID, segVariationID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *agentVariationsService) UpdateMemoryLayer(ctx context.Context, agentID string, variationID string, id string, params *AgentVariationUpdateMemoryLayerParams, opts ...RequestOption) (*VariationMemoryLayerAssignment, error) {
	if params == nil {
		params = &AgentVariationUpdateMemoryLayerParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segVariationID, err := pathSegment("variationId", variationID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/variations/%s/memory_layer_assignments/%s", segWorkspaceID, segAgentID, segVariationID, segID)
	body := map[string]any{}
	if params.Position != nil {
		body["position"] = params.Position
	}
	var out VariationMemoryLayerAssignment
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
