// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
)

// AccountResources is implemented by the SDK and easy to mock in tests.
type AccountResources interface {
	// Retrieves the current account for the token accessing the API
	Retrieve(ctx context.Context, opts ...RequestOption) (*Account, error)
	// Rotates the challenge token for the account
	RotateChallengeToken(ctx context.Context, opts ...RequestOption) (*RotateChallengeTokenResponse, error)
	// Rotates the webhook signing key for the account
	RotateWebhookSigningKey(ctx context.Context, opts ...RequestOption) (*RotateWebhookEventsHMACSecretResponse, error)
}

type accountsService struct{ core *core }

var _ AccountResources = (*accountsService)(nil)

func (s *accountsService) Retrieve(ctx context.Context, opts ...RequestOption) (*Account, error) {
	path := "/v1/account"
	var out Account
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *accountsService) RotateChallengeToken(ctx context.Context, opts ...RequestOption) (*RotateChallengeTokenResponse, error) {
	path := "/v1/account:rotateChallengeToken"
	var out RotateChallengeTokenResponse
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *accountsService) RotateWebhookSigningKey(ctx context.Context, opts ...RequestOption) (*RotateWebhookEventsHMACSecretResponse, error) {
	path := "/v1/account:rotateWebhookSigningKey"
	var out RotateWebhookEventsHMACSecretResponse
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
