// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type AgentPoolsSuite struct {
	suite.Suite
}

func TestAgentPoolsSuite(t *testing.T) {
	suite.Run(t, new(AgentPoolsSuite))
}

func (s *AgentPoolsSuite) TestList() {
	g := loadGolden(s.T(), "AgentPoolService_ListAgentPools")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.AgentPools().List(ctx, (&cadenya.AgentPoolListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		State(cadenya.AgentPoolServiceListAgentPoolsState("AGENT_POOL_STATE_ACTIVE")).
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AgentPools().List(ctx, (&cadenya.AgentPoolListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			State(cadenya.AgentPoolServiceListAgentPoolsState("AGENT_POOL_STATE_ACTIVE")).
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentPoolsSuite) TestCreate() {
	g := loadGolden(s.T(), "AgentPoolService_CreateAgentPool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AgentPools().Create(ctx, (&cadenya.AgentPoolCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AgentPoolSpec{Description: "sample", Assignments: []cadenya.AgentPoolAssignment{cadenya.AgentPoolAssignment{AgentID: "sample"}}}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AgentPools().Create(ctx, (&cadenya.AgentPoolCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AgentPoolSpec{Description: "sample", Assignments: []cadenya.AgentPoolAssignment{cadenya.AgentPoolAssignment{AgentID: "sample"}}}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentPoolsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "AgentPoolService_GetAgentPool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AgentPools().Retrieve(ctx, "sample", (&cadenya.AgentPoolRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AgentPools().Retrieve(ctx, "sample", (&cadenya.AgentPoolRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentPoolsSuite) TestDelete() {
	g := loadGolden(s.T(), "AgentPoolService_DeleteAgentPool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.AgentPools().Delete(ctx, "sample", (&cadenya.AgentPoolDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.AgentPools().Delete(ctx, "sample", (&cadenya.AgentPoolDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentPoolsSuite) TestUpdate() {
	g := loadGolden(s.T(), "AgentPoolService_UpdateAgentPool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AgentPools().Update(ctx, "sample", (&cadenya.AgentPoolUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AgentPoolUpdateSpec{}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AgentPools().Update(ctx, "sample", (&cadenya.AgentPoolUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AgentPoolUpdateSpec{}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentPoolsSuite) TestActivate() {
	g := loadGolden(s.T(), "AgentPoolService_ActivateAgentPool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AgentPools().Activate(ctx, "sample", (&cadenya.AgentPoolActivateBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools/sample:activate", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AgentPools().Activate(ctx, "sample", (&cadenya.AgentPoolActivateBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentPoolsSuite) TestArchive() {
	g := loadGolden(s.T(), "AgentPoolService_ArchiveAgentPool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AgentPools().Archive(ctx, "sample", (&cadenya.AgentPoolArchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools/sample:archive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AgentPools().Archive(ctx, "sample", (&cadenya.AgentPoolArchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentPoolsSuite) TestDeactivate() {
	g := loadGolden(s.T(), "AgentPoolService_DeactivateAgentPool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AgentPools().Deactivate(ctx, "sample", (&cadenya.AgentPoolDeactivateBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools/sample:deactivate", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AgentPools().Deactivate(ctx, "sample", (&cadenya.AgentPoolDeactivateBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentPoolsSuite) TestUnarchive() {
	g := loadGolden(s.T(), "AgentPoolService_UnarchiveAgentPool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.AgentPools().Unarchive(ctx, "sample", (&cadenya.AgentPoolUnarchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agent_pools/sample:unarchive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.AgentPools().Unarchive(ctx, "sample", (&cadenya.AgentPoolUnarchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
