// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type WorkspaceSecretListParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	Prefix      *string `json:"prefix,omitempty"`
	Query       *string `json:"query,omitempty"`
	Labels      *string `json:"labels,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
}

// WorkspaceSecretListBuilder builds a WorkspaceSecretListParams fluently.
type WorkspaceSecretListBuilder struct {
	params WorkspaceSecretListParams
}

func (b *WorkspaceSecretListBuilder) WorkspaceID(v string) *WorkspaceSecretListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *WorkspaceSecretListBuilder) Limit(v int32) *WorkspaceSecretListBuilder {
	b.params.Limit = &v
	return b
}

func (b *WorkspaceSecretListBuilder) Cursor(v string) *WorkspaceSecretListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *WorkspaceSecretListBuilder) Prefix(v string) *WorkspaceSecretListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *WorkspaceSecretListBuilder) Query(v string) *WorkspaceSecretListBuilder {
	b.params.Query = &v
	return b
}

func (b *WorkspaceSecretListBuilder) Labels(v string) *WorkspaceSecretListBuilder {
	b.params.Labels = &v
	return b
}

func (b *WorkspaceSecretListBuilder) SortOrder(v string) *WorkspaceSecretListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *WorkspaceSecretListBuilder) IncludeInfo(v bool) *WorkspaceSecretListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WorkspaceSecretListBuilder) ToParams() *WorkspaceSecretListParams {
	p := b.params
	return &p
}

type WorkspaceSecretCreateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *CreateResourceMetadata `json:"metadata"`
	Spec        *WorkspaceSecretSpec    `json:"spec"`
}

// WorkspaceSecretCreateBuilder builds a WorkspaceSecretCreateParams fluently.
type WorkspaceSecretCreateBuilder struct {
	params WorkspaceSecretCreateParams
}

func (b *WorkspaceSecretCreateBuilder) WorkspaceID(v string) *WorkspaceSecretCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *WorkspaceSecretCreateBuilder) Metadata(v *CreateResourceMetadata) *WorkspaceSecretCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *WorkspaceSecretCreateBuilder) Spec(v *WorkspaceSecretSpec) *WorkspaceSecretCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WorkspaceSecretCreateBuilder) ToParams() *WorkspaceSecretCreateParams {
	p := b.params
	return &p
}

type WorkspaceSecretRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// WorkspaceSecretRetrieveBuilder builds a WorkspaceSecretRetrieveParams fluently.
type WorkspaceSecretRetrieveBuilder struct {
	params WorkspaceSecretRetrieveParams
}

func (b *WorkspaceSecretRetrieveBuilder) WorkspaceID(v string) *WorkspaceSecretRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WorkspaceSecretRetrieveBuilder) ToParams() *WorkspaceSecretRetrieveParams {
	p := b.params
	return &p
}

type WorkspaceSecretDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// WorkspaceSecretDeleteBuilder builds a WorkspaceSecretDeleteParams fluently.
type WorkspaceSecretDeleteBuilder struct {
	params WorkspaceSecretDeleteParams
}

func (b *WorkspaceSecretDeleteBuilder) WorkspaceID(v string) *WorkspaceSecretDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WorkspaceSecretDeleteBuilder) ToParams() *WorkspaceSecretDeleteParams {
	p := b.params
	return &p
}

type WorkspaceSecretUpdateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *UpdateResourceMetadata `json:"metadata,omitempty"`
	Spec        *WorkspaceSecretSpec    `json:"spec,omitempty"`
	UpdateMask  *string                 `json:"updateMask,omitempty"`
}

// WorkspaceSecretUpdateBuilder builds a WorkspaceSecretUpdateParams fluently.
type WorkspaceSecretUpdateBuilder struct {
	params WorkspaceSecretUpdateParams
}

func (b *WorkspaceSecretUpdateBuilder) WorkspaceID(v string) *WorkspaceSecretUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *WorkspaceSecretUpdateBuilder) Metadata(v *UpdateResourceMetadata) *WorkspaceSecretUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *WorkspaceSecretUpdateBuilder) Spec(v *WorkspaceSecretSpec) *WorkspaceSecretUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *WorkspaceSecretUpdateBuilder) UpdateMask(v string) *WorkspaceSecretUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WorkspaceSecretUpdateBuilder) ToParams() *WorkspaceSecretUpdateParams {
	p := b.params
	return &p
}

// WorkspaceSecretResources is implemented by the SDK and easy to mock in tests.
type WorkspaceSecretResources interface {
	// List workspace secrets
	List(ctx context.Context, params *WorkspaceSecretListParams, opts ...RequestOption) (*Page[WorkspaceSecret], error)
	// Create a new workspace secret
	Create(ctx context.Context, params *WorkspaceSecretCreateParams, opts ...RequestOption) (*WorkspaceSecret, error)
	// Get a workspace secret by ID
	Retrieve(ctx context.Context, id string, params *WorkspaceSecretRetrieveParams, opts ...RequestOption) (*WorkspaceSecret, error)
	// Delete a workspace secret
	Delete(ctx context.Context, id string, params *WorkspaceSecretDeleteParams, opts ...RequestOption) error
	// Update a workspace secret
	Update(ctx context.Context, id string, params *WorkspaceSecretUpdateParams, opts ...RequestOption) (*WorkspaceSecret, error)
}

type workspaceSecretsService struct{ core *core }

var _ WorkspaceSecretResources = (*workspaceSecretsService)(nil)

func (s *workspaceSecretsService) List(ctx context.Context, params *WorkspaceSecretListParams, opts ...RequestOption) (*Page[WorkspaceSecret], error) {
	if params == nil {
		params = &WorkspaceSecretListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/workspace_secrets", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListWorkspaceSecretsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[WorkspaceSecret], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *workspaceSecretsService) Create(ctx context.Context, params *WorkspaceSecretCreateParams, opts ...RequestOption) (*WorkspaceSecret, error) {
	if params == nil {
		params = &WorkspaceSecretCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/workspace_secrets", segWorkspaceID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out WorkspaceSecret
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *workspaceSecretsService) Retrieve(ctx context.Context, id string, params *WorkspaceSecretRetrieveParams, opts ...RequestOption) (*WorkspaceSecret, error) {
	if params == nil {
		params = &WorkspaceSecretRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/workspace_secrets/%s", segWorkspaceID, segID)
	var out WorkspaceSecret
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *workspaceSecretsService) Delete(ctx context.Context, id string, params *WorkspaceSecretDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &WorkspaceSecretDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/workspace_secrets/%s", segWorkspaceID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *workspaceSecretsService) Update(ctx context.Context, id string, params *WorkspaceSecretUpdateParams, opts ...RequestOption) (*WorkspaceSecret, error) {
	if params == nil {
		params = &WorkspaceSecretUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/workspace_secrets/%s", segWorkspaceID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out WorkspaceSecret
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
