// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"
)

type ProfilesSuite struct {
	suite.Suite
}

func TestProfilesSuite(t *testing.T) {
	suite.Run(t, new(ProfilesSuite))
}

func (s *ProfilesSuite) TestWhoami() {
	g := loadGolden(s.T(), "ProfilesService_Whoami")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Profiles().Whoami(ctx)
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}
