// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type WorkspacesSuite struct {
	suite.Suite
}

func TestWorkspacesSuite(t *testing.T) {
	suite.Run(t, new(WorkspacesSuite))
}

func (s *WorkspacesSuite) TestList() {
	g := loadGolden(s.T(), "WorkspaceService_ListWorkspaces")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.Workspaces().List(ctx, (&cadenya.WorkspaceListBuilder{}).
		Limit(1).
		Cursor("sample").
		SortOrder("sample").
		IncludeInfo(true).
		Labels("sample").
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}
