// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type WidgetSessionListParams struct {
	WorkspaceID *string                                      `json:"workspaceId,omitempty"`
	Limit       *int32                                       `json:"limit,omitempty"`
	Cursor      *string                                      `json:"cursor,omitempty"`
	WidgetID    *string                                      `json:"widgetId,omitempty"`
	TenantID    *string                                      `json:"tenantId,omitempty"`
	SubjectID   *string                                      `json:"subjectId,omitempty"`
	State       *WidgetSessionServiceListWidgetSessionsState `json:"state,omitempty"`
	Labels      *string                                      `json:"labels,omitempty"`
	SortOrder   *string                                      `json:"sortOrder,omitempty"`
	IncludeInfo *bool                                        `json:"includeInfo,omitempty"`
}

// WidgetSessionListBuilder builds a WidgetSessionListParams fluently.
type WidgetSessionListBuilder struct {
	params WidgetSessionListParams
}

func (b *WidgetSessionListBuilder) WorkspaceID(v string) *WidgetSessionListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *WidgetSessionListBuilder) Limit(v int32) *WidgetSessionListBuilder {
	b.params.Limit = &v
	return b
}

func (b *WidgetSessionListBuilder) Cursor(v string) *WidgetSessionListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *WidgetSessionListBuilder) WidgetID(v string) *WidgetSessionListBuilder {
	b.params.WidgetID = &v
	return b
}

func (b *WidgetSessionListBuilder) TenantID(v string) *WidgetSessionListBuilder {
	b.params.TenantID = &v
	return b
}

func (b *WidgetSessionListBuilder) SubjectID(v string) *WidgetSessionListBuilder {
	b.params.SubjectID = &v
	return b
}

func (b *WidgetSessionListBuilder) State(v WidgetSessionServiceListWidgetSessionsState) *WidgetSessionListBuilder {
	b.params.State = &v
	return b
}

func (b *WidgetSessionListBuilder) Labels(v string) *WidgetSessionListBuilder {
	b.params.Labels = &v
	return b
}

func (b *WidgetSessionListBuilder) SortOrder(v string) *WidgetSessionListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *WidgetSessionListBuilder) IncludeInfo(v bool) *WidgetSessionListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WidgetSessionListBuilder) ToParams() *WidgetSessionListParams {
	p := b.params
	return &p
}

type WidgetSessionCreateParams struct {
	WorkspaceID *string                             `json:"workspaceId,omitempty"`
	Metadata    *CreateOperationMetadata            `json:"metadata,omitempty"`
	Spec        *WidgetSessionSpecParam             `json:"spec"`
	Secrets     []CreateWidgetSessionRequest_Secret `json:"secrets,omitempty"`
}

// WidgetSessionCreateBuilder builds a WidgetSessionCreateParams fluently.
type WidgetSessionCreateBuilder struct {
	params WidgetSessionCreateParams
}

func (b *WidgetSessionCreateBuilder) WorkspaceID(v string) *WidgetSessionCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *WidgetSessionCreateBuilder) Metadata(v *CreateOperationMetadata) *WidgetSessionCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *WidgetSessionCreateBuilder) Spec(v *WidgetSessionSpecParam) *WidgetSessionCreateBuilder {
	b.params.Spec = v
	return b
}

func (b *WidgetSessionCreateBuilder) Secrets(v ...CreateWidgetSessionRequest_Secret) *WidgetSessionCreateBuilder {
	b.params.Secrets = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WidgetSessionCreateBuilder) ToParams() *WidgetSessionCreateParams {
	p := b.params
	return &p
}

type WidgetSessionDeleteTenantParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	TenantID    *string `json:"tenantId,omitempty"`
}

// WidgetSessionDeleteTenantBuilder builds a WidgetSessionDeleteTenantParams fluently.
type WidgetSessionDeleteTenantBuilder struct {
	params WidgetSessionDeleteTenantParams
}

func (b *WidgetSessionDeleteTenantBuilder) WorkspaceID(v string) *WidgetSessionDeleteTenantBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *WidgetSessionDeleteTenantBuilder) TenantID(v string) *WidgetSessionDeleteTenantBuilder {
	b.params.TenantID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WidgetSessionDeleteTenantBuilder) ToParams() *WidgetSessionDeleteTenantParams {
	p := b.params
	return &p
}

type WidgetSessionRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// WidgetSessionRetrieveBuilder builds a WidgetSessionRetrieveParams fluently.
type WidgetSessionRetrieveBuilder struct {
	params WidgetSessionRetrieveParams
}

func (b *WidgetSessionRetrieveBuilder) WorkspaceID(v string) *WidgetSessionRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WidgetSessionRetrieveBuilder) ToParams() *WidgetSessionRetrieveParams {
	p := b.params
	return &p
}

type WidgetSessionDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// WidgetSessionDeleteBuilder builds a WidgetSessionDeleteParams fluently.
type WidgetSessionDeleteBuilder struct {
	params WidgetSessionDeleteParams
}

func (b *WidgetSessionDeleteBuilder) WorkspaceID(v string) *WidgetSessionDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WidgetSessionDeleteBuilder) ToParams() *WidgetSessionDeleteParams {
	p := b.params
	return &p
}

type WidgetSessionRevokeParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// WidgetSessionRevokeBuilder builds a WidgetSessionRevokeParams fluently.
type WidgetSessionRevokeBuilder struct {
	params WidgetSessionRevokeParams
}

func (b *WidgetSessionRevokeBuilder) WorkspaceID(v string) *WidgetSessionRevokeBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *WidgetSessionRevokeBuilder) ToParams() *WidgetSessionRevokeParams {
	p := b.params
	return &p
}

// WidgetSessionResources is implemented by the SDK and easy to mock in tests.
type WidgetSessionResources interface {
	// List widget sessions
	List(ctx context.Context, params *WidgetSessionListParams, opts ...RequestOption) (*Page[WidgetSession], error)
	// Create a widget session
	Create(ctx context.Context, params *WidgetSessionCreateParams, opts ...RequestOption) (*WidgetSession, error)
	// Delete all of a tenant's widget sessions
	DeleteTenant(ctx context.Context, params *WidgetSessionDeleteTenantParams, opts ...RequestOption) (*DeleteTenantWidgetSessionsResponse, error)
	// Get a widget session by ID
	Retrieve(ctx context.Context, id string, params *WidgetSessionRetrieveParams, opts ...RequestOption) (*WidgetSession, error)
	// Delete a widget session
	Delete(ctx context.Context, id string, params *WidgetSessionDeleteParams, opts ...RequestOption) error
	// Revoke a widget session
	Revoke(ctx context.Context, id string, params *WidgetSessionRevokeParams, opts ...RequestOption) (*WidgetSession, error)
}

type widgetSessionsService struct{ core *core }

var _ WidgetSessionResources = (*widgetSessionsService)(nil)

func (s *widgetSessionsService) List(ctx context.Context, params *WidgetSessionListParams, opts ...RequestOption) (*Page[WidgetSession], error) {
	if params == nil {
		params = &WidgetSessionListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/widget_sessions", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.WidgetID != nil {
		q.Set("widgetId", (*params.WidgetID))
	}
	if params.TenantID != nil {
		q.Set("tenantId", (*params.TenantID))
	}
	if params.SubjectID != nil {
		q.Set("subjectId", (*params.SubjectID))
	}
	if params.State != nil {
		q.Set("state", string(*params.State))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListWidgetSessionsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[WidgetSession], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *widgetSessionsService) Create(ctx context.Context, params *WidgetSessionCreateParams, opts ...RequestOption) (*WidgetSession, error) {
	if params == nil {
		params = &WidgetSessionCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/widget_sessions", segWorkspaceID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.Secrets != nil {
		body["secrets"] = params.Secrets
	}
	var out WidgetSession
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *widgetSessionsService) DeleteTenant(ctx context.Context, params *WidgetSessionDeleteTenantParams, opts ...RequestOption) (*DeleteTenantWidgetSessionsResponse, error) {
	if params == nil {
		params = &WidgetSessionDeleteTenantParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/widget_sessions", segWorkspaceID)
	q := url.Values{}
	if params.TenantID != nil {
		q.Set("tenantId", (*params.TenantID))
	}
	var out DeleteTenantWidgetSessionsResponse
	if err := s.core.do(ctx, "DELETE", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *widgetSessionsService) Retrieve(ctx context.Context, id string, params *WidgetSessionRetrieveParams, opts ...RequestOption) (*WidgetSession, error) {
	if params == nil {
		params = &WidgetSessionRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/widget_sessions/%s", segWorkspaceID, segID)
	var out WidgetSession
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *widgetSessionsService) Delete(ctx context.Context, id string, params *WidgetSessionDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &WidgetSessionDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/widget_sessions/%s", segWorkspaceID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *widgetSessionsService) Revoke(ctx context.Context, id string, params *WidgetSessionRevokeParams, opts ...RequestOption) (*WidgetSession, error) {
	if params == nil {
		params = &WidgetSessionRevokeParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/widget_sessions/%s:revoke", segWorkspaceID, segID)
	var out WidgetSession
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
