// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type AgentVariationsSuite struct {
	suite.Suite
}

func TestAgentVariationsSuite(t *testing.T) {
	suite.Run(t, new(AgentVariationsSuite))
}

func (s *AgentVariationsSuite) TestList() {
	g := loadGolden(s.T(), "AgentVariationService_ListAgentVariations")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.Agents().Variations().List(ctx, "sample", (&cadenya.AgentVariationListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		SortOrder("sample").
		IncludeInfo(true).
		Labels("sample").
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Variations().List(ctx, "sample", (&cadenya.AgentVariationListBuilder{}).
			Limit(1).
			Cursor("sample").
			SortOrder("sample").
			IncludeInfo(true).
			Labels("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestCreate() {
	g := loadGolden(s.T(), "AgentVariationService_CreateAgentVariation")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Variations().Create(ctx, "sample", (&cadenya.AgentVariationCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AgentVariationSpec{}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Variations().Create(ctx, "sample", (&cadenya.AgentVariationCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AgentVariationSpec{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "AgentVariationService_GetAgentVariation")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Variations().Retrieve(ctx, "sample", "sample", (&cadenya.AgentVariationRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Variations().Retrieve(ctx, "sample", "sample", (&cadenya.AgentVariationRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestDelete() {
	g := loadGolden(s.T(), "AgentVariationService_DeleteAgentVariation")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.Agents().Variations().Delete(ctx, "sample", "sample", (&cadenya.AgentVariationDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.Agents().Variations().Delete(ctx, "sample", "sample", (&cadenya.AgentVariationDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestUpdate() {
	g := loadGolden(s.T(), "AgentVariationService_UpdateAgentVariation")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Variations().Update(ctx, "sample", "sample", (&cadenya.AgentVariationUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AgentVariationSpec{}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Variations().Update(ctx, "sample", "sample", (&cadenya.AgentVariationUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AgentVariationSpec{}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestAddAssignment() {
	g := loadGolden(s.T(), "AgentVariationService_AddAgentVariationAssignment")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Variations().AddAssignment(ctx, "sample", "sample", (&cadenya.AgentVariationAddAssignmentBuilder{}).
		WorkspaceID("sample").
		Body(&cadenya.AddAgentVariationAssignmentRequestParam{ToolID: &cadenya.AddAgentVariationAssignmentRequest_ToolIDParam{Type: "toolId", ToolID: "sample"}}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations/sample/assignments", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Variations().AddAssignment(ctx, "sample", "sample", (&cadenya.AgentVariationAddAssignmentBuilder{}).
			Body(&cadenya.AddAgentVariationAssignmentRequestParam{ToolID: &cadenya.AddAgentVariationAssignmentRequest_ToolIDParam{Type: "toolId", ToolID: "sample"}}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestRemoveAssignment() {
	g := loadGolden(s.T(), "AgentVariationService_RemoveAgentVariationAssignment")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.Agents().Variations().RemoveAssignment(ctx, "sample", "sample", "sample", (&cadenya.AgentVariationRemoveAssignmentBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations/sample/assignments/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.Agents().Variations().RemoveAssignment(ctx, "sample", "sample", "sample", (&cadenya.AgentVariationRemoveAssignmentBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestAddMemoryLayer() {
	g := loadGolden(s.T(), "AgentVariationService_AddAgentVariationMemoryLayer")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Variations().AddMemoryLayer(ctx, "sample", "sample", (&cadenya.AgentVariationAddMemoryLayerBuilder{}).
		WorkspaceID("sample").
		MemoryLayerID("sample").
		Position(1).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations/sample/memory_layer_assignments", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Variations().AddMemoryLayer(ctx, "sample", "sample", (&cadenya.AgentVariationAddMemoryLayerBuilder{}).
			MemoryLayerID("sample").
			Position(1).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestRemoveMemoryLayer() {
	g := loadGolden(s.T(), "AgentVariationService_RemoveAgentVariationMemoryLayer")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.Agents().Variations().RemoveMemoryLayer(ctx, "sample", "sample", "sample", (&cadenya.AgentVariationRemoveMemoryLayerBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations/sample/memory_layer_assignments/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.Agents().Variations().RemoveMemoryLayer(ctx, "sample", "sample", "sample", (&cadenya.AgentVariationRemoveMemoryLayerBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentVariationsSuite) TestUpdateMemoryLayer() {
	g := loadGolden(s.T(), "AgentVariationService_UpdateAgentVariationMemoryLayer")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Variations().UpdateMemoryLayer(ctx, "sample", "sample", "sample", (&cadenya.AgentVariationUpdateMemoryLayerBuilder{}).
		WorkspaceID("sample").
		Position(1).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/variations/sample/memory_layer_assignments/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Variations().UpdateMemoryLayer(ctx, "sample", "sample", "sample", (&cadenya.AgentVariationUpdateMemoryLayerBuilder{}).
			Position(1).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
