// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type ModelListParams struct {
	WorkspaceID     *string                      `json:"workspaceId,omitempty"`
	Limit           *int32                       `json:"limit,omitempty"`
	Cursor          *string                      `json:"cursor,omitempty"`
	Prefix          *string                      `json:"prefix,omitempty"`
	Query           *string                      `json:"query,omitempty"`
	State           *ModelServiceListModelsState `json:"state,omitempty"`
	AIProviderKeyID *string                      `json:"aiProviderKeyId,omitempty"`
	IsAssigned      *bool                        `json:"isAssigned,omitempty"`
	Labels          *string                      `json:"labels,omitempty"`
	SortOrder       *string                      `json:"sortOrder,omitempty"`
	IncludeInfo     *bool                        `json:"includeInfo,omitempty"`
}

// ModelListBuilder builds a ModelListParams fluently.
type ModelListBuilder struct {
	params ModelListParams
}

func (b *ModelListBuilder) WorkspaceID(v string) *ModelListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ModelListBuilder) Limit(v int32) *ModelListBuilder {
	b.params.Limit = &v
	return b
}

func (b *ModelListBuilder) Cursor(v string) *ModelListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ModelListBuilder) Prefix(v string) *ModelListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *ModelListBuilder) Query(v string) *ModelListBuilder {
	b.params.Query = &v
	return b
}

func (b *ModelListBuilder) State(v ModelServiceListModelsState) *ModelListBuilder {
	b.params.State = &v
	return b
}

func (b *ModelListBuilder) AIProviderKeyID(v string) *ModelListBuilder {
	b.params.AIProviderKeyID = &v
	return b
}

func (b *ModelListBuilder) IsAssigned(v bool) *ModelListBuilder {
	b.params.IsAssigned = &v
	return b
}

func (b *ModelListBuilder) Labels(v string) *ModelListBuilder {
	b.params.Labels = &v
	return b
}

func (b *ModelListBuilder) SortOrder(v string) *ModelListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *ModelListBuilder) IncludeInfo(v bool) *ModelListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ModelListBuilder) ToParams() *ModelListParams {
	p := b.params
	return &p
}

type ModelRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ModelRetrieveBuilder builds a ModelRetrieveParams fluently.
type ModelRetrieveBuilder struct {
	params ModelRetrieveParams
}

func (b *ModelRetrieveBuilder) WorkspaceID(v string) *ModelRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ModelRetrieveBuilder) ToParams() *ModelRetrieveParams {
	p := b.params
	return &p
}

type ModelDisableParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ModelDisableBuilder builds a ModelDisableParams fluently.
type ModelDisableBuilder struct {
	params ModelDisableParams
}

func (b *ModelDisableBuilder) WorkspaceID(v string) *ModelDisableBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ModelDisableBuilder) ToParams() *ModelDisableParams {
	p := b.params
	return &p
}

type ModelEnableParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ModelEnableBuilder builds a ModelEnableParams fluently.
type ModelEnableBuilder struct {
	params ModelEnableParams
}

func (b *ModelEnableBuilder) WorkspaceID(v string) *ModelEnableBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ModelEnableBuilder) ToParams() *ModelEnableParams {
	p := b.params
	return &p
}

type ModelSwapOnVariationsParams struct {
	WorkspaceID *string                                  `json:"workspaceId,omitempty"`
	ModelSwaps  []SwapModelOnVariationsRequest_ModelSwap `json:"modelSwaps,omitempty"`
}

// ModelSwapOnVariationsBuilder builds a ModelSwapOnVariationsParams fluently.
type ModelSwapOnVariationsBuilder struct {
	params ModelSwapOnVariationsParams
}

func (b *ModelSwapOnVariationsBuilder) WorkspaceID(v string) *ModelSwapOnVariationsBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ModelSwapOnVariationsBuilder) ModelSwaps(v ...SwapModelOnVariationsRequest_ModelSwap) *ModelSwapOnVariationsBuilder {
	b.params.ModelSwaps = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ModelSwapOnVariationsBuilder) ToParams() *ModelSwapOnVariationsParams {
	p := b.params
	return &p
}

// ModelResources is implemented by the SDK and easy to mock in tests.
type ModelResources interface {
	// List models
	List(ctx context.Context, params *ModelListParams, opts ...RequestOption) (*Page[Model], error)
	// Get a model by ID
	Retrieve(ctx context.Context, id string, params *ModelRetrieveParams, opts ...RequestOption) (*Model, error)
	// Disable a model
	Disable(ctx context.Context, id string, params *ModelDisableParams, opts ...RequestOption) (*Model, error)
	// Enable a model
	Enable(ctx context.Context, id string, params *ModelEnableParams, opts ...RequestOption) (*Model, error)
	// Swap models on agent variations
	SwapOnVariations(ctx context.Context, params *ModelSwapOnVariationsParams, opts ...RequestOption) error
}

type modelsService struct{ core *core }

var _ ModelResources = (*modelsService)(nil)

func (s *modelsService) List(ctx context.Context, params *ModelListParams, opts ...RequestOption) (*Page[Model], error) {
	if params == nil {
		params = &ModelListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/models", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.State != nil {
		q.Set("state", string(*params.State))
	}
	if params.AIProviderKeyID != nil {
		q.Set("aiProviderKeyId", (*params.AIProviderKeyID))
	}
	if params.IsAssigned != nil {
		q.Set("isAssigned", strconv.FormatBool(*params.IsAssigned))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListModelsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[Model], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *modelsService) Retrieve(ctx context.Context, id string, params *ModelRetrieveParams, opts ...RequestOption) (*Model, error) {
	if params == nil {
		params = &ModelRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/models/%s", segWorkspaceID, segID)
	var out Model
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *modelsService) Disable(ctx context.Context, id string, params *ModelDisableParams, opts ...RequestOption) (*Model, error) {
	if params == nil {
		params = &ModelDisableParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/models/%s:disable", segWorkspaceID, segID)
	var out Model
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *modelsService) Enable(ctx context.Context, id string, params *ModelEnableParams, opts ...RequestOption) (*Model, error) {
	if params == nil {
		params = &ModelEnableParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/models/%s:enable", segWorkspaceID, segID)
	var out Model
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *modelsService) SwapOnVariations(ctx context.Context, params *ModelSwapOnVariationsParams, opts ...RequestOption) error {
	if params == nil {
		params = &ModelSwapOnVariationsParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/models:swapModelOnVariations", segWorkspaceID)
	body := map[string]any{}
	if params.ModelSwaps != nil {
		body["modelSwaps"] = params.ModelSwaps
	}
	return s.core.do(ctx, "POST", path, nil, body, nil, opts...)
}
