// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
	"time"
)

type AgentListParams struct {
	WorkspaceID            *string                                       `json:"workspaceId,omitempty"`
	Limit                  *int32                                        `json:"limit,omitempty"`
	Cursor                 *string                                       `json:"cursor,omitempty"`
	Prefix                 *string                                       `json:"prefix,omitempty"`
	Query                  *string                                       `json:"query,omitempty"`
	State                  *AgentServiceListAgentsState                  `json:"state,omitempty"`
	VariationSelectionMode *AgentServiceListAgentsVariationSelectionMode `json:"variationSelectionMode,omitempty"`
	Labels                 *string                                       `json:"labels,omitempty"`
	SortOrder              *string                                       `json:"sortOrder,omitempty"`
	IncludeInfo            *bool                                         `json:"includeInfo,omitempty"`
}

// AgentListBuilder builds a AgentListParams fluently.
type AgentListBuilder struct {
	params AgentListParams
}

func (b *AgentListBuilder) WorkspaceID(v string) *AgentListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentListBuilder) Limit(v int32) *AgentListBuilder {
	b.params.Limit = &v
	return b
}

func (b *AgentListBuilder) Cursor(v string) *AgentListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *AgentListBuilder) Prefix(v string) *AgentListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *AgentListBuilder) Query(v string) *AgentListBuilder {
	b.params.Query = &v
	return b
}

func (b *AgentListBuilder) State(v AgentServiceListAgentsState) *AgentListBuilder {
	b.params.State = &v
	return b
}

func (b *AgentListBuilder) VariationSelectionMode(v AgentServiceListAgentsVariationSelectionMode) *AgentListBuilder {
	b.params.VariationSelectionMode = &v
	return b
}

func (b *AgentListBuilder) Labels(v string) *AgentListBuilder {
	b.params.Labels = &v
	return b
}

func (b *AgentListBuilder) SortOrder(v string) *AgentListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *AgentListBuilder) IncludeInfo(v bool) *AgentListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentListBuilder) ToParams() *AgentListParams {
	p := b.params
	return &p
}

type AgentCreateParams struct {
	WorkspaceID      *string                           `json:"workspaceId,omitempty"`
	Metadata         *CreateResourceMetadata           `json:"metadata"`
	Spec             *AgentSpec                        `json:"spec"`
	DefaultVariation *CreateAgentVariationRequestParam `json:"defaultVariation,omitempty"`
}

// AgentCreateBuilder builds a AgentCreateParams fluently.
type AgentCreateBuilder struct {
	params AgentCreateParams
}

func (b *AgentCreateBuilder) WorkspaceID(v string) *AgentCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentCreateBuilder) Metadata(v *CreateResourceMetadata) *AgentCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AgentCreateBuilder) Spec(v *AgentSpec) *AgentCreateBuilder {
	b.params.Spec = v
	return b
}

func (b *AgentCreateBuilder) DefaultVariation(v *CreateAgentVariationRequestParam) *AgentCreateBuilder {
	b.params.DefaultVariation = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentCreateBuilder) ToParams() *AgentCreateParams {
	p := b.params
	return &p
}

type AgentListFeedbackParams struct {
	WorkspaceID      *string                                 `json:"workspaceId,omitempty"`
	Limit            *int32                                  `json:"limit,omitempty"`
	Cursor           *string                                 `json:"cursor,omitempty"`
	Query            *string                                 `json:"query,omitempty"`
	Sentiment        *AgentServiceListAgentFeedbackSentiment `json:"sentiment,omitempty"`
	AgentVariationID *string                                 `json:"agentVariationId,omitempty"`
	CreatedAfter     *time.Time                              `json:"createdAfter,omitempty"`
	CreatedBefore    *time.Time                              `json:"createdBefore,omitempty"`
	Labels           *string                                 `json:"labels,omitempty"`
	IncludeInfo      *bool                                   `json:"includeInfo,omitempty"`
}

// AgentListFeedbackBuilder builds a AgentListFeedbackParams fluently.
type AgentListFeedbackBuilder struct {
	params AgentListFeedbackParams
}

func (b *AgentListFeedbackBuilder) WorkspaceID(v string) *AgentListFeedbackBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentListFeedbackBuilder) Limit(v int32) *AgentListFeedbackBuilder {
	b.params.Limit = &v
	return b
}

func (b *AgentListFeedbackBuilder) Cursor(v string) *AgentListFeedbackBuilder {
	b.params.Cursor = &v
	return b
}

func (b *AgentListFeedbackBuilder) Query(v string) *AgentListFeedbackBuilder {
	b.params.Query = &v
	return b
}

func (b *AgentListFeedbackBuilder) Sentiment(v AgentServiceListAgentFeedbackSentiment) *AgentListFeedbackBuilder {
	b.params.Sentiment = &v
	return b
}

func (b *AgentListFeedbackBuilder) AgentVariationID(v string) *AgentListFeedbackBuilder {
	b.params.AgentVariationID = &v
	return b
}

func (b *AgentListFeedbackBuilder) CreatedAfter(v time.Time) *AgentListFeedbackBuilder {
	b.params.CreatedAfter = &v
	return b
}

func (b *AgentListFeedbackBuilder) CreatedBefore(v time.Time) *AgentListFeedbackBuilder {
	b.params.CreatedBefore = &v
	return b
}

func (b *AgentListFeedbackBuilder) Labels(v string) *AgentListFeedbackBuilder {
	b.params.Labels = &v
	return b
}

func (b *AgentListFeedbackBuilder) IncludeInfo(v bool) *AgentListFeedbackBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentListFeedbackBuilder) ToParams() *AgentListFeedbackParams {
	p := b.params
	return &p
}

type AgentListWebhookDeliveriesParams struct {
	WorkspaceID *string                                          `json:"workspaceId,omitempty"`
	Cursor      *string                                          `json:"cursor,omitempty"`
	Limit       *int32                                           `json:"limit,omitempty"`
	ObjectiveID *string                                          `json:"objectiveId,omitempty"`
	EventType   *AgentServiceListAgentWebhookDeliveriesEventType `json:"eventType,omitempty"`
	Labels      *string                                          `json:"labels,omitempty"`
}

// AgentListWebhookDeliveriesBuilder builds a AgentListWebhookDeliveriesParams fluently.
type AgentListWebhookDeliveriesBuilder struct {
	params AgentListWebhookDeliveriesParams
}

func (b *AgentListWebhookDeliveriesBuilder) WorkspaceID(v string) *AgentListWebhookDeliveriesBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentListWebhookDeliveriesBuilder) Cursor(v string) *AgentListWebhookDeliveriesBuilder {
	b.params.Cursor = &v
	return b
}

func (b *AgentListWebhookDeliveriesBuilder) Limit(v int32) *AgentListWebhookDeliveriesBuilder {
	b.params.Limit = &v
	return b
}

func (b *AgentListWebhookDeliveriesBuilder) ObjectiveID(v string) *AgentListWebhookDeliveriesBuilder {
	b.params.ObjectiveID = &v
	return b
}

func (b *AgentListWebhookDeliveriesBuilder) EventType(v AgentServiceListAgentWebhookDeliveriesEventType) *AgentListWebhookDeliveriesBuilder {
	b.params.EventType = &v
	return b
}

func (b *AgentListWebhookDeliveriesBuilder) Labels(v string) *AgentListWebhookDeliveriesBuilder {
	b.params.Labels = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentListWebhookDeliveriesBuilder) ToParams() *AgentListWebhookDeliveriesParams {
	p := b.params
	return &p
}

type AgentRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentRetrieveBuilder builds a AgentRetrieveParams fluently.
type AgentRetrieveBuilder struct {
	params AgentRetrieveParams
}

func (b *AgentRetrieveBuilder) WorkspaceID(v string) *AgentRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentRetrieveBuilder) ToParams() *AgentRetrieveParams {
	p := b.params
	return &p
}

type AgentDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentDeleteBuilder builds a AgentDeleteParams fluently.
type AgentDeleteBuilder struct {
	params AgentDeleteParams
}

func (b *AgentDeleteBuilder) WorkspaceID(v string) *AgentDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentDeleteBuilder) ToParams() *AgentDeleteParams {
	p := b.params
	return &p
}

type AgentUpdateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *UpdateResourceMetadata `json:"metadata,omitempty"`
	Spec        *AgentSpec              `json:"spec,omitempty"`
	UpdateMask  *string                 `json:"updateMask,omitempty"`
}

// AgentUpdateBuilder builds a AgentUpdateParams fluently.
type AgentUpdateBuilder struct {
	params AgentUpdateParams
}

func (b *AgentUpdateBuilder) WorkspaceID(v string) *AgentUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentUpdateBuilder) Metadata(v *UpdateResourceMetadata) *AgentUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AgentUpdateBuilder) Spec(v *AgentSpec) *AgentUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *AgentUpdateBuilder) UpdateMask(v string) *AgentUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentUpdateBuilder) ToParams() *AgentUpdateParams {
	p := b.params
	return &p
}

type AgentArchiveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentArchiveBuilder builds a AgentArchiveParams fluently.
type AgentArchiveBuilder struct {
	params AgentArchiveParams
}

func (b *AgentArchiveBuilder) WorkspaceID(v string) *AgentArchiveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentArchiveBuilder) ToParams() *AgentArchiveParams {
	p := b.params
	return &p
}

type AgentPublishParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentPublishBuilder builds a AgentPublishParams fluently.
type AgentPublishBuilder struct {
	params AgentPublishParams
}

func (b *AgentPublishBuilder) WorkspaceID(v string) *AgentPublishBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentPublishBuilder) ToParams() *AgentPublishParams {
	p := b.params
	return &p
}

type AgentUnarchiveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentUnarchiveBuilder builds a AgentUnarchiveParams fluently.
type AgentUnarchiveBuilder struct {
	params AgentUnarchiveParams
}

func (b *AgentUnarchiveBuilder) WorkspaceID(v string) *AgentUnarchiveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentUnarchiveBuilder) ToParams() *AgentUnarchiveParams {
	p := b.params
	return &p
}

type AgentUnpublishParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentUnpublishBuilder builds a AgentUnpublishParams fluently.
type AgentUnpublishBuilder struct {
	params AgentUnpublishParams
}

func (b *AgentUnpublishBuilder) WorkspaceID(v string) *AgentUnpublishBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentUnpublishBuilder) ToParams() *AgentUnpublishParams {
	p := b.params
	return &p
}

// AgentResources is implemented by the SDK and easy to mock in tests.
type AgentResources interface {
	// List agents
	List(ctx context.Context, params *AgentListParams, opts ...RequestOption) (*Page[Agent], error)
	// Create a new agent
	Create(ctx context.Context, params *AgentCreateParams, opts ...RequestOption) (*Agent, error)
	// List feedback for an agent
	ListFeedback(ctx context.Context, agentID string, params *AgentListFeedbackParams, opts ...RequestOption) (*Page[ObjectiveFeedback], error)
	// List webhook deliveries
	ListWebhookDeliveries(ctx context.Context, agentID string, params *AgentListWebhookDeliveriesParams, opts ...RequestOption) (*Page[WebhookDelivery], error)
	// Get an agent by ID
	Retrieve(ctx context.Context, id string, params *AgentRetrieveParams, opts ...RequestOption) (*Agent, error)
	// Delete an agent
	Delete(ctx context.Context, id string, params *AgentDeleteParams, opts ...RequestOption) error
	// Update an agent
	Update(ctx context.Context, id string, params *AgentUpdateParams, opts ...RequestOption) (*Agent, error)
	// Archive an agent
	Archive(ctx context.Context, id string, params *AgentArchiveParams, opts ...RequestOption) (*Agent, error)
	// Publish an agent
	Publish(ctx context.Context, id string, params *AgentPublishParams, opts ...RequestOption) (*Agent, error)
	// Unarchive an agent
	Unarchive(ctx context.Context, id string, params *AgentUnarchiveParams, opts ...RequestOption) (*Agent, error)
	// Unpublish an agent
	Unpublish(ctx context.Context, id string, params *AgentUnpublishParams, opts ...RequestOption) (*Agent, error)
	// Schedules returns the nested schedules resource group.
	Schedules() AgentScheduleResources
	// Variations returns the nested variations resource group.
	Variations() AgentVariationResources
}

type agentsService struct{ core *core }

var _ AgentResources = (*agentsService)(nil)

func (s *agentsService) Schedules() AgentScheduleResources {
	return &agentSchedulesService{core: s.core}
}

func (s *agentsService) Variations() AgentVariationResources {
	return &agentVariationsService{core: s.core}
}

func (s *agentsService) List(ctx context.Context, params *AgentListParams, opts ...RequestOption) (*Page[Agent], error) {
	if params == nil {
		params = &AgentListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.State != nil {
		q.Set("state", string(*params.State))
	}
	if params.VariationSelectionMode != nil {
		q.Set("variationSelectionMode", string(*params.VariationSelectionMode))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListAgentsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[Agent], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *agentsService) Create(ctx context.Context, params *AgentCreateParams, opts ...RequestOption) (*Agent, error) {
	if params == nil {
		params = &AgentCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents", segWorkspaceID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.DefaultVariation != nil {
		body["defaultVariation"] = params.DefaultVariation
	}
	var out Agent
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentsService) ListFeedback(ctx context.Context, agentID string, params *AgentListFeedbackParams, opts ...RequestOption) (*Page[ObjectiveFeedback], error) {
	if params == nil {
		params = &AgentListFeedbackParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/feedback", segWorkspaceID, segAgentID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.Sentiment != nil {
		q.Set("sentiment", string(*params.Sentiment))
	}
	if params.AgentVariationID != nil {
		q.Set("agentVariationId", (*params.AgentVariationID))
	}
	if params.CreatedAfter != nil {
		q.Set("createdAfter", (*params.CreatedAfter).Format(time.RFC3339Nano))
	}
	if params.CreatedBefore != nil {
		q.Set("createdBefore", (*params.CreatedBefore).Format(time.RFC3339Nano))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListAgentFeedbackResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ObjectiveFeedback], error) {
		p := base
		p.Cursor = &cursor
		return s.ListFeedback(ctx, agentID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *agentsService) ListWebhookDeliveries(ctx context.Context, agentID string, params *AgentListWebhookDeliveriesParams, opts ...RequestOption) (*Page[WebhookDelivery], error) {
	if params == nil {
		params = &AgentListWebhookDeliveriesParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/webhook_deliveries", segWorkspaceID, segAgentID)
	q := url.Values{}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.ObjectiveID != nil {
		q.Set("objectiveId", (*params.ObjectiveID))
	}
	if params.EventType != nil {
		q.Set("eventType", string(*params.EventType))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	var out ListAgentWebhookDeliveriesResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[WebhookDelivery], error) {
		p := base
		p.Cursor = &cursor
		return s.ListWebhookDeliveries(ctx, agentID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *agentsService) Retrieve(ctx context.Context, id string, params *AgentRetrieveParams, opts ...RequestOption) (*Agent, error) {
	if params == nil {
		params = &AgentRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s", segWorkspaceID, segID)
	var out Agent
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentsService) Delete(ctx context.Context, id string, params *AgentDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &AgentDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s", segWorkspaceID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *agentsService) Update(ctx context.Context, id string, params *AgentUpdateParams, opts ...RequestOption) (*Agent, error) {
	if params == nil {
		params = &AgentUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s", segWorkspaceID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out Agent
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentsService) Archive(ctx context.Context, id string, params *AgentArchiveParams, opts ...RequestOption) (*Agent, error) {
	if params == nil {
		params = &AgentArchiveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s:archive", segWorkspaceID, segID)
	var out Agent
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentsService) Publish(ctx context.Context, id string, params *AgentPublishParams, opts ...RequestOption) (*Agent, error) {
	if params == nil {
		params = &AgentPublishParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s:publish", segWorkspaceID, segID)
	var out Agent
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentsService) Unarchive(ctx context.Context, id string, params *AgentUnarchiveParams, opts ...RequestOption) (*Agent, error) {
	if params == nil {
		params = &AgentUnarchiveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s:unarchive", segWorkspaceID, segID)
	var out Agent
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentsService) Unpublish(ctx context.Context, id string, params *AgentUnpublishParams, opts ...RequestOption) (*Agent, error) {
	if params == nil {
		params = &AgentUnpublishParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s:unpublish", segWorkspaceID, segID)
	var out Agent
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
