// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type MemoryEntriesSuite struct {
	suite.Suite
}

func TestMemoryEntriesSuite(t *testing.T) {
	suite.Run(t, new(MemoryEntriesSuite))
}

func (s *MemoryEntriesSuite) TestList() {
	g := loadGolden(s.T(), "MemoryService_ListMemoryEntries")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.MemoryLayers().Entries().List(ctx, "sample", (&cadenya.MemoryEntryListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers/sample/entries", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.MemoryLayers().Entries().List(ctx, "sample", (&cadenya.MemoryEntryListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *MemoryEntriesSuite) TestCreate() {
	g := loadGolden(s.T(), "MemoryService_CreateMemoryEntry")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.MemoryLayers().Entries().Create(ctx, "sample", (&cadenya.MemoryEntryCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.MemoryEntryCreateSpec{Content: &cadenya.MemoryEntryCreateSpec_Content{Type: "content", Content: "sample", Key: "sample"}}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers/sample/entries", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.MemoryLayers().Entries().Create(ctx, "sample", (&cadenya.MemoryEntryCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.MemoryEntryCreateSpec{Content: &cadenya.MemoryEntryCreateSpec_Content{Type: "content", Content: "sample", Key: "sample"}}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *MemoryEntriesSuite) TestRetrieve() {
	g := loadGolden(s.T(), "MemoryService_GetMemoryEntry")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.MemoryLayers().Entries().Retrieve(ctx, "sample", "sample", (&cadenya.MemoryEntryRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers/sample/entries/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.MemoryLayers().Entries().Retrieve(ctx, "sample", "sample", (&cadenya.MemoryEntryRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *MemoryEntriesSuite) TestDelete() {
	g := loadGolden(s.T(), "MemoryService_DeleteMemoryEntry")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.MemoryLayers().Entries().Delete(ctx, "sample", "sample", (&cadenya.MemoryEntryDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers/sample/entries/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.MemoryLayers().Entries().Delete(ctx, "sample", "sample", (&cadenya.MemoryEntryDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *MemoryEntriesSuite) TestUpdate() {
	g := loadGolden(s.T(), "MemoryService_UpdateMemoryEntry")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.MemoryLayers().Entries().Update(ctx, "sample", "sample", (&cadenya.MemoryEntryUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.MemoryEntryUpdateSpec{}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/memory_layers/sample/entries/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.MemoryLayers().Entries().Update(ctx, "sample", "sample", (&cadenya.MemoryEntryUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.MemoryEntryUpdateSpec{}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
