// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type AIProviderKeyListParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	Prefix      *string `json:"prefix,omitempty"`
	Query       *string `json:"query,omitempty"`
	Promotional *bool   `json:"promotional,omitempty"`
	Labels      *string `json:"labels,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
}

// AIProviderKeyListBuilder builds a AIProviderKeyListParams fluently.
type AIProviderKeyListBuilder struct {
	params AIProviderKeyListParams
}

func (b *AIProviderKeyListBuilder) WorkspaceID(v string) *AIProviderKeyListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AIProviderKeyListBuilder) Limit(v int32) *AIProviderKeyListBuilder {
	b.params.Limit = &v
	return b
}

func (b *AIProviderKeyListBuilder) Cursor(v string) *AIProviderKeyListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *AIProviderKeyListBuilder) Prefix(v string) *AIProviderKeyListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *AIProviderKeyListBuilder) Query(v string) *AIProviderKeyListBuilder {
	b.params.Query = &v
	return b
}

func (b *AIProviderKeyListBuilder) Promotional(v bool) *AIProviderKeyListBuilder {
	b.params.Promotional = &v
	return b
}

func (b *AIProviderKeyListBuilder) Labels(v string) *AIProviderKeyListBuilder {
	b.params.Labels = &v
	return b
}

func (b *AIProviderKeyListBuilder) SortOrder(v string) *AIProviderKeyListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *AIProviderKeyListBuilder) IncludeInfo(v bool) *AIProviderKeyListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AIProviderKeyListBuilder) ToParams() *AIProviderKeyListParams {
	p := b.params
	return &p
}

type AIProviderKeyCreateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *CreateResourceMetadata `json:"metadata"`
	Spec        *AIProviderKeySpec      `json:"spec"`
}

// AIProviderKeyCreateBuilder builds a AIProviderKeyCreateParams fluently.
type AIProviderKeyCreateBuilder struct {
	params AIProviderKeyCreateParams
}

func (b *AIProviderKeyCreateBuilder) WorkspaceID(v string) *AIProviderKeyCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AIProviderKeyCreateBuilder) Metadata(v *CreateResourceMetadata) *AIProviderKeyCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AIProviderKeyCreateBuilder) Spec(v *AIProviderKeySpec) *AIProviderKeyCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AIProviderKeyCreateBuilder) ToParams() *AIProviderKeyCreateParams {
	p := b.params
	return &p
}

type AIProviderKeyRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AIProviderKeyRetrieveBuilder builds a AIProviderKeyRetrieveParams fluently.
type AIProviderKeyRetrieveBuilder struct {
	params AIProviderKeyRetrieveParams
}

func (b *AIProviderKeyRetrieveBuilder) WorkspaceID(v string) *AIProviderKeyRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AIProviderKeyRetrieveBuilder) ToParams() *AIProviderKeyRetrieveParams {
	p := b.params
	return &p
}

type AIProviderKeyDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AIProviderKeyDeleteBuilder builds a AIProviderKeyDeleteParams fluently.
type AIProviderKeyDeleteBuilder struct {
	params AIProviderKeyDeleteParams
}

func (b *AIProviderKeyDeleteBuilder) WorkspaceID(v string) *AIProviderKeyDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AIProviderKeyDeleteBuilder) ToParams() *AIProviderKeyDeleteParams {
	p := b.params
	return &p
}

type AIProviderKeyUpdateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *UpdateResourceMetadata `json:"metadata,omitempty"`
	Spec        *AIProviderKeySpec      `json:"spec,omitempty"`
	UpdateMask  *string                 `json:"updateMask,omitempty"`
}

// AIProviderKeyUpdateBuilder builds a AIProviderKeyUpdateParams fluently.
type AIProviderKeyUpdateBuilder struct {
	params AIProviderKeyUpdateParams
}

func (b *AIProviderKeyUpdateBuilder) WorkspaceID(v string) *AIProviderKeyUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AIProviderKeyUpdateBuilder) Metadata(v *UpdateResourceMetadata) *AIProviderKeyUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AIProviderKeyUpdateBuilder) Spec(v *AIProviderKeySpec) *AIProviderKeyUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *AIProviderKeyUpdateBuilder) UpdateMask(v string) *AIProviderKeyUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AIProviderKeyUpdateBuilder) ToParams() *AIProviderKeyUpdateParams {
	p := b.params
	return &p
}

// AIProviderKeyResources is implemented by the SDK and easy to mock in tests.
type AIProviderKeyResources interface {
	// List AI provider keys
	List(ctx context.Context, params *AIProviderKeyListParams, opts ...RequestOption) (*Page[AIProviderKey], error)
	// Create a new AI provider key
	Create(ctx context.Context, params *AIProviderKeyCreateParams, opts ...RequestOption) (*AIProviderKey, error)
	// Get an AI provider key by ID
	Retrieve(ctx context.Context, id string, params *AIProviderKeyRetrieveParams, opts ...RequestOption) (*AIProviderKey, error)
	// Delete an AI provider key
	Delete(ctx context.Context, id string, params *AIProviderKeyDeleteParams, opts ...RequestOption) error
	// Update an AI provider key
	Update(ctx context.Context, id string, params *AIProviderKeyUpdateParams, opts ...RequestOption) (*AIProviderKey, error)
}

type aiProviderKeysService struct{ core *core }

var _ AIProviderKeyResources = (*aiProviderKeysService)(nil)

func (s *aiProviderKeysService) List(ctx context.Context, params *AIProviderKeyListParams, opts ...RequestOption) (*Page[AIProviderKey], error) {
	if params == nil {
		params = &AIProviderKeyListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/ai_provider_keys", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.Promotional != nil {
		q.Set("promotional", strconv.FormatBool(*params.Promotional))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListAIProviderKeysResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[AIProviderKey], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *aiProviderKeysService) Create(ctx context.Context, params *AIProviderKeyCreateParams, opts ...RequestOption) (*AIProviderKey, error) {
	if params == nil {
		params = &AIProviderKeyCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/ai_provider_keys", segWorkspaceID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out AIProviderKey
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *aiProviderKeysService) Retrieve(ctx context.Context, id string, params *AIProviderKeyRetrieveParams, opts ...RequestOption) (*AIProviderKey, error) {
	if params == nil {
		params = &AIProviderKeyRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/ai_provider_keys/%s", segWorkspaceID, segID)
	var out AIProviderKey
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *aiProviderKeysService) Delete(ctx context.Context, id string, params *AIProviderKeyDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &AIProviderKeyDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/ai_provider_keys/%s", segWorkspaceID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *aiProviderKeysService) Update(ctx context.Context, id string, params *AIProviderKeyUpdateParams, opts ...RequestOption) (*AIProviderKey, error) {
	if params == nil {
		params = &AIProviderKeyUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/ai_provider_keys/%s", segWorkspaceID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out AIProviderKey
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
