// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type ToolSetSecretListParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	Prefix      *string `json:"prefix,omitempty"`
	Query       *string `json:"query,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
}

// ToolSetSecretListBuilder builds a ToolSetSecretListParams fluently.
type ToolSetSecretListBuilder struct {
	params ToolSetSecretListParams
}

func (b *ToolSetSecretListBuilder) WorkspaceID(v string) *ToolSetSecretListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ToolSetSecretListBuilder) Limit(v int32) *ToolSetSecretListBuilder {
	b.params.Limit = &v
	return b
}

func (b *ToolSetSecretListBuilder) Cursor(v string) *ToolSetSecretListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *ToolSetSecretListBuilder) Prefix(v string) *ToolSetSecretListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *ToolSetSecretListBuilder) Query(v string) *ToolSetSecretListBuilder {
	b.params.Query = &v
	return b
}

func (b *ToolSetSecretListBuilder) SortOrder(v string) *ToolSetSecretListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *ToolSetSecretListBuilder) IncludeInfo(v bool) *ToolSetSecretListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetSecretListBuilder) ToParams() *ToolSetSecretListParams {
	p := b.params
	return &p
}

type ToolSetSecretCreateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *CreateResourceMetadata `json:"metadata"`
	Spec        *ToolSetSecretSpec      `json:"spec"`
}

// ToolSetSecretCreateBuilder builds a ToolSetSecretCreateParams fluently.
type ToolSetSecretCreateBuilder struct {
	params ToolSetSecretCreateParams
}

func (b *ToolSetSecretCreateBuilder) WorkspaceID(v string) *ToolSetSecretCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ToolSetSecretCreateBuilder) Metadata(v *CreateResourceMetadata) *ToolSetSecretCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *ToolSetSecretCreateBuilder) Spec(v *ToolSetSecretSpec) *ToolSetSecretCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetSecretCreateBuilder) ToParams() *ToolSetSecretCreateParams {
	p := b.params
	return &p
}

type ToolSetSecretRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ToolSetSecretRetrieveBuilder builds a ToolSetSecretRetrieveParams fluently.
type ToolSetSecretRetrieveBuilder struct {
	params ToolSetSecretRetrieveParams
}

func (b *ToolSetSecretRetrieveBuilder) WorkspaceID(v string) *ToolSetSecretRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetSecretRetrieveBuilder) ToParams() *ToolSetSecretRetrieveParams {
	p := b.params
	return &p
}

type ToolSetSecretDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// ToolSetSecretDeleteBuilder builds a ToolSetSecretDeleteParams fluently.
type ToolSetSecretDeleteBuilder struct {
	params ToolSetSecretDeleteParams
}

func (b *ToolSetSecretDeleteBuilder) WorkspaceID(v string) *ToolSetSecretDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetSecretDeleteBuilder) ToParams() *ToolSetSecretDeleteParams {
	p := b.params
	return &p
}

type ToolSetSecretUpdateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *UpdateResourceMetadata `json:"metadata,omitempty"`
	Spec        *ToolSetSecretSpec      `json:"spec,omitempty"`
	UpdateMask  *string                 `json:"updateMask,omitempty"`
}

// ToolSetSecretUpdateBuilder builds a ToolSetSecretUpdateParams fluently.
type ToolSetSecretUpdateBuilder struct {
	params ToolSetSecretUpdateParams
}

func (b *ToolSetSecretUpdateBuilder) WorkspaceID(v string) *ToolSetSecretUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *ToolSetSecretUpdateBuilder) Metadata(v *UpdateResourceMetadata) *ToolSetSecretUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *ToolSetSecretUpdateBuilder) Spec(v *ToolSetSecretSpec) *ToolSetSecretUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *ToolSetSecretUpdateBuilder) UpdateMask(v string) *ToolSetSecretUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *ToolSetSecretUpdateBuilder) ToParams() *ToolSetSecretUpdateParams {
	p := b.params
	return &p
}

// ToolSetSecretResources is implemented by the SDK and easy to mock in tests.
type ToolSetSecretResources interface {
	// List tool set secrets
	List(ctx context.Context, toolSetID string, params *ToolSetSecretListParams, opts ...RequestOption) (*Page[ToolSetSecret], error)
	// Create a new tool set secret
	Create(ctx context.Context, toolSetID string, params *ToolSetSecretCreateParams, opts ...RequestOption) (*ToolSetSecret, error)
	// Get a tool set secret by ID
	Retrieve(ctx context.Context, toolSetID string, id string, params *ToolSetSecretRetrieveParams, opts ...RequestOption) (*ToolSetSecret, error)
	// Delete a tool set secret
	Delete(ctx context.Context, toolSetID string, id string, params *ToolSetSecretDeleteParams, opts ...RequestOption) error
	// Update a tool set secret
	Update(ctx context.Context, toolSetID string, id string, params *ToolSetSecretUpdateParams, opts ...RequestOption) (*ToolSetSecret, error)
}

type toolSetSecretsService struct{ core *core }

var _ ToolSetSecretResources = (*toolSetSecretsService)(nil)

func (s *toolSetSecretsService) List(ctx context.Context, toolSetID string, params *ToolSetSecretListParams, opts ...RequestOption) (*Page[ToolSetSecret], error) {
	if params == nil {
		params = &ToolSetSecretListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segToolSetID, err := pathSegment("toolSetId", toolSetID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s/secrets", segWorkspaceID, segToolSetID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListToolSetSecretsResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[ToolSetSecret], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, toolSetID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *toolSetSecretsService) Create(ctx context.Context, toolSetID string, params *ToolSetSecretCreateParams, opts ...RequestOption) (*ToolSetSecret, error) {
	if params == nil {
		params = &ToolSetSecretCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segToolSetID, err := pathSegment("toolSetId", toolSetID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s/secrets", segWorkspaceID, segToolSetID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out ToolSetSecret
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *toolSetSecretsService) Retrieve(ctx context.Context, toolSetID string, id string, params *ToolSetSecretRetrieveParams, opts ...RequestOption) (*ToolSetSecret, error) {
	if params == nil {
		params = &ToolSetSecretRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segToolSetID, err := pathSegment("toolSetId", toolSetID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s/secrets/%s", segWorkspaceID, segToolSetID, segID)
	var out ToolSetSecret
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *toolSetSecretsService) Delete(ctx context.Context, toolSetID string, id string, params *ToolSetSecretDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &ToolSetSecretDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segToolSetID, err := pathSegment("toolSetId", toolSetID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s/secrets/%s", segWorkspaceID, segToolSetID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *toolSetSecretsService) Update(ctx context.Context, toolSetID string, id string, params *ToolSetSecretUpdateParams, opts ...RequestOption) (*ToolSetSecret, error) {
	if params == nil {
		params = &ToolSetSecretUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segToolSetID, err := pathSegment("toolSetId", toolSetID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/tool_sets/%s/secrets/%s", segWorkspaceID, segToolSetID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out ToolSetSecret
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
