// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type WorkspaceSecretsSuite struct {
	suite.Suite
}

func TestWorkspaceSecretsSuite(t *testing.T) {
	suite.Run(t, new(WorkspaceSecretsSuite))
}

func (s *WorkspaceSecretsSuite) TestList() {
	g := loadGolden(s.T(), "WorkspaceSecretService_ListWorkspaceSecrets")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.WorkspaceSecrets().List(ctx, (&cadenya.WorkspaceSecretListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/workspace_secrets", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WorkspaceSecrets().List(ctx, (&cadenya.WorkspaceSecretListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceSecretsSuite) TestCreate() {
	g := loadGolden(s.T(), "WorkspaceSecretService_CreateWorkspaceSecret")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WorkspaceSecrets().Create(ctx, (&cadenya.WorkspaceSecretCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.WorkspaceSecretSpec{}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/workspace_secrets", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WorkspaceSecrets().Create(ctx, (&cadenya.WorkspaceSecretCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.WorkspaceSecretSpec{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceSecretsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "WorkspaceSecretService_GetWorkspaceSecret")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WorkspaceSecrets().Retrieve(ctx, "sample", (&cadenya.WorkspaceSecretRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/workspace_secrets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WorkspaceSecrets().Retrieve(ctx, "sample", (&cadenya.WorkspaceSecretRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceSecretsSuite) TestDelete() {
	g := loadGolden(s.T(), "WorkspaceSecretService_DeleteWorkspaceSecret")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.WorkspaceSecrets().Delete(ctx, "sample", (&cadenya.WorkspaceSecretDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/workspace_secrets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.WorkspaceSecrets().Delete(ctx, "sample", (&cadenya.WorkspaceSecretDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceSecretsSuite) TestUpdate() {
	g := loadGolden(s.T(), "WorkspaceSecretService_UpdateWorkspaceSecret")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WorkspaceSecrets().Update(ctx, "sample", (&cadenya.WorkspaceSecretUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.WorkspaceSecretSpec{}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/workspace_secrets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WorkspaceSecrets().Update(ctx, "sample", (&cadenya.WorkspaceSecretUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.WorkspaceSecretSpec{}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
