// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type ApiKeysSuite struct {
	suite.Suite
}

func TestApiKeysSuite(t *testing.T) {
	suite.Run(t, new(ApiKeysSuite))
}

func (s *ApiKeysSuite) TestRetrieveGlobal() {
	g := loadGolden(s.T(), "GlobalAPIKeyService_GetGlobalAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().RetrieveGlobal(ctx)
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *ApiKeysSuite) TestDisableGlobal() {
	g := loadGolden(s.T(), "GlobalAPIKeyService_DisableGlobalAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().DisableGlobal(ctx)
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *ApiKeysSuite) TestEnableGlobal() {
	g := loadGolden(s.T(), "GlobalAPIKeyService_EnableGlobalAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().EnableGlobal(ctx)
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *ApiKeysSuite) TestRotateGlobal() {
	g := loadGolden(s.T(), "GlobalAPIKeyService_RotateGlobalAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().RotateGlobal(ctx)
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *ApiKeysSuite) TestList() {
	g := loadGolden(s.T(), "APIKeyService_ListAPIKeys")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.APIKeys().List(ctx, (&cadenya.APIKeyListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/api_keys", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.APIKeys().List(ctx, (&cadenya.APIKeyListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ApiKeysSuite) TestCreate() {
	g := loadGolden(s.T(), "APIKeyService_CreateAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().Create(ctx, (&cadenya.APIKeyCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateAccountResourceMetadata{Name: "sample"}).
		Spec(&cadenya.APIKeySpecParam{}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/api_keys", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.APIKeys().Create(ctx, (&cadenya.APIKeyCreateBuilder{}).
			Metadata(&cadenya.CreateAccountResourceMetadata{Name: "sample"}).
			Spec(&cadenya.APIKeySpecParam{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ApiKeysSuite) TestRetrieve() {
	g := loadGolden(s.T(), "APIKeyService_GetAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().Retrieve(ctx, "sample", (&cadenya.APIKeyRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/api_keys/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.APIKeys().Retrieve(ctx, "sample", (&cadenya.APIKeyRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ApiKeysSuite) TestDelete() {
	g := loadGolden(s.T(), "APIKeyService_DeleteAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.APIKeys().Delete(ctx, "sample", (&cadenya.APIKeyDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/api_keys/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.APIKeys().Delete(ctx, "sample", (&cadenya.APIKeyDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ApiKeysSuite) TestUpdate() {
	g := loadGolden(s.T(), "APIKeyService_UpdateAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().Update(ctx, "sample", (&cadenya.APIKeyUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateAccountResourceMetadata{Name: "sample"}).
		Spec(&cadenya.APIKeySpecParam{}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/api_keys/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.APIKeys().Update(ctx, "sample", (&cadenya.APIKeyUpdateBuilder{}).
			Metadata(&cadenya.UpdateAccountResourceMetadata{Name: "sample"}).
			Spec(&cadenya.APIKeySpecParam{}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ApiKeysSuite) TestDisable() {
	g := loadGolden(s.T(), "APIKeyService_DisableAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().Disable(ctx, "sample", (&cadenya.APIKeyDisableBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/api_keys/sample:disable", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.APIKeys().Disable(ctx, "sample", (&cadenya.APIKeyDisableBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ApiKeysSuite) TestEnable() {
	g := loadGolden(s.T(), "APIKeyService_EnableAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().Enable(ctx, "sample", (&cadenya.APIKeyEnableBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/api_keys/sample:enable", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.APIKeys().Enable(ctx, "sample", (&cadenya.APIKeyEnableBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ApiKeysSuite) TestRotate() {
	g := loadGolden(s.T(), "APIKeyService_RotateAPIKey")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.APIKeys().Rotate(ctx, "sample", (&cadenya.APIKeyRotateBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/api_keys/sample:rotate", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.APIKeys().Rotate(ctx, "sample", (&cadenya.APIKeyRotateBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
