// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type WorkspaceAdminSuite struct {
	suite.Suite
}

func TestWorkspaceAdminSuite(t *testing.T) {
	suite.Run(t, new(WorkspaceAdminSuite))
}

func (s *WorkspaceAdminSuite) TestListProfiles() {
	g := loadGolden(s.T(), "WorkspaceAdminService_ListProfiles")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.WorkspaceAdmin().ListProfiles(ctx, (&cadenya.WorkspaceAdminListProfilesBuilder{}).
		Limit(1).
		Cursor("sample").
		Query("sample").
		Labels("sample").
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *WorkspaceAdminSuite) TestListAccount() {
	g := loadGolden(s.T(), "WorkspaceAdminService_ListAccountWorkspaces")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.WorkspaceAdmin().ListAccount(ctx, (&cadenya.WorkspaceAdminListAccountBuilder{}).
		Limit(1).
		Cursor("sample").
		IncludeArchived(true).
		Labels("sample").
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *WorkspaceAdminSuite) TestCreate() {
	g := loadGolden(s.T(), "WorkspaceAdminService_CreateWorkspace")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WorkspaceAdmin().Create(ctx, (&cadenya.WorkspaceAdminCreateBuilder{}).
		Metadata(&cadenya.CreateAccountResourceMetadata{Name: "sample"}).
		Spec(&cadenya.WorkspaceSpec{}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")
}

func (s *WorkspaceAdminSuite) TestRetrieve() {
	g := loadGolden(s.T(), "WorkspaceAdminService_GetWorkspace")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WorkspaceAdmin().Retrieve(ctx, (&cadenya.WorkspaceAdminRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/account/workspaces/default_workspace_id", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WorkspaceAdmin().Retrieve(ctx, (&cadenya.WorkspaceAdminRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceAdminSuite) TestArchive() {
	g := loadGolden(s.T(), "WorkspaceAdminService_ArchiveWorkspace")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.WorkspaceAdmin().Archive(ctx, (&cadenya.WorkspaceAdminArchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/account/workspaces/default_workspace_id", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.WorkspaceAdmin().Archive(ctx, (&cadenya.WorkspaceAdminArchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceAdminSuite) TestUpdate() {
	g := loadGolden(s.T(), "WorkspaceAdminService_UpdateWorkspace")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WorkspaceAdmin().Update(ctx, (&cadenya.WorkspaceAdminUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateAccountResourceMetadata{Name: "sample"}).
		Spec(&cadenya.WorkspaceSpec{}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/account/workspaces/default_workspace_id", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WorkspaceAdmin().Update(ctx, (&cadenya.WorkspaceAdminUpdateBuilder{}).
			Metadata(&cadenya.UpdateAccountResourceMetadata{Name: "sample"}).
			Spec(&cadenya.WorkspaceSpec{}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceAdminSuite) TestListMembers() {
	g := loadGolden(s.T(), "WorkspaceAdminService_ListWorkspaceMembers")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.WorkspaceAdmin().ListMembers(ctx, (&cadenya.WorkspaceAdminListMembersBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/account/workspaces/default_workspace_id/members", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WorkspaceAdmin().ListMembers(ctx, (&cadenya.WorkspaceAdminListMembersBuilder{}).
			Limit(1).
			Cursor("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceAdminSuite) TestAddMember() {
	g := loadGolden(s.T(), "WorkspaceAdminService_AddWorkspaceMember")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.WorkspaceAdmin().AddMember(ctx, (&cadenya.WorkspaceAdminAddMemberBuilder{}).
		WorkspaceID("sample").
		ProfileID("sample").
		Email("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/account/workspaces/default_workspace_id/members", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.WorkspaceAdmin().AddMember(ctx, (&cadenya.WorkspaceAdminAddMemberBuilder{}).
			ProfileID("sample").
			Email("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *WorkspaceAdminSuite) TestRemoveMember() {
	g := loadGolden(s.T(), "WorkspaceAdminService_RemoveWorkspaceMember")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.WorkspaceAdmin().RemoveMember(ctx, "sample", (&cadenya.WorkspaceAdminRemoveMemberBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/account/workspaces/default_workspace_id/members/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.WorkspaceAdmin().RemoveMember(ctx, "sample", (&cadenya.WorkspaceAdminRemoveMemberBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
