// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type APIKeyListParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	Prefix      *string `json:"prefix,omitempty"`
	Query       *string `json:"query,omitempty"`
	Labels      *string `json:"labels,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
}

// APIKeyListBuilder builds a APIKeyListParams fluently.
type APIKeyListBuilder struct {
	params APIKeyListParams
}

func (b *APIKeyListBuilder) WorkspaceID(v string) *APIKeyListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *APIKeyListBuilder) Limit(v int32) *APIKeyListBuilder {
	b.params.Limit = &v
	return b
}

func (b *APIKeyListBuilder) Cursor(v string) *APIKeyListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *APIKeyListBuilder) Prefix(v string) *APIKeyListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *APIKeyListBuilder) Query(v string) *APIKeyListBuilder {
	b.params.Query = &v
	return b
}

func (b *APIKeyListBuilder) Labels(v string) *APIKeyListBuilder {
	b.params.Labels = &v
	return b
}

func (b *APIKeyListBuilder) SortOrder(v string) *APIKeyListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *APIKeyListBuilder) IncludeInfo(v bool) *APIKeyListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *APIKeyListBuilder) ToParams() *APIKeyListParams {
	p := b.params
	return &p
}

type APIKeyCreateParams struct {
	WorkspaceID *string                        `json:"workspaceId,omitempty"`
	Metadata    *CreateAccountResourceMetadata `json:"metadata"`
	Spec        *APIKeySpecParam               `json:"spec"`
}

// APIKeyCreateBuilder builds a APIKeyCreateParams fluently.
type APIKeyCreateBuilder struct {
	params APIKeyCreateParams
}

func (b *APIKeyCreateBuilder) WorkspaceID(v string) *APIKeyCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *APIKeyCreateBuilder) Metadata(v *CreateAccountResourceMetadata) *APIKeyCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *APIKeyCreateBuilder) Spec(v *APIKeySpecParam) *APIKeyCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *APIKeyCreateBuilder) ToParams() *APIKeyCreateParams {
	p := b.params
	return &p
}

type APIKeyRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// APIKeyRetrieveBuilder builds a APIKeyRetrieveParams fluently.
type APIKeyRetrieveBuilder struct {
	params APIKeyRetrieveParams
}

func (b *APIKeyRetrieveBuilder) WorkspaceID(v string) *APIKeyRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *APIKeyRetrieveBuilder) ToParams() *APIKeyRetrieveParams {
	p := b.params
	return &p
}

type APIKeyDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// APIKeyDeleteBuilder builds a APIKeyDeleteParams fluently.
type APIKeyDeleteBuilder struct {
	params APIKeyDeleteParams
}

func (b *APIKeyDeleteBuilder) WorkspaceID(v string) *APIKeyDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *APIKeyDeleteBuilder) ToParams() *APIKeyDeleteParams {
	p := b.params
	return &p
}

type APIKeyUpdateParams struct {
	WorkspaceID *string                        `json:"workspaceId,omitempty"`
	Metadata    *UpdateAccountResourceMetadata `json:"metadata,omitempty"`
	Spec        *APIKeySpecParam               `json:"spec,omitempty"`
	UpdateMask  *string                        `json:"updateMask,omitempty"`
}

// APIKeyUpdateBuilder builds a APIKeyUpdateParams fluently.
type APIKeyUpdateBuilder struct {
	params APIKeyUpdateParams
}

func (b *APIKeyUpdateBuilder) WorkspaceID(v string) *APIKeyUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *APIKeyUpdateBuilder) Metadata(v *UpdateAccountResourceMetadata) *APIKeyUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *APIKeyUpdateBuilder) Spec(v *APIKeySpecParam) *APIKeyUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *APIKeyUpdateBuilder) UpdateMask(v string) *APIKeyUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *APIKeyUpdateBuilder) ToParams() *APIKeyUpdateParams {
	p := b.params
	return &p
}

type APIKeyDisableParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// APIKeyDisableBuilder builds a APIKeyDisableParams fluently.
type APIKeyDisableBuilder struct {
	params APIKeyDisableParams
}

func (b *APIKeyDisableBuilder) WorkspaceID(v string) *APIKeyDisableBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *APIKeyDisableBuilder) ToParams() *APIKeyDisableParams {
	p := b.params
	return &p
}

type APIKeyEnableParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// APIKeyEnableBuilder builds a APIKeyEnableParams fluently.
type APIKeyEnableBuilder struct {
	params APIKeyEnableParams
}

func (b *APIKeyEnableBuilder) WorkspaceID(v string) *APIKeyEnableBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *APIKeyEnableBuilder) ToParams() *APIKeyEnableParams {
	p := b.params
	return &p
}

type APIKeyRotateParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// APIKeyRotateBuilder builds a APIKeyRotateParams fluently.
type APIKeyRotateBuilder struct {
	params APIKeyRotateParams
}

func (b *APIKeyRotateBuilder) WorkspaceID(v string) *APIKeyRotateBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *APIKeyRotateBuilder) ToParams() *APIKeyRotateParams {
	p := b.params
	return &p
}

// APIKeyResources is implemented by the SDK and easy to mock in tests.
type APIKeyResources interface {
	// Get the global API key
	RetrieveGlobal(ctx context.Context, opts ...RequestOption) (*APIKey, error)
	// Disable the global API key
	DisableGlobal(ctx context.Context, opts ...RequestOption) (*APIKey, error)
	// Enable the global API key
	EnableGlobal(ctx context.Context, opts ...RequestOption) (*APIKey, error)
	// Rotate the global API key
	RotateGlobal(ctx context.Context, opts ...RequestOption) (*APIKey, error)
	// List API keys
	List(ctx context.Context, params *APIKeyListParams, opts ...RequestOption) (*Page[APIKey], error)
	// Create a new API key
	Create(ctx context.Context, params *APIKeyCreateParams, opts ...RequestOption) (*APIKey, error)
	// Get an API key by ID
	Retrieve(ctx context.Context, id string, params *APIKeyRetrieveParams, opts ...RequestOption) (*APIKey, error)
	// Delete an API key
	Delete(ctx context.Context, id string, params *APIKeyDeleteParams, opts ...RequestOption) error
	// Update an API key
	Update(ctx context.Context, id string, params *APIKeyUpdateParams, opts ...RequestOption) (*APIKey, error)
	// Disable an API key
	Disable(ctx context.Context, id string, params *APIKeyDisableParams, opts ...RequestOption) (*APIKey, error)
	// Enable an API key
	Enable(ctx context.Context, id string, params *APIKeyEnableParams, opts ...RequestOption) (*APIKey, error)
	// Rotate an API key
	Rotate(ctx context.Context, id string, params *APIKeyRotateParams, opts ...RequestOption) (*APIKey, error)
}

type apiKeysService struct{ core *core }

var _ APIKeyResources = (*apiKeysService)(nil)

func (s *apiKeysService) RetrieveGlobal(ctx context.Context, opts ...RequestOption) (*APIKey, error) {
	path := "/v1/account/global_api_key"
	var out APIKey
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) DisableGlobal(ctx context.Context, opts ...RequestOption) (*APIKey, error) {
	path := "/v1/account/global_api_key:disable"
	var out APIKey
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) EnableGlobal(ctx context.Context, opts ...RequestOption) (*APIKey, error) {
	path := "/v1/account/global_api_key:enable"
	var out APIKey
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) RotateGlobal(ctx context.Context, opts ...RequestOption) (*APIKey, error) {
	path := "/v1/account/global_api_key:rotate"
	var out APIKey
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) List(ctx context.Context, params *APIKeyListParams, opts ...RequestOption) (*Page[APIKey], error) {
	if params == nil {
		params = &APIKeyListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/api_keys", segWorkspaceID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListAPIKeysResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[APIKey], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *apiKeysService) Create(ctx context.Context, params *APIKeyCreateParams, opts ...RequestOption) (*APIKey, error) {
	if params == nil {
		params = &APIKeyCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/api_keys", segWorkspaceID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out APIKey
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) Retrieve(ctx context.Context, id string, params *APIKeyRetrieveParams, opts ...RequestOption) (*APIKey, error) {
	if params == nil {
		params = &APIKeyRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/api_keys/%s", segWorkspaceID, segID)
	var out APIKey
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) Delete(ctx context.Context, id string, params *APIKeyDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &APIKeyDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/api_keys/%s", segWorkspaceID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *apiKeysService) Update(ctx context.Context, id string, params *APIKeyUpdateParams, opts ...RequestOption) (*APIKey, error) {
	if params == nil {
		params = &APIKeyUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/api_keys/%s", segWorkspaceID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out APIKey
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) Disable(ctx context.Context, id string, params *APIKeyDisableParams, opts ...RequestOption) (*APIKey, error) {
	if params == nil {
		params = &APIKeyDisableParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/api_keys/%s:disable", segWorkspaceID, segID)
	var out APIKey
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) Enable(ctx context.Context, id string, params *APIKeyEnableParams, opts ...RequestOption) (*APIKey, error) {
	if params == nil {
		params = &APIKeyEnableParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/api_keys/%s:enable", segWorkspaceID, segID)
	var out APIKey
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *apiKeysService) Rotate(ctx context.Context, id string, params *APIKeyRotateParams, opts ...RequestOption) (*APIKey, error) {
	if params == nil {
		params = &APIKeyRotateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/api_keys/%s:rotate", segWorkspaceID, segID)
	var out APIKey
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
