// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type ToolSetsSuite struct {
	suite.Suite
}

func TestToolSetsSuite(t *testing.T) {
	suite.Run(t, new(ToolSetsSuite))
}

func (s *ToolSetsSuite) TestList() {
	g := loadGolden(s.T(), "ToolService_ListToolSets")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.ToolSets().List(ctx, (&cadenya.ToolSetListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		State(cadenya.ToolServiceListToolSetsState("STATE_ACTIVE")).
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().List(ctx, (&cadenya.ToolSetListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			State(cadenya.ToolServiceListToolSetsState("STATE_ACTIVE")).
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestCreate() {
	g := loadGolden(s.T(), "ToolService_CreateToolSet")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Create(ctx, (&cadenya.ToolSetCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.ToolSetSpec{Adapter: &cadenya.ToolSetAdapter{MCP: &cadenya.ToolSetAdapter_MCPVariant{Type: "mcp", MCP: &cadenya.ToolSetAdapter_MCP{}}}}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Create(ctx, (&cadenya.ToolSetCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.ToolSetSpec{Adapter: &cadenya.ToolSetAdapter{MCP: &cadenya.ToolSetAdapter_MCPVariant{Type: "mcp", MCP: &cadenya.ToolSetAdapter_MCP{}}}}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "ToolService_GetToolSet")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Retrieve(ctx, "sample", (&cadenya.ToolSetRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Retrieve(ctx, "sample", (&cadenya.ToolSetRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestDelete() {
	g := loadGolden(s.T(), "ToolService_DeleteToolSet")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.ToolSets().Delete(ctx, "sample", (&cadenya.ToolSetDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.ToolSets().Delete(ctx, "sample", (&cadenya.ToolSetDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestUpdate() {
	g := loadGolden(s.T(), "ToolService_UpdateToolSet")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Update(ctx, "sample", (&cadenya.ToolSetUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.ToolSetSpec{Adapter: &cadenya.ToolSetAdapter{MCP: &cadenya.ToolSetAdapter_MCPVariant{Type: "mcp", MCP: &cadenya.ToolSetAdapter_MCP{}}}}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Update(ctx, "sample", (&cadenya.ToolSetUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.ToolSetSpec{Adapter: &cadenya.ToolSetAdapter{MCP: &cadenya.ToolSetAdapter_MCPVariant{Type: "mcp", MCP: &cadenya.ToolSetAdapter_MCP{}}}}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestArchive() {
	g := loadGolden(s.T(), "ToolService_ArchiveToolSet")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Archive(ctx, "sample", (&cadenya.ToolSetArchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample:archive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Archive(ctx, "sample", (&cadenya.ToolSetArchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestUnarchive() {
	g := loadGolden(s.T(), "ToolService_UnarchiveToolSet")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Unarchive(ctx, "sample", (&cadenya.ToolSetUnarchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample:unarchive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Unarchive(ctx, "sample", (&cadenya.ToolSetUnarchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestListEvents() {
	g := loadGolden(s.T(), "ToolService_ListToolSetEvents")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.ToolSets().ListEvents(ctx, "sample", (&cadenya.ToolSetListEventsBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		SortOrder("sample").
		IncludeInfo(true).
		Labels("sample").
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/events", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().ListEvents(ctx, "sample", (&cadenya.ToolSetListEventsBuilder{}).
			Limit(1).
			Cursor("sample").
			SortOrder("sample").
			IncludeInfo(true).
			Labels("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestRetrieveOpenAPISpec() {
	g := loadGolden(s.T(), "ToolService_GetToolSetOpenAPISpec")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().RetrieveOpenAPISpec(ctx, "sample", (&cadenya.ToolSetRetrieveOpenAPISpecBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/openapi_spec", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().RetrieveOpenAPISpec(ctx, "sample", (&cadenya.ToolSetRetrieveOpenAPISpecBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolSetsSuite) TestListUsage() {
	g := loadGolden(s.T(), "ToolService_ListToolSetUsage")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.ToolSets().ListUsage(ctx, "sample", (&cadenya.ToolSetListUsageBuilder{}).
		WorkspaceID("sample").
		ToolID("sample").
		Limit(1).
		Cursor("sample").
		SortOrder("sample").
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/usage", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().ListUsage(ctx, "sample", (&cadenya.ToolSetListUsageBuilder{}).
			ToolID("sample").
			Limit(1).
			Cursor("sample").
			SortOrder("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
