// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
)

type UploadCreateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *CreateResourceMetadata `json:"metadata"`
	Spec        *UploadSpec             `json:"spec"`
}

// UploadCreateBuilder builds a UploadCreateParams fluently.
type UploadCreateBuilder struct {
	params UploadCreateParams
}

func (b *UploadCreateBuilder) WorkspaceID(v string) *UploadCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *UploadCreateBuilder) Metadata(v *CreateResourceMetadata) *UploadCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *UploadCreateBuilder) Spec(v *UploadSpec) *UploadCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *UploadCreateBuilder) ToParams() *UploadCreateParams {
	p := b.params
	return &p
}

type UploadRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// UploadRetrieveBuilder builds a UploadRetrieveParams fluently.
type UploadRetrieveBuilder struct {
	params UploadRetrieveParams
}

func (b *UploadRetrieveBuilder) WorkspaceID(v string) *UploadRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *UploadRetrieveBuilder) ToParams() *UploadRetrieveParams {
	p := b.params
	return &p
}

// UploadResources is implemented by the SDK and easy to mock in tests.
type UploadResources interface {
	// Create an upload
	Create(ctx context.Context, params *UploadCreateParams, opts ...RequestOption) (*Upload, error)
	// Get an upload by ID
	Retrieve(ctx context.Context, id string, params *UploadRetrieveParams, opts ...RequestOption) (*Upload, error)
}

type uploadsService struct{ core *core }

var _ UploadResources = (*uploadsService)(nil)

func (s *uploadsService) Create(ctx context.Context, params *UploadCreateParams, opts ...RequestOption) (*Upload, error) {
	if params == nil {
		params = &UploadCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/uploads", segWorkspaceID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out Upload
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *uploadsService) Retrieve(ctx context.Context, id string, params *UploadRetrieveParams, opts ...RequestOption) (*Upload, error) {
	if params == nil {
		params = &UploadRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/uploads/%s", segWorkspaceID, segID)
	var out Upload
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
