// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"

	cadenya "go.cadenya.com/cadenya-go"
)

type ToolsSuite struct {
	suite.Suite
}

func TestToolsSuite(t *testing.T) {
	suite.Run(t, new(ToolsSuite))
}

func (s *ToolsSuite) TestList() {
	g := loadGolden(s.T(), "ToolService_ListTools")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.ToolSets().Tools().List(ctx, "sample", (&cadenya.ToolListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		Names("sample").
		States(cadenya.ToolServiceListToolsStates("STATE_AVAILABLE")).
		RequiresApproval(true).
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/tools", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Tools().List(ctx, "sample", (&cadenya.ToolListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			Names("sample").
			States(cadenya.ToolServiceListToolsStates("STATE_AVAILABLE")).
			RequiresApproval(true).
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolsSuite) TestCreate() {
	g := loadGolden(s.T(), "ToolService_CreateTool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Tools().Create(ctx, "sample", (&cadenya.ToolCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.ToolSpec{Description: "sample", RequiresApproval: true, Parameters: map[string]any{}, Config: &cadenya.ToolSpec_Config{HTTP: &cadenya.ToolSpec_Config_HTTP{Type: "http", HTTP: &cadenya.Config_HTTP{RequestMethod: cadenya.ConfigHTTPRequestMethod("GET")}}}}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/tools", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Tools().Create(ctx, "sample", (&cadenya.ToolCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.ToolSpec{Description: "sample", RequiresApproval: true, Parameters: map[string]any{}, Config: &cadenya.ToolSpec_Config{HTTP: &cadenya.ToolSpec_Config_HTTP{Type: "http", HTTP: &cadenya.Config_HTTP{RequestMethod: cadenya.ConfigHTTPRequestMethod("GET")}}}}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "ToolService_GetTool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Tools().Retrieve(ctx, "sample", "sample", (&cadenya.ToolRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Tools().Retrieve(ctx, "sample", "sample", (&cadenya.ToolRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolsSuite) TestDelete() {
	g := loadGolden(s.T(), "ToolService_DeleteTool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.ToolSets().Tools().Delete(ctx, "sample", "sample", (&cadenya.ToolDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.ToolSets().Tools().Delete(ctx, "sample", "sample", (&cadenya.ToolDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolsSuite) TestUpdate() {
	g := loadGolden(s.T(), "ToolService_UpdateTool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Tools().Update(ctx, "sample", "sample", (&cadenya.ToolUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.ToolSpec{Description: "sample", RequiresApproval: true, Parameters: map[string]any{}, Config: &cadenya.ToolSpec_Config{HTTP: &cadenya.ToolSpec_Config_HTTP{Type: "http", HTTP: &cadenya.Config_HTTP{RequestMethod: cadenya.ConfigHTTPRequestMethod("GET")}}}}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Tools().Update(ctx, "sample", "sample", (&cadenya.ToolUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.ToolSpec{Description: "sample", RequiresApproval: true, Parameters: map[string]any{}, Config: &cadenya.ToolSpec_Config{HTTP: &cadenya.ToolSpec_Config_HTTP{Type: "http", HTTP: &cadenya.Config_HTTP{RequestMethod: cadenya.ConfigHTTPRequestMethod("GET")}}}}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolsSuite) TestOmit() {
	g := loadGolden(s.T(), "ToolService_OmitTool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Tools().Omit(ctx, "sample", "sample", (&cadenya.ToolOmitBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample:omit", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Tools().Omit(ctx, "sample", "sample", (&cadenya.ToolOmitBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *ToolsSuite) TestRestore() {
	g := loadGolden(s.T(), "ToolService_RestoreTool")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.ToolSets().Tools().Restore(ctx, "sample", "sample", (&cadenya.ToolRestoreBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample:restore", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.ToolSets().Tools().Restore(ctx, "sample", "sample", (&cadenya.ToolRestoreBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
