// Code generated by redwood. DO NOT EDIT.

package cadenya

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type AgentScheduleListParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
	Limit       *int32  `json:"limit,omitempty"`
	Cursor      *string `json:"cursor,omitempty"`
	Prefix      *string `json:"prefix,omitempty"`
	Query       *string `json:"query,omitempty"`
	Labels      *string `json:"labels,omitempty"`
	SortOrder   *string `json:"sortOrder,omitempty"`
	IncludeInfo *bool   `json:"includeInfo,omitempty"`
}

// AgentScheduleListBuilder builds a AgentScheduleListParams fluently.
type AgentScheduleListBuilder struct {
	params AgentScheduleListParams
}

func (b *AgentScheduleListBuilder) WorkspaceID(v string) *AgentScheduleListBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentScheduleListBuilder) Limit(v int32) *AgentScheduleListBuilder {
	b.params.Limit = &v
	return b
}

func (b *AgentScheduleListBuilder) Cursor(v string) *AgentScheduleListBuilder {
	b.params.Cursor = &v
	return b
}

func (b *AgentScheduleListBuilder) Prefix(v string) *AgentScheduleListBuilder {
	b.params.Prefix = &v
	return b
}

func (b *AgentScheduleListBuilder) Query(v string) *AgentScheduleListBuilder {
	b.params.Query = &v
	return b
}

func (b *AgentScheduleListBuilder) Labels(v string) *AgentScheduleListBuilder {
	b.params.Labels = &v
	return b
}

func (b *AgentScheduleListBuilder) SortOrder(v string) *AgentScheduleListBuilder {
	b.params.SortOrder = &v
	return b
}

func (b *AgentScheduleListBuilder) IncludeInfo(v bool) *AgentScheduleListBuilder {
	b.params.IncludeInfo = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentScheduleListBuilder) ToParams() *AgentScheduleListParams {
	p := b.params
	return &p
}

type AgentScheduleCreateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *CreateResourceMetadata `json:"metadata"`
	Spec        *AgentScheduleSpec      `json:"spec"`
}

// AgentScheduleCreateBuilder builds a AgentScheduleCreateParams fluently.
type AgentScheduleCreateBuilder struct {
	params AgentScheduleCreateParams
}

func (b *AgentScheduleCreateBuilder) WorkspaceID(v string) *AgentScheduleCreateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentScheduleCreateBuilder) Metadata(v *CreateResourceMetadata) *AgentScheduleCreateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AgentScheduleCreateBuilder) Spec(v *AgentScheduleSpec) *AgentScheduleCreateBuilder {
	b.params.Spec = v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentScheduleCreateBuilder) ToParams() *AgentScheduleCreateParams {
	p := b.params
	return &p
}

type AgentScheduleRetrieveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentScheduleRetrieveBuilder builds a AgentScheduleRetrieveParams fluently.
type AgentScheduleRetrieveBuilder struct {
	params AgentScheduleRetrieveParams
}

func (b *AgentScheduleRetrieveBuilder) WorkspaceID(v string) *AgentScheduleRetrieveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentScheduleRetrieveBuilder) ToParams() *AgentScheduleRetrieveParams {
	p := b.params
	return &p
}

type AgentScheduleDeleteParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentScheduleDeleteBuilder builds a AgentScheduleDeleteParams fluently.
type AgentScheduleDeleteBuilder struct {
	params AgentScheduleDeleteParams
}

func (b *AgentScheduleDeleteBuilder) WorkspaceID(v string) *AgentScheduleDeleteBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentScheduleDeleteBuilder) ToParams() *AgentScheduleDeleteParams {
	p := b.params
	return &p
}

type AgentScheduleUpdateParams struct {
	WorkspaceID *string                 `json:"workspaceId,omitempty"`
	Metadata    *UpdateResourceMetadata `json:"metadata,omitempty"`
	Spec        *AgentScheduleSpec      `json:"spec,omitempty"`
	UpdateMask  *string                 `json:"updateMask,omitempty"`
}

// AgentScheduleUpdateBuilder builds a AgentScheduleUpdateParams fluently.
type AgentScheduleUpdateBuilder struct {
	params AgentScheduleUpdateParams
}

func (b *AgentScheduleUpdateBuilder) WorkspaceID(v string) *AgentScheduleUpdateBuilder {
	b.params.WorkspaceID = &v
	return b
}

func (b *AgentScheduleUpdateBuilder) Metadata(v *UpdateResourceMetadata) *AgentScheduleUpdateBuilder {
	b.params.Metadata = v
	return b
}

func (b *AgentScheduleUpdateBuilder) Spec(v *AgentScheduleSpec) *AgentScheduleUpdateBuilder {
	b.params.Spec = v
	return b
}

func (b *AgentScheduleUpdateBuilder) UpdateMask(v string) *AgentScheduleUpdateBuilder {
	b.params.UpdateMask = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentScheduleUpdateBuilder) ToParams() *AgentScheduleUpdateParams {
	p := b.params
	return &p
}

type AgentScheduleArchiveParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentScheduleArchiveBuilder builds a AgentScheduleArchiveParams fluently.
type AgentScheduleArchiveBuilder struct {
	params AgentScheduleArchiveParams
}

func (b *AgentScheduleArchiveBuilder) WorkspaceID(v string) *AgentScheduleArchiveBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentScheduleArchiveBuilder) ToParams() *AgentScheduleArchiveParams {
	p := b.params
	return &p
}

type AgentSchedulePauseParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentSchedulePauseBuilder builds a AgentSchedulePauseParams fluently.
type AgentSchedulePauseBuilder struct {
	params AgentSchedulePauseParams
}

func (b *AgentSchedulePauseBuilder) WorkspaceID(v string) *AgentSchedulePauseBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentSchedulePauseBuilder) ToParams() *AgentSchedulePauseParams {
	p := b.params
	return &p
}

type AgentScheduleResumeParams struct {
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// AgentScheduleResumeBuilder builds a AgentScheduleResumeParams fluently.
type AgentScheduleResumeBuilder struct {
	params AgentScheduleResumeParams
}

func (b *AgentScheduleResumeBuilder) WorkspaceID(v string) *AgentScheduleResumeBuilder {
	b.params.WorkspaceID = &v
	return b
}

// ToParams returns the built params, ready to pass to the SDK method.
func (b *AgentScheduleResumeBuilder) ToParams() *AgentScheduleResumeParams {
	p := b.params
	return &p
}

// AgentScheduleResources is implemented by the SDK and easy to mock in tests.
type AgentScheduleResources interface {
	// List schedules
	List(ctx context.Context, agentID string, params *AgentScheduleListParams, opts ...RequestOption) (*Page[AgentSchedule], error)
	// Create a new schedule
	Create(ctx context.Context, agentID string, params *AgentScheduleCreateParams, opts ...RequestOption) (*AgentSchedule, error)
	// Get a schedule by ID
	Retrieve(ctx context.Context, agentID string, id string, params *AgentScheduleRetrieveParams, opts ...RequestOption) (*AgentSchedule, error)
	// Delete a schedule
	Delete(ctx context.Context, agentID string, id string, params *AgentScheduleDeleteParams, opts ...RequestOption) error
	// Update a schedule
	Update(ctx context.Context, agentID string, id string, params *AgentScheduleUpdateParams, opts ...RequestOption) (*AgentSchedule, error)
	// Archive a schedule
	Archive(ctx context.Context, agentID string, id string, params *AgentScheduleArchiveParams, opts ...RequestOption) (*AgentSchedule, error)
	// Pause a schedule
	Pause(ctx context.Context, agentID string, id string, params *AgentSchedulePauseParams, opts ...RequestOption) (*AgentSchedule, error)
	// Resume a schedule
	Resume(ctx context.Context, agentID string, id string, params *AgentScheduleResumeParams, opts ...RequestOption) (*AgentSchedule, error)
}

type agentSchedulesService struct{ core *core }

var _ AgentScheduleResources = (*agentSchedulesService)(nil)

func (s *agentSchedulesService) List(ctx context.Context, agentID string, params *AgentScheduleListParams, opts ...RequestOption) (*Page[AgentSchedule], error) {
	if params == nil {
		params = &AgentScheduleListParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/schedules", segWorkspaceID, segAgentID)
	q := url.Values{}
	if params.Limit != nil {
		q.Set("limit", strconv.FormatInt(int64(*params.Limit), 10))
	}
	if params.Cursor != nil {
		q.Set("cursor", (*params.Cursor))
	}
	if params.Prefix != nil {
		q.Set("prefix", (*params.Prefix))
	}
	if params.Query != nil {
		q.Set("query", (*params.Query))
	}
	if params.Labels != nil {
		q.Set("labels", (*params.Labels))
	}
	if params.SortOrder != nil {
		q.Set("sortOrder", (*params.SortOrder))
	}
	if params.IncludeInfo != nil {
		q.Set("includeInfo", strconv.FormatBool(*params.IncludeInfo))
	}
	var out ListAgentSchedulesResponse
	if err := s.core.do(ctx, "GET", path, q, nil, &out, opts...); err != nil {
		return nil, err
	}
	nextCursor := ""
	if out.Pagination != nil {
		nextCursor = out.Pagination.NextCursor
	}
	base := *params
	fetch := func(ctx context.Context, cursor string) (*Page[AgentSchedule], error) {
		p := base
		p.Cursor = &cursor
		return s.List(ctx, agentID, &p, opts...)
	}
	return newPage(out.Items, nextCursor, fetch), nil
}

func (s *agentSchedulesService) Create(ctx context.Context, agentID string, params *AgentScheduleCreateParams, opts ...RequestOption) (*AgentSchedule, error) {
	if params == nil {
		params = &AgentScheduleCreateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/schedules", segWorkspaceID, segAgentID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	var out AgentSchedule
	if err := s.core.do(ctx, "POST", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentSchedulesService) Retrieve(ctx context.Context, agentID string, id string, params *AgentScheduleRetrieveParams, opts ...RequestOption) (*AgentSchedule, error) {
	if params == nil {
		params = &AgentScheduleRetrieveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/schedules/%s", segWorkspaceID, segAgentID, segID)
	var out AgentSchedule
	if err := s.core.do(ctx, "GET", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentSchedulesService) Delete(ctx context.Context, agentID string, id string, params *AgentScheduleDeleteParams, opts ...RequestOption) error {
	if params == nil {
		params = &AgentScheduleDeleteParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/schedules/%s", segWorkspaceID, segAgentID, segID)
	return s.core.do(ctx, "DELETE", path, nil, nil, nil, opts...)
}

func (s *agentSchedulesService) Update(ctx context.Context, agentID string, id string, params *AgentScheduleUpdateParams, opts ...RequestOption) (*AgentSchedule, error) {
	if params == nil {
		params = &AgentScheduleUpdateParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/schedules/%s", segWorkspaceID, segAgentID, segID)
	body := map[string]any{}
	if params.Metadata != nil {
		body["metadata"] = params.Metadata
	}
	if params.Spec != nil {
		body["spec"] = params.Spec
	}
	if params.UpdateMask != nil {
		body["updateMask"] = params.UpdateMask
	}
	var out AgentSchedule
	if err := s.core.do(ctx, "PATCH", path, nil, body, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentSchedulesService) Archive(ctx context.Context, agentID string, id string, params *AgentScheduleArchiveParams, opts ...RequestOption) (*AgentSchedule, error) {
	if params == nil {
		params = &AgentScheduleArchiveParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/schedules/%s:archive", segWorkspaceID, segAgentID, segID)
	var out AgentSchedule
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentSchedulesService) Pause(ctx context.Context, agentID string, id string, params *AgentSchedulePauseParams, opts ...RequestOption) (*AgentSchedule, error) {
	if params == nil {
		params = &AgentSchedulePauseParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/schedules/%s:pause", segWorkspaceID, segAgentID, segID)
	var out AgentSchedule
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

func (s *agentSchedulesService) Resume(ctx context.Context, agentID string, id string, params *AgentScheduleResumeParams, opts ...RequestOption) (*AgentSchedule, error) {
	if params == nil {
		params = &AgentScheduleResumeParams{}
	}
	workspaceID, err := s.core.resolveDefault("workspaceId", "CADENYA_WORKSPACE_ID", params.WorkspaceID)
	if err != nil {
		return nil, err
	}
	segWorkspaceID, err := pathSegment("workspaceId", workspaceID)
	if err != nil {
		return nil, err
	}
	segAgentID, err := pathSegment("agentId", agentID)
	if err != nil {
		return nil, err
	}
	segID, err := pathSegment("id", id)
	if err != nil {
		return nil, err
	}
	path := fmt.Sprintf("/v1/workspaces/%s/agents/%s/schedules/%s:resume", segWorkspaceID, segAgentID, segID)
	var out AgentSchedule
	if err := s.core.do(ctx, "POST", path, nil, nil, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
