// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"context"
	"github.com/stretchr/testify/suite"
	"testing"
	"time"

	cadenya "go.cadenya.com/cadenya-go"
)

type AgentsSuite struct {
	suite.Suite
}

func TestAgentsSuite(t *testing.T) {
	suite.Run(t, new(AgentsSuite))
}

func (s *AgentsSuite) TestList() {
	g := loadGolden(s.T(), "AgentService_ListAgents")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.Agents().List(ctx, (&cadenya.AgentListBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Prefix("sample").
		Query("sample").
		State(cadenya.AgentServiceListAgentsState("STATE_DRAFT")).
		VariationSelectionMode(cadenya.AgentServiceListAgentsVariationSelectionMode("VARIATION_SELECTION_MODE_RANDOM")).
		Labels("sample").
		SortOrder("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().List(ctx, (&cadenya.AgentListBuilder{}).
			Limit(1).
			Cursor("sample").
			Prefix("sample").
			Query("sample").
			State(cadenya.AgentServiceListAgentsState("STATE_DRAFT")).
			VariationSelectionMode(cadenya.AgentServiceListAgentsVariationSelectionMode("VARIATION_SELECTION_MODE_RANDOM")).
			Labels("sample").
			SortOrder("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestCreate() {
	g := loadGolden(s.T(), "AgentService_CreateAgent")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Create(ctx, (&cadenya.AgentCreateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AgentSpec{VariationSelectionMode: cadenya.AgentSpecVariationSelectionMode("VARIATION_SELECTION_MODE_RANDOM")}).
		DefaultVariation(&cadenya.CreateAgentVariationRequestParam{Metadata: &cadenya.CreateResourceMetadata{Name: "sample"}, Spec: &cadenya.AgentVariationSpec{}}).
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Create(ctx, (&cadenya.AgentCreateBuilder{}).
			Metadata(&cadenya.CreateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AgentSpec{VariationSelectionMode: cadenya.AgentSpecVariationSelectionMode("VARIATION_SELECTION_MODE_RANDOM")}).
			DefaultVariation(&cadenya.CreateAgentVariationRequestParam{Metadata: &cadenya.CreateResourceMetadata{Name: "sample"}, Spec: &cadenya.AgentVariationSpec{}}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestListFeedback() {
	g := loadGolden(s.T(), "AgentService_ListAgentFeedback")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.Agents().ListFeedback(ctx, "sample", (&cadenya.AgentListFeedbackBuilder{}).
		WorkspaceID("sample").
		Limit(1).
		Cursor("sample").
		Query("sample").
		Sentiment(cadenya.AgentServiceListAgentFeedbackSentiment("FEEDBACK_SENTIMENT_POSITIVE")).
		AgentVariationID("sample").
		CreatedAfter(time.Date(2026, time.January, 1, 0, 0, 0, 0, time.UTC)).
		CreatedBefore(time.Date(2026, time.January, 1, 0, 0, 0, 0, time.UTC)).
		Labels("sample").
		IncludeInfo(true).
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/feedback", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().ListFeedback(ctx, "sample", (&cadenya.AgentListFeedbackBuilder{}).
			Limit(1).
			Cursor("sample").
			Query("sample").
			Sentiment(cadenya.AgentServiceListAgentFeedbackSentiment("FEEDBACK_SENTIMENT_POSITIVE")).
			AgentVariationID("sample").
			CreatedAfter(time.Date(2026, time.January, 1, 0, 0, 0, 0, time.UTC)).
			CreatedBefore(time.Date(2026, time.January, 1, 0, 0, 0, 0, time.UTC)).
			Labels("sample").
			IncludeInfo(true).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestListWebhookDeliveries() {
	g := loadGolden(s.T(), "AgentService_ListAgentWebhookDeliveries")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	page, err := client.Agents().ListWebhookDeliveries(ctx, "sample", (&cadenya.AgentListWebhookDeliveriesBuilder{}).
		WorkspaceID("sample").
		Cursor("sample").
		Limit(1).
		ObjectiveID("sample").
		EventType(cadenya.AgentServiceListAgentWebhookDeliveriesEventType("OBJECTIVE_EVENT_TYPE_USER_MESSAGE")).
		Labels("sample").
		ToParams())
	s.Require().NoError(err)
	items, err := page.All(ctx)
	s.Require().NoError(err)
	s.Require().Len(items, 2)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample/webhook_deliveries", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().ListWebhookDeliveries(ctx, "sample", (&cadenya.AgentListWebhookDeliveriesBuilder{}).
			Cursor("sample").
			Limit(1).
			ObjectiveID("sample").
			EventType(cadenya.AgentServiceListAgentWebhookDeliveriesEventType("OBJECTIVE_EVENT_TYPE_USER_MESSAGE")).
			Labels("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestRetrieve() {
	g := loadGolden(s.T(), "AgentService_GetAgent")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Retrieve(ctx, "sample", (&cadenya.AgentRetrieveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Retrieve(ctx, "sample", (&cadenya.AgentRetrieveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestDelete() {
	g := loadGolden(s.T(), "AgentService_DeleteAgent")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	err := client.Agents().Delete(ctx, "sample", (&cadenya.AgentDeleteBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		err := client.Agents().Delete(ctx, "sample", (&cadenya.AgentDeleteBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestUpdate() {
	g := loadGolden(s.T(), "AgentService_UpdateAgent")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Update(ctx, "sample", (&cadenya.AgentUpdateBuilder{}).
		WorkspaceID("sample").
		Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
		Spec(&cadenya.AgentSpec{VariationSelectionMode: cadenya.AgentSpecVariationSelectionMode("VARIATION_SELECTION_MODE_RANDOM")}).
		UpdateMask("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Update(ctx, "sample", (&cadenya.AgentUpdateBuilder{}).
			Metadata(&cadenya.UpdateResourceMetadata{Name: "sample"}).
			Spec(&cadenya.AgentSpec{VariationSelectionMode: cadenya.AgentSpecVariationSelectionMode("VARIATION_SELECTION_MODE_RANDOM")}).
			UpdateMask("sample").
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestArchive() {
	g := loadGolden(s.T(), "AgentService_ArchiveAgent")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Archive(ctx, "sample", (&cadenya.AgentArchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample:archive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Archive(ctx, "sample", (&cadenya.AgentArchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestPublish() {
	g := loadGolden(s.T(), "AgentService_PublishAgent")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Publish(ctx, "sample", (&cadenya.AgentPublishBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample:publish", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Publish(ctx, "sample", (&cadenya.AgentPublishBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestUnarchive() {
	g := loadGolden(s.T(), "AgentService_UnarchiveAgent")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Unarchive(ctx, "sample", (&cadenya.AgentUnarchiveBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample:unarchive", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Unarchive(ctx, "sample", (&cadenya.AgentUnarchiveBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}

func (s *AgentsSuite) TestUnpublish() {
	g := loadGolden(s.T(), "AgentService_UnpublishAgent")
	server, served := goldenServer(s.T(), g)
	client := newTestClient(s.T(), server.URL)
	ctx := context.Background()
	result, err := client.Agents().Unpublish(ctx, "sample", (&cadenya.AgentUnpublishBuilder{}).
		WorkspaceID("sample").
		ToParams())
	s.Require().NoError(err)
	s.Require().NotNil(result)
	s.Require().Equal(int32(len(g.Interactions)), served.Load(), "request count")

	s.Run("workspace_id falls back to the client default", func() {
		server, hits := pathServer(s.T(), "/v1/workspaces/default_workspace_id/agents/sample:unpublish", g.Interactions[0].Response)
		client := newTestClient(s.T(), server.URL)
		ctx := context.Background()
		_, err := client.Agents().Unpublish(ctx, "sample", (&cadenya.AgentUnpublishBuilder{}).
			ToParams())
		s.Require().NoError(err)
		s.Require().Equal(int32(1), hits.Load())
	})
}
