// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"sync/atomic"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	cadenya "go.cadenya.com/cadenya-go"
)

type goldenRequest struct {
	Method string              `json:"method"`
	Path   string              `json:"path"`
	Query  map[string][]string `json:"query"`
	Body   json.RawMessage     `json:"body"`
}

type goldenResponse struct {
	Status      int    `json:"status"`
	ContentType string `json:"contentType"`
	Body        string `json:"body"`
}

type goldenInteraction struct {
	Request  goldenRequest  `json:"request"`
	Response goldenResponse `json:"response"`
}

type golden struct {
	Interactions []goldenInteraction `json:"interactions"`
}

func loadGolden(t *testing.T, id string) golden {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "golden", id+".json"))
	require.NoError(t, err, "golden file for %s", id)
	var g golden
	require.NoError(t, json.Unmarshal(raw, &g))
	require.NotEmpty(t, g.Interactions)
	return g
}

// goldenServer replays the golden interactions in order and fails the test
// when the incoming request drifts from the recorded method, path, query,
// or parsed JSON body. Assertions in the handler goroutine use assert (safe
// Errorf semantics); the caller checks the final count with require.
func goldenServer(t *testing.T, g golden) (*httptest.Server, *atomic.Int32) {
	t.Helper()
	var served atomic.Int32
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		index := int(served.Add(1)) - 1
		if !assert.Less(t, index, len(g.Interactions), "more requests than golden interactions") {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		want := g.Interactions[index]
		assert.Equal(t, want.Request.Method, r.Method)
		assert.Equal(t, want.Request.Path, r.URL.Path)
		gotQuery := map[string][]string(r.URL.Query())
		wantQuery := want.Request.Query
		if wantQuery == nil {
			wantQuery = map[string][]string{}
		}
		if len(gotQuery) != 0 || len(wantQuery) != 0 {
			assert.True(t, reflect.DeepEqual(wantQuery, gotQuery), "query drifted: want %v, got %v", wantQuery, gotQuery)
		}
		gotBody := readAll(t, r)
		if len(want.Request.Body) == 0 || string(want.Request.Body) == "null" {
			assert.Empty(t, gotBody, "unexpected request body")
		} else {
			var wantParsed, gotParsed any
			require.NoError(t, json.Unmarshal(want.Request.Body, &wantParsed))
			if assert.NoError(t, json.Unmarshal(gotBody, &gotParsed), "request body is not JSON") {
				assert.True(t, reflect.DeepEqual(wantParsed, gotParsed), "body drifted: want %s, got %s", want.Request.Body, gotBody)
			}
		}
		w.Header().Set("Content-Type", want.Response.ContentType)
		w.WriteHeader(want.Response.Status)
		_, _ = w.Write([]byte(want.Response.Body))
	}))
	t.Cleanup(server.Close)
	return server, &served
}

func readAll(t *testing.T, r *http.Request) []byte {
	t.Helper()
	if r.Body == nil {
		return nil
	}
	defer r.Body.Close()
	buf := make([]byte, 0, 1024)
	tmp := make([]byte, 1024)
	for {
		n, err := r.Body.Read(tmp)
		buf = append(buf, tmp[:n]...)
		if err != nil {
			break
		}
	}
	return buf
}

func newTestClient(t *testing.T, baseURL string, extra ...cadenya.Option) *cadenya.Client {
	t.Helper()
	opts := []cadenya.Option{
		cadenya.WithBaseURL(baseURL),
		cadenya.WithAPIKey("test-key"),
		cadenya.WithWorkspaceID("default_workspace_id"),
	}
	opts = append(opts, extra...)
	client, err := cadenya.NewClient(opts...)
	require.NoError(t, err)
	return client
}
