// Code generated by redwood. DO NOT EDIT.
package cadenya_test

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"net/http"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	cadenya "go.cadenya.com/cadenya-go"
)

var webhookKey = []byte("0123456789abcdef0123456789abcdef")

func webhookSecret() string {
	return "whsec_" + base64.StdEncoding.EncodeToString(webhookKey)
}

func signedHeaders(payload []byte, at int64, key []byte) http.Header {
	mac := hmac.New(sha256.New, key)
	fmt.Fprintf(mac, "msg_1.%d.%s", at, payload)
	signature := base64.StdEncoding.EncodeToString(mac.Sum(nil))
	headers := http.Header{}
	headers.Set("webhook-id", "msg_1")
	headers.Set("webhook-timestamp", fmt.Sprintf("%d", at))
	headers.Set("webhook-signature", "v1,"+signature)
	return headers
}

func TestWebhookVerification(t *testing.T) {
	payload := []byte(`{"data":{"agent":{"accountId":"sample","createdAt":"2026-01-01T00:00:00Z","externalId":"sample","id":"sample","labels":{},"name":"sample","profileId":"sample","workspaceId":"sample"},"agentVariation":{"accountId":"sample","createdAt":"2026-01-01T00:00:00Z","externalId":"sample","id":"sample","labels":{},"name":"sample","profileId":"sample","workspaceId":"sample"},"objective":{"accountId":"sample","createdAt":"2026-01-01T00:00:00Z","externalId":"sample","id":"sample","labels":{},"profileId":"sample","workspaceId":"sample"},"objectiveEvent":{"contextWindowId":"sample","data":{"type":"userMessage","userMessage":{"content":"sample"}},"metadata":{"accountId":"sample","createdAt":"2026-01-01T00:00:00Z","externalId":"sample","id":"sample","labels":{},"profileId":"sample","workspaceId":"sample"}}},"timestamp":"2026-01-01T00:00:00Z","type":"sample"}`)
	t.Run("an authentic signature verifies", func(t *testing.T) {
		require.NoError(t, cadenya.VerifyWebhook(webhookSecret(), payload, signedHeaders(payload, time.Now().Unix(), webhookKey)))
	})
	t.Run("a tampered payload is rejected", func(t *testing.T) {
		headers := signedHeaders(payload, time.Now().Unix(), webhookKey)
		require.Error(t, cadenya.VerifyWebhook(webhookSecret(), append(payload, ' '), headers))
	})
	t.Run("the wrong secret is rejected", func(t *testing.T) {
		other := "whsec_" + base64.StdEncoding.EncodeToString([]byte("fedcba9876543210fedcba9876543210"))
		require.Error(t, cadenya.VerifyWebhook(other, payload, signedHeaders(payload, time.Now().Unix(), webhookKey)))
	})
	t.Run("a stale timestamp is rejected as replay", func(t *testing.T) {
		headers := signedHeaders(payload, time.Now().Add(-time.Hour).Unix(), webhookKey)
		require.ErrorContains(t, cadenya.VerifyWebhook(webhookSecret(), payload, headers), "tolerance")
	})
	t.Run("a missing signature header is rejected", func(t *testing.T) {
		headers := signedHeaders(payload, time.Now().Unix(), webhookKey)
		headers.Del("webhook-signature")
		require.Error(t, cadenya.VerifyWebhook(webhookSecret(), payload, headers))
	})
}
