// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cadenya

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go.cadenya.com/cadenya-go/internal/apijson"
	"go.cadenya.com/cadenya-go/internal/apiquery"
	"go.cadenya.com/cadenya-go/internal/requestconfig"
	"go.cadenya.com/cadenya-go/option"
	"go.cadenya.com/cadenya-go/packages/pagination"
	"go.cadenya.com/cadenya-go/packages/param"
	"go.cadenya.com/cadenya-go/packages/respjson"
	"go.cadenya.com/cadenya-go/shared"
	"net/http"
	"net/url"
	"slices"
)

// Manage embeddable chat widgets. A widget binds an agent to a globally unique
// hostname with a per-widget origin allowlist; browsers reach it with session
// tokens minted via WidgetSessionService.
//
// WidgetService contains methods and other services that help with interacting
// with the cadenya API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewWidgetService] method instead.
type WidgetService struct {
	options []option.RequestOption
}

// NewWidgetService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewWidgetService(opts ...option.RequestOption) (r WidgetService) {
	r = WidgetService{}
	r.options = opts
	return
}

// Creates a widget bound to an agent. The widget's DNS label and hostname are
// generated by the server and returned in `info`. The hostname may take up to a
// minute to become reachable while the edge propagates.
func (r *WidgetService) New(ctx context.Context, params WidgetNewParams, opts ...option.RequestOption) (res *Widget, err error) {
	opts = slices.Concat(r.options, opts)
	precfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return nil, err
	}
	requestconfig.UseDefaultParam(&params.WorkspaceID, precfg.WorkspaceID)
	if params.WorkspaceID.Value == "" {
		err = errors.New("missing required workspaceId parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/workspaces/%s/widgets", url.PathEscape(params.WorkspaceID.Value))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, params, &res, opts...)
	return res, err
}

// Retrieves a widget by ID
func (r *WidgetService) Get(ctx context.Context, id string, query WidgetGetParams, opts ...option.RequestOption) (res *Widget, err error) {
	opts = slices.Concat(r.options, opts)
	precfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return nil, err
	}
	requestconfig.UseDefaultParam(&query.WorkspaceID, precfg.WorkspaceID)
	if query.WorkspaceID.Value == "" {
		err = errors.New("missing required workspaceId parameter")
		return nil, err
	}
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/workspaces/%s/widgets/%s", url.PathEscape(query.WorkspaceID.Value), url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Updates a widget's metadata or spec. The DNS label is immutable and cannot be
// updated. Re-pointing the agent affects new sessions only; in-flight
// conversations finish against the agent they started with.
func (r *WidgetService) Update(ctx context.Context, id string, params WidgetUpdateParams, opts ...option.RequestOption) (res *Widget, err error) {
	opts = slices.Concat(r.options, opts)
	precfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return nil, err
	}
	requestconfig.UseDefaultParam(&params.WorkspaceID, precfg.WorkspaceID)
	if params.WorkspaceID.Value == "" {
		err = errors.New("missing required workspaceId parameter")
		return nil, err
	}
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/workspaces/%s/widgets/%s", url.PathEscape(params.WorkspaceID.Value), url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, params, &res, opts...)
	return res, err
}

// Lists all widgets in a workspace
func (r *WidgetService) List(ctx context.Context, params WidgetListParams, opts ...option.RequestOption) (res *pagination.CursorPagination[Widget], err error) {
	var raw *http.Response
	opts = slices.Concat(r.options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	precfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return nil, err
	}
	requestconfig.UseDefaultParam(&params.WorkspaceID, precfg.WorkspaceID)
	if params.WorkspaceID.Value == "" {
		err = errors.New("missing required workspaceId parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/workspaces/%s/widgets", url.PathEscape(params.WorkspaceID.Value))
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, params, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// Lists all widgets in a workspace
func (r *WidgetService) ListAutoPaging(ctx context.Context, params WidgetListParams, opts ...option.RequestOption) *pagination.CursorPaginationAutoPager[Widget] {
	return pagination.NewCursorPaginationAutoPager(r.List(ctx, params, opts...))
}

// Deletes a widget. Its hostname stops serving and all of its sessions are
// revoked.
func (r *WidgetService) Delete(ctx context.Context, id string, body WidgetDeleteParams, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	precfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return err
	}
	requestconfig.UseDefaultParam(&body.WorkspaceID, precfg.WorkspaceID)
	if body.WorkspaceID.Value == "" {
		err = errors.New("missing required workspaceId parameter")
		return err
	}
	if id == "" {
		err = errors.New("missing required id parameter")
		return err
	}
	path := fmt.Sprintf("v1/workspaces/%s/widgets/%s", url.PathEscape(body.WorkspaceID.Value), url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, nil, opts...)
	return err
}

// Transitions a widget to STATE_ARCHIVED. The hostname stops serving at the edge,
// existing sessions are revoked, and no new sessions can be minted. Reversible via
// :unarchive.
func (r *WidgetService) Archive(ctx context.Context, id string, body WidgetArchiveParams, opts ...option.RequestOption) (res *Widget, err error) {
	opts = slices.Concat(r.options, opts)
	precfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return nil, err
	}
	requestconfig.UseDefaultParam(&body.WorkspaceID, precfg.WorkspaceID)
	if body.WorkspaceID.Value == "" {
		err = errors.New("missing required workspaceId parameter")
		return nil, err
	}
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/workspaces/%s/widgets/%s:archive", url.PathEscape(body.WorkspaceID.Value), url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Transitions an archived widget back to STATE_ACTIVE so its hostname serves
// traffic again. Sessions revoked by archival stay revoked; mint new ones.
func (r *WidgetService) Unarchive(ctx context.Context, id string, body WidgetUnarchiveParams, opts ...option.RequestOption) (res *Widget, err error) {
	opts = slices.Concat(r.options, opts)
	precfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return nil, err
	}
	requestconfig.UseDefaultParam(&body.WorkspaceID, precfg.WorkspaceID)
	if body.WorkspaceID.Value == "" {
		err = errors.New("missing required workspaceId parameter")
		return nil, err
	}
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/workspaces/%s/widgets/%s:unarchive", url.PathEscape(body.WorkspaceID.Value), url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Widget is an embeddable chat surface bound to a single agent. Each widget owns a
// globally unique, immutable DNS label under the widgets domain (e.g.
// "k7m2xq9fp4wn.widgets.cadenya.com"): one widget = one hostname = one origin
// allowlist = one agent binding. Browsers talk to the widget host with session
// bearer tokens minted server-side via WidgetSessionService.
type Widget struct {
	// Standard metadata for persistent, named resources (e.g., agents, tools, prompts)
	Metadata shared.ResourceMetadata `json:"metadata" api:"required"`
	// WidgetSpec is the user-provided configuration for a widget.
	Spec WidgetSpec `json:"spec" api:"required"`
	// The current lifecycle state of the widget. Output only. Widgets are created
	// STATE_ACTIVE; use the :archive and :unarchive actions to transition between
	// states.
	//
	// Any of "STATE_UNSPECIFIED", "STATE_ACTIVE", "STATE_ARCHIVED".
	State WidgetState `json:"state" api:"required"`
	// WidgetInfo provides read-only server-derived data about a widget.
	Info WidgetInfo `json:"info"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Metadata    respjson.Field
		Spec        respjson.Field
		State       respjson.Field
		Info        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r Widget) RawJSON() string { return r.JSON.raw }
func (r *Widget) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// The current lifecycle state of the widget. Output only. Widgets are created
// STATE_ACTIVE; use the :archive and :unarchive actions to transition between
// states.
type WidgetState string

const (
	WidgetStateStateUnspecified WidgetState = "STATE_UNSPECIFIED"
	WidgetStateStateActive      WidgetState = "STATE_ACTIVE"
	WidgetStateStateArchived    WidgetState = "STATE_ARCHIVED"
)

// WidgetInfo provides read-only server-derived data about a widget.
type WidgetInfo struct {
	// BareMetadata contains the minimal metadata for a resource: the ID and an
	// optional human-readable name. These are used for reference fields where the full
	// metadata (account scoping, timestamps, labels, external IDs) is not needed —
	// e.g., the tool references inside an agent variation spec or the tools assigned
	// to an objective. Both fields are server-populated; clients provide IDs through
	// sibling fields rather than by constructing a BareMetadata themselves.
	Agent shared.BareMetadata `json:"agent"`
	// A profile identifies a user or non-human principal (such as an API key) at the
	// account level. Profiles are account-scoped and can be granted access to multiple
	// workspaces.
	CreatedBy Profile `json:"createdBy"`
	// The widget's DNS label — the single hostname label under the widgets domain.
	// Server-generated at creation, globally unique, immutable, and deliberately
	// unrelated to the widget's id.
	DNSLabel string `json:"dnsLabel"`
	// The full hostname browsers talk to. Authoritative — clients must use this value
	// rather than constructing the hostname themselves.
	Host string `json:"host"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Agent       respjson.Field
		CreatedBy   respjson.Field
		DNSLabel    respjson.Field
		Host        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r WidgetInfo) RawJSON() string { return r.JSON.raw }
func (r *WidgetInfo) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// WidgetSpec is the user-provided configuration for a widget.
type WidgetSpec struct {
	// Agent this widget is bound to. Accepts the canonical `agent_…` form or the
	// `external_id:<value>` form. Sessions copy the agent at mint: re-pointing a
	// widget's agent affects new sessions only.
	AgentID string `json:"agentId" api:"required"`
	// Web origins allowed to embed and use this widget, enforced at the edge on every
	// browser request. Exact origins only (scheme + host + optional port), no paths,
	// no wildcard subdomains.
	OriginAllowlist []string `json:"originAllowlist"`
	// Optional explicit variation pin. Must belong to the widget's agent. When set,
	// every objective created through the widget runs this variation — bypassing the
	// agent's variation_selection_mode (staged rollout: pin in production, follow in
	// staging, promote by clearing). When unset, the agent's selection mode chooses
	// per conversation.
	VariationID string `json:"variationId"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		AgentID         respjson.Field
		OriginAllowlist respjson.Field
		VariationID     respjson.Field
		ExtraFields     map[string]respjson.Field
		raw             string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r WidgetSpec) RawJSON() string { return r.JSON.raw }
func (r *WidgetSpec) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// ToParam converts this WidgetSpec to a WidgetSpecParam.
//
// Warning: the fields of the param type will not be present. ToParam should only
// be used at the last possible moment before sending a request. Test for this with
// WidgetSpecParam.Overrides()
func (r WidgetSpec) ToParam() WidgetSpecParam {
	return param.Override[WidgetSpecParam](json.RawMessage(r.RawJSON()))
}

// WidgetSpec is the user-provided configuration for a widget.
//
// The property AgentID is required.
type WidgetSpecParam struct {
	// Agent this widget is bound to. Accepts the canonical `agent_…` form or the
	// `external_id:<value>` form. Sessions copy the agent at mint: re-pointing a
	// widget's agent affects new sessions only.
	AgentID string `json:"agentId" api:"required"`
	// Optional explicit variation pin. Must belong to the widget's agent. When set,
	// every objective created through the widget runs this variation — bypassing the
	// agent's variation_selection_mode (staged rollout: pin in production, follow in
	// staging, promote by clearing). When unset, the agent's selection mode chooses
	// per conversation.
	VariationID param.Opt[string] `json:"variationId,omitzero"`
	// Web origins allowed to embed and use this widget, enforced at the edge on every
	// browser request. Exact origins only (scheme + host + optional port), no paths,
	// no wildcard subdomains.
	OriginAllowlist []string `json:"originAllowlist,omitzero"`
	paramObj
}

func (r WidgetSpecParam) MarshalJSON() (data []byte, err error) {
	type shadow WidgetSpecParam
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *WidgetSpecParam) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type WidgetNewParams struct {
	// Use [option.WithWorkspaceID] on the client to set a global default for this
	// field.
	WorkspaceID param.Opt[string] `path:"workspaceId,omitzero" api:"required" json:"-"`
	// CreateResourceMetadata contains the user-provided fields for creating a
	// workspace-scoped resource. Read-only fields (id, account_id, workspace_id,
	// profile_id, created_at) are excluded since they are set by the server.
	Metadata shared.CreateResourceMetadataParam `json:"metadata,omitzero" api:"required"`
	// WidgetSpec is the user-provided configuration for a widget.
	Spec WidgetSpecParam `json:"spec,omitzero" api:"required"`
	paramObj
}

func (r WidgetNewParams) MarshalJSON() (data []byte, err error) {
	type shadow WidgetNewParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *WidgetNewParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type WidgetGetParams struct {
	// Use [option.WithWorkspaceID] on the client to set a global default for this
	// field.
	WorkspaceID param.Opt[string] `path:"workspaceId,omitzero" api:"required" json:"-"`
	paramObj
}

type WidgetUpdateParams struct {
	// Use [option.WithWorkspaceID] on the client to set a global default for this
	// field.
	WorkspaceID param.Opt[string] `path:"workspaceId,omitzero" api:"required" json:"-"`
	// Fields to update.
	UpdateMask param.Opt[string] `json:"updateMask,omitzero" format:"field-mask"`
	// UpdateResourceMetadata contains the user-provided fields for updating a
	// workspace-scoped resource. Read-only fields (id, account_id, workspace_id,
	// profile_id, created_at) are excluded since they are set by the server.
	Metadata shared.UpdateResourceMetadataParam `json:"metadata,omitzero"`
	// WidgetSpec is the user-provided configuration for a widget.
	Spec WidgetSpecParam `json:"spec,omitzero"`
	paramObj
}

func (r WidgetUpdateParams) MarshalJSON() (data []byte, err error) {
	type shadow WidgetUpdateParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *WidgetUpdateParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type WidgetListParams struct {
	// Use [option.WithWorkspaceID] on the client to set a global default for this
	// field.
	WorkspaceID param.Opt[string] `path:"workspaceId,omitzero" api:"required" json:"-"`
	// Filter to widgets bound to a specific agent. Accepts the canonical `agent_…`
	// form or the `external_id:<value>` form.
	AgentID param.Opt[string] `query:"agentId,omitzero" json:"-"`
	// Pagination cursor from previous response.
	Cursor param.Opt[string] `query:"cursor,omitzero" json:"-"`
	// When true, the `info` field on each returned widget is populated. Requests with
	// this flag count more against your rate limit.
	IncludeInfo param.Opt[bool] `query:"includeInfo,omitzero" json:"-"`
	// Filters by metadata labels. Comma-separated key=value pairs, e.g.
	// "env=prod,team=ai". A resource matches only if every pair matches exactly (AND
	// semantics).
	Labels param.Opt[string] `query:"labels,omitzero" json:"-"`
	// Maximum number of results to return.
	Limit param.Opt[int64] `query:"limit,omitzero" json:"-"`
	// Sort order for results (asc or desc by creation time).
	SortOrder param.Opt[string] `query:"sortOrder,omitzero" json:"-"`
	paramObj
}

// URLQuery serializes [WidgetListParams]'s query parameters as `url.Values`.
func (r WidgetListParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type WidgetDeleteParams struct {
	// Use [option.WithWorkspaceID] on the client to set a global default for this
	// field.
	WorkspaceID param.Opt[string] `path:"workspaceId,omitzero" api:"required" json:"-"`
	paramObj
}

type WidgetArchiveParams struct {
	// Use [option.WithWorkspaceID] on the client to set a global default for this
	// field.
	WorkspaceID param.Opt[string] `path:"workspaceId,omitzero" api:"required" json:"-"`
	paramObj
}

func (r WidgetArchiveParams) MarshalJSON() (data []byte, err error) {
	type shadow WidgetArchiveParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *WidgetArchiveParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type WidgetUnarchiveParams struct {
	// Use [option.WithWorkspaceID] on the client to set a global default for this
	// field.
	WorkspaceID param.Opt[string] `path:"workspaceId,omitzero" api:"required" json:"-"`
	paramObj
}

func (r WidgetUnarchiveParams) MarshalJSON() (data []byte, err error) {
	type shadow WidgetUnarchiveParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *WidgetUnarchiveParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
