// Code generated by redwood. DO NOT EDIT.
// Conformance driver: calls every operation against the mock at MOCK_URL.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	sdk "go.cadenya.com/cadenya-go"
)

var failures int

func run(id string, fn func() error) {
	if err := fn(); err != nil {
		failures++
		fmt.Printf("FAIL %s: %v\n", id, err)
		return
	}
	fmt.Printf("PASS %s\n", id)
}

func decode[T any](raw string) *T {
	var v T
	if err := json.Unmarshal([]byte(raw), &v); err != nil {
		panic(fmt.Sprintf("bad sample: %v", err))
	}
	return &v
}

func main() {
	client, err := sdk.NewClient(
		sdk.WithAPIKey("conformance-key"),
		sdk.WithBaseURL(os.Getenv("MOCK_URL")),
	)
	if err != nil {
		fmt.Println("client:", err)
		os.Exit(1)
	}
	ctx := context.Background()
	_ = ctx
	run("AccountService_GetAccount", func() error {
		_, err := client.Accounts().Retrieve(ctx)
		return err
	})
	run("AccountService_RotateChallengeToken", func() error {
		_, err := client.Accounts().RotateChallengeToken(ctx)
		return err
	})
	run("AccountService_RotateWebhookSigningKey", func() error {
		_, err := client.Accounts().RotateWebhookSigningKey(ctx)
		return err
	})
	run("GlobalAPIKeyService_GetGlobalAPIKey", func() error {
		_, err := client.APIKeys().RetrieveGlobal(ctx)
		return err
	})
	run("GlobalAPIKeyService_DisableGlobalAPIKey", func() error {
		_, err := client.APIKeys().DisableGlobal(ctx)
		return err
	})
	run("GlobalAPIKeyService_EnableGlobalAPIKey", func() error {
		_, err := client.APIKeys().EnableGlobal(ctx)
		return err
	})
	run("GlobalAPIKeyService_RotateGlobalAPIKey", func() error {
		_, err := client.APIKeys().RotateGlobal(ctx)
		return err
	})
	run("APIKeyService_ListAPIKeys", func() error {
		page, err := client.APIKeys().List(ctx, decode[sdk.APIKeyListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("APIKeyService_CreateAPIKey", func() error {
		_, err := client.APIKeys().Create(ctx, decode[sdk.APIKeyCreateParams](`{"metadata":{"name":"sample"},"spec":{},"workspaceId":"sample"}`))
		return err
	})
	run("APIKeyService_GetAPIKey", func() error {
		_, err := client.APIKeys().Retrieve(ctx, "sample", decode[sdk.APIKeyRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("APIKeyService_DeleteAPIKey", func() error {
		return client.APIKeys().Delete(ctx, "sample", decode[sdk.APIKeyDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("APIKeyService_UpdateAPIKey", func() error {
		_, err := client.APIKeys().Update(ctx, "sample", decode[sdk.APIKeyUpdateParams](`{"metadata":{"name":"sample"},"spec":{},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("APIKeyService_DisableAPIKey", func() error {
		_, err := client.APIKeys().Disable(ctx, "sample", decode[sdk.APIKeyDisableParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("APIKeyService_EnableAPIKey", func() error {
		_, err := client.APIKeys().Enable(ctx, "sample", decode[sdk.APIKeyEnableParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("APIKeyService_RotateAPIKey", func() error {
		_, err := client.APIKeys().Rotate(ctx, "sample", decode[sdk.APIKeyRotateParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WorkspaceAdminService_ListProfiles", func() error {
		page, err := client.WorkspaceAdmin().ListProfiles(ctx, decode[sdk.WorkspaceAdminListProfilesParams](`{"cursor":"sample","labels":"sample","limit":1,"query":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("WorkspaceAdminService_ListAccountWorkspaces", func() error {
		page, err := client.WorkspaceAdmin().ListAccount(ctx, decode[sdk.WorkspaceAdminListAccountParams](`{"cursor":"sample","includeArchived":true,"labels":"sample","limit":1}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("WorkspaceAdminService_CreateWorkspace", func() error {
		_, err := client.WorkspaceAdmin().Create(ctx, decode[sdk.WorkspaceAdminCreateParams](`{"metadata":{"name":"sample"},"spec":{}}`))
		return err
	})
	run("WorkspaceAdminService_GetWorkspace", func() error {
		_, err := client.WorkspaceAdmin().Retrieve(ctx, decode[sdk.WorkspaceAdminRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WorkspaceAdminService_ArchiveWorkspace", func() error {
		return client.WorkspaceAdmin().Archive(ctx, decode[sdk.WorkspaceAdminArchiveParams](`{"workspaceId":"sample"}`))
	})
	run("WorkspaceAdminService_UpdateWorkspace", func() error {
		_, err := client.WorkspaceAdmin().Update(ctx, decode[sdk.WorkspaceAdminUpdateParams](`{"metadata":{"name":"sample"},"spec":{},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("WorkspaceAdminService_ListWorkspaceMembers", func() error {
		page, err := client.WorkspaceAdmin().ListMembers(ctx, decode[sdk.WorkspaceAdminListMembersParams](`{"cursor":"sample","limit":1,"workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("WorkspaceAdminService_AddWorkspaceMember", func() error {
		_, err := client.WorkspaceAdmin().AddMember(ctx, decode[sdk.WorkspaceAdminAddMemberParams](`{"email":"sample","profileId":"sample","workspaceId":"sample"}`))
		return err
	})
	run("WorkspaceAdminService_RemoveWorkspaceMember", func() error {
		return client.WorkspaceAdmin().RemoveMember(ctx, "sample", decode[sdk.WorkspaceAdminRemoveMemberParams](`{"workspaceId":"sample"}`))
	})
	run("ProfilesService_Whoami", func() error {
		_, err := client.Profiles().Whoami(ctx)
		return err
	})
	run("WorkspaceService_ListWorkspaces", func() error {
		page, err := client.Workspaces().List(ctx, decode[sdk.WorkspaceListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"sortOrder":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("AgentService_ListAgents", func() error {
		page, err := client.Agents().List(ctx, decode[sdk.AgentListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","state":"STATE_UNSPECIFIED","variationSelectionMode":"VARIATION_SELECTION_MODE_UNSPECIFIED","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("AgentService_CreateAgent", func() error {
		_, err := client.Agents().Create(ctx, decode[sdk.AgentCreateParams](`{"defaultVariation":{"metadata":{"name":"sample"},"spec":{}},"metadata":{"name":"sample"},"spec":{"variationSelectionMode":"VARIATION_SELECTION_MODE_UNSPECIFIED"},"workspaceId":"sample"}`))
		return err
	})
	run("AgentService_ListAgentFeedback", func() error {
		page, err := client.Agents().ListFeedback(ctx, "sample", decode[sdk.AgentListFeedbackParams](`{"agentVariationId":"sample","createdAfter":"2026-01-01T00:00:00Z","createdBefore":"2026-01-01T00:00:00Z","cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"query":"sample","sentiment":"FEEDBACK_SENTIMENT_UNSPECIFIED","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("AgentService_ListAgentWebhookDeliveries", func() error {
		page, err := client.Agents().ListWebhookDeliveries(ctx, "sample", decode[sdk.AgentListWebhookDeliveriesParams](`{"cursor":"sample","eventType":"OBJECTIVE_EVENT_TYPE_UNSPECIFIED","labels":"sample","limit":1,"objectiveId":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("AgentService_GetAgent", func() error {
		_, err := client.Agents().Retrieve(ctx, "sample", decode[sdk.AgentRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentService_DeleteAgent", func() error {
		return client.Agents().Delete(ctx, "sample", decode[sdk.AgentDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("AgentService_UpdateAgent", func() error {
		_, err := client.Agents().Update(ctx, "sample", decode[sdk.AgentUpdateParams](`{"metadata":{"name":"sample"},"spec":{"variationSelectionMode":"VARIATION_SELECTION_MODE_UNSPECIFIED"},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("AgentService_ArchiveAgent", func() error {
		_, err := client.Agents().Archive(ctx, "sample", decode[sdk.AgentArchiveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentService_PublishAgent", func() error {
		_, err := client.Agents().Publish(ctx, "sample", decode[sdk.AgentPublishParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentService_UnarchiveAgent", func() error {
		_, err := client.Agents().Unarchive(ctx, "sample", decode[sdk.AgentUnarchiveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentService_UnpublishAgent", func() error {
		_, err := client.Agents().Unpublish(ctx, "sample", decode[sdk.AgentUnpublishParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentScheduleService_ListAgentSchedules", func() error {
		page, err := client.Agents().Schedules().List(ctx, "sample", decode[sdk.AgentScheduleListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("AgentScheduleService_CreateAgentSchedule", func() error {
		_, err := client.Agents().Schedules().Create(ctx, "sample", decode[sdk.AgentScheduleCreateParams](`{"metadata":{"name":"sample"},"spec":{"schedule":{}},"workspaceId":"sample"}`))
		return err
	})
	run("AgentScheduleService_GetAgentSchedule", func() error {
		_, err := client.Agents().Schedules().Retrieve(ctx, "sample", "sample", decode[sdk.AgentScheduleRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentScheduleService_DeleteAgentSchedule", func() error {
		return client.Agents().Schedules().Delete(ctx, "sample", "sample", decode[sdk.AgentScheduleDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("AgentScheduleService_UpdateAgentSchedule", func() error {
		_, err := client.Agents().Schedules().Update(ctx, "sample", "sample", decode[sdk.AgentScheduleUpdateParams](`{"metadata":{"name":"sample"},"spec":{"schedule":{}},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("AgentScheduleService_ArchiveAgentSchedule", func() error {
		_, err := client.Agents().Schedules().Archive(ctx, "sample", "sample", decode[sdk.AgentScheduleArchiveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentScheduleService_PauseAgentSchedule", func() error {
		_, err := client.Agents().Schedules().Pause(ctx, "sample", "sample", decode[sdk.AgentSchedulePauseParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentScheduleService_ResumeAgentSchedule", func() error {
		_, err := client.Agents().Schedules().Resume(ctx, "sample", "sample", decode[sdk.AgentScheduleResumeParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentVariationService_ListAgentVariations", func() error {
		page, err := client.Agents().Variations().List(ctx, "sample", decode[sdk.AgentVariationListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("AgentVariationService_CreateAgentVariation", func() error {
		_, err := client.Agents().Variations().Create(ctx, "sample", decode[sdk.AgentVariationCreateParams](`{"metadata":{"name":"sample"},"spec":{},"workspaceId":"sample"}`))
		return err
	})
	run("AgentVariationService_GetAgentVariation", func() error {
		_, err := client.Agents().Variations().Retrieve(ctx, "sample", "sample", decode[sdk.AgentVariationRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AgentVariationService_DeleteAgentVariation", func() error {
		return client.Agents().Variations().Delete(ctx, "sample", "sample", decode[sdk.AgentVariationDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("AgentVariationService_UpdateAgentVariation", func() error {
		_, err := client.Agents().Variations().Update(ctx, "sample", "sample", decode[sdk.AgentVariationUpdateParams](`{"metadata":{"name":"sample"},"spec":{},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("AgentVariationService_AddAgentVariationAssignment", func() error {
		_, err := client.Agents().Variations().AddAssignment(ctx, "sample", "sample", decode[sdk.AgentVariationAddAssignmentParams](`{"body":{"toolId":"sample","type":"toolId"},"workspaceId":"sample"}`))
		return err
	})
	run("AgentVariationService_RemoveAgentVariationAssignment", func() error {
		return client.Agents().Variations().RemoveAssignment(ctx, "sample", "sample", "sample", decode[sdk.AgentVariationRemoveAssignmentParams](`{"workspaceId":"sample"}`))
	})
	run("AgentVariationService_AddAgentVariationMemoryLayer", func() error {
		_, err := client.Agents().Variations().AddMemoryLayer(ctx, "sample", "sample", decode[sdk.AgentVariationAddMemoryLayerParams](`{"memoryLayerId":"sample","position":1,"workspaceId":"sample"}`))
		return err
	})
	run("AgentVariationService_RemoveAgentVariationMemoryLayer", func() error {
		return client.Agents().Variations().RemoveMemoryLayer(ctx, "sample", "sample", "sample", decode[sdk.AgentVariationRemoveMemoryLayerParams](`{"workspaceId":"sample"}`))
	})
	run("AgentVariationService_UpdateAgentVariationMemoryLayer", func() error {
		_, err := client.Agents().Variations().UpdateMemoryLayer(ctx, "sample", "sample", "sample", decode[sdk.AgentVariationUpdateMemoryLayerParams](`{"position":1,"workspaceId":"sample"}`))
		return err
	})
	run("AIProviderKeyService_ListAIProviderKeys", func() error {
		page, err := client.AIProviderKeys().List(ctx, decode[sdk.AIProviderKeyListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"prefix":"sample","promotional":true,"query":"sample","sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("AIProviderKeyService_CreateAIProviderKey", func() error {
		_, err := client.AIProviderKeys().Create(ctx, decode[sdk.AIProviderKeyCreateParams](`{"metadata":{"name":"sample"},"spec":{},"workspaceId":"sample"}`))
		return err
	})
	run("AIProviderKeyService_GetAIProviderKey", func() error {
		_, err := client.AIProviderKeys().Retrieve(ctx, "sample", decode[sdk.AIProviderKeyRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("AIProviderKeyService_DeleteAIProviderKey", func() error {
		return client.AIProviderKeys().Delete(ctx, "sample", decode[sdk.AIProviderKeyDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("AIProviderKeyService_UpdateAIProviderKey", func() error {
		_, err := client.AIProviderKeys().Update(ctx, "sample", decode[sdk.AIProviderKeyUpdateParams](`{"metadata":{"name":"sample"},"spec":{},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("MemoryService_ListMemoryLayers", func() error {
		page, err := client.MemoryLayers().List(ctx, decode[sdk.MemoryLayerListParams](`{"agentId":"sample","cursor":"sample","episodicKeyPrefix":"sample","includeInfo":true,"labels":"sample","limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","type":"MEMORY_LAYER_TYPE_UNSPECIFIED","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("MemoryService_CreateMemoryLayer", func() error {
		_, err := client.MemoryLayers().Create(ctx, decode[sdk.MemoryLayerCreateParams](`{"metadata":{"name":"sample"},"spec":{"type":"MEMORY_LAYER_TYPE_UNSPECIFIED"},"workspaceId":"sample"}`))
		return err
	})
	run("MemoryService_GetMemoryLayer", func() error {
		_, err := client.MemoryLayers().Retrieve(ctx, "sample", decode[sdk.MemoryLayerRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("MemoryService_DeleteMemoryLayer", func() error {
		return client.MemoryLayers().Delete(ctx, "sample", decode[sdk.MemoryLayerDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("MemoryService_UpdateMemoryLayer", func() error {
		_, err := client.MemoryLayers().Update(ctx, "sample", decode[sdk.MemoryLayerUpdateParams](`{"metadata":{"name":"sample"},"spec":{"type":"MEMORY_LAYER_TYPE_UNSPECIFIED"},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("MemoryService_ListMemoryEntries", func() error {
		page, err := client.MemoryLayers().Entries().List(ctx, "sample", decode[sdk.MemoryEntryListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("MemoryService_CreateMemoryEntry", func() error {
		_, err := client.MemoryLayers().Entries().Create(ctx, "sample", decode[sdk.MemoryEntryCreateParams](`{"metadata":{"name":"sample"},"spec":{"content":"sample","key":"sample","type":"content"},"workspaceId":"sample"}`))
		return err
	})
	run("MemoryService_GetMemoryEntry", func() error {
		_, err := client.MemoryLayers().Entries().Retrieve(ctx, "sample", "sample", decode[sdk.MemoryEntryRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("MemoryService_DeleteMemoryEntry", func() error {
		return client.MemoryLayers().Entries().Delete(ctx, "sample", "sample", decode[sdk.MemoryEntryDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("MemoryService_UpdateMemoryEntry", func() error {
		_, err := client.MemoryLayers().Entries().Update(ctx, "sample", "sample", decode[sdk.MemoryEntryUpdateParams](`{"metadata":{"name":"sample"},"spec":{},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("ModelService_ListModels", func() error {
		page, err := client.Models().List(ctx, decode[sdk.ModelListParams](`{"aiProviderKeyId":"sample","cursor":"sample","includeInfo":true,"isAssigned":true,"labels":"sample","limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","state":"STATE_UNSPECIFIED","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ModelService_GetModel", func() error {
		_, err := client.Models().Retrieve(ctx, "sample", decode[sdk.ModelRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ModelService_DisableModel", func() error {
		_, err := client.Models().Disable(ctx, "sample", decode[sdk.ModelDisableParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ModelService_EnableModel", func() error {
		_, err := client.Models().Enable(ctx, "sample", decode[sdk.ModelEnableParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ModelService_SwapModelOnVariations", func() error {
		return client.Models().SwapOnVariations(ctx, decode[sdk.ModelSwapOnVariationsParams](`{"modelSwaps":[{}],"workspaceId":"sample"}`))
	})
	run("ObjectiveService_ListObjectives", func() error {
		page, err := client.Objectives().List(ctx, decode[sdk.ObjectiveListParams](`{"agentId":"sample","agentScheduleId":"sample","cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"parentObjectiveId":"sample","profileId":"sample","sortOrder":"sample","state":"STATE_UNSPECIFIED","subjectId":"sample","tenantId":"sample","widgetId":"sample","widgetSessionId":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ObjectiveService_CreateObjective", func() error {
		_, err := client.Objectives().Create(ctx, decode[sdk.ObjectiveCreateParams](`{"agentId":"sample","episodicMemory":{"key":"sample"},"firstUserMessage":"sample","firstUserMessageData":{},"memoryCascade":[{"memoryLayerId":"sample"}],"metadata":{},"pinnedParameters":{},"secrets":[{}],"subject":{"id":"sample"},"systemPromptData":{},"tenant":{"id":"sample"},"variationId":"sample","workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_GetObjective", func() error {
		_, err := client.Objectives().Retrieve(ctx, "sample", decode[sdk.ObjectiveRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_ListObjectiveContextWindows", func() error {
		page, err := client.Objectives().ListContextWindows(ctx, "sample", decode[sdk.ObjectiveListContextWindowsParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ObjectiveService_GetObjectiveDiagnostics", func() error {
		_, err := client.Objectives().RetrieveDiagnostics(ctx, "sample", decode[sdk.ObjectiveRetrieveDiagnosticsParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_ListObjectiveEvents", func() error {
		page, err := client.Objectives().ListEvents(ctx, "sample", decode[sdk.ObjectiveListEventsParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"sinceEventId":"sample","sortOrder":"sample","windowId":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ObjectiveEventStreamsService_StreamObjectiveEvents", func() error {
		stream, err := client.Objectives().StreamEvents(ctx, "sample", decode[sdk.ObjectiveStreamEventsParams](`{"workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		count := 0
		for stream.Next() {
			count++
		}
		if err := stream.Err(); err != nil {
			return err
		}
		if count != 2 {
			return fmt.Errorf("expected 2 events, got %d", count)
		}
		return nil
	})
	run("ObjectiveService_ListObjectiveFeedback", func() error {
		page, err := client.Objectives().ListFeedback(ctx, "sample", decode[sdk.ObjectiveListFeedbackParams](`{"cursor":"sample","labels":"sample","limit":1,"workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ObjectiveService_CreateObjectiveFeedback", func() error {
		_, err := client.Objectives().CreateFeedback(ctx, "sample", decode[sdk.ObjectiveCreateFeedbackParams](`{"data":{},"metadata":{},"workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_ListObjectiveTasks", func() error {
		page, err := client.Objectives().ListTasks(ctx, "sample", decode[sdk.ObjectiveListTasksParams](`{"cursor":"sample","limit":1,"sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ObjectiveService_GetObjectiveTask", func() error {
		_, err := client.Objectives().RetrieveTask(ctx, "sample", "sample", decode[sdk.ObjectiveRetrieveTaskParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_ListObjectiveToolCalls", func() error {
		page, err := client.Objectives().ListToolCalls(ctx, "sample", decode[sdk.ObjectiveListToolCallsParams](`{"cursor":"sample","executionStatus":"TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED","includeInfo":true,"labels":"sample","limit":1,"status":"TOOL_CALL_STATUS_UNSPECIFIED","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ObjectiveService_GetObjectiveToolCall", func() error {
		_, err := client.Objectives().RetrieveToolCall(ctx, "sample", "sample", decode[sdk.ObjectiveRetrieveToolCallParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_ApproveToolCall", func() error {
		_, err := client.Objectives().ApproveToolCall(ctx, "sample", "sample", decode[sdk.ObjectiveApproveToolCallParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_DenyToolCall", func() error {
		_, err := client.Objectives().DenyToolCall(ctx, "sample", "sample", decode[sdk.ObjectiveDenyToolCallParams](`{"memo":"sample","workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_SetToolCallContent", func() error {
		_, err := client.Objectives().SetToolCallContent(ctx, "sample", "sample", decode[sdk.ObjectiveSetToolCallContentParams](`{"content":[{"text":{"text":"sample"},"type":"text"}],"workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_ListObjectiveTools", func() error {
		page, err := client.Objectives().ListTools(ctx, "sample", decode[sdk.ObjectiveListToolsParams](`{"cursor":"sample","limit":1,"workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ObjectiveService_CancelObjective", func() error {
		_, err := client.Objectives().Cancel(ctx, "sample", decode[sdk.ObjectiveCancelParams](`{"reason":"sample","workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_CompactObjective", func() error {
		_, err := client.Objectives().Compact(ctx, "sample", decode[sdk.ObjectiveCompactParams](`{"compactionConfig":{},"workspaceId":"sample"}`))
		return err
	})
	run("ObjectiveService_ContinueObjective", func() error {
		_, err := client.Objectives().Continue(ctx, "sample", decode[sdk.ObjectiveContinueParams](`{"enqueue":true,"message":"sample","workspaceId":"sample"}`))
		return err
	})
	run("SearchService_SearchToolsOrToolSets", func() error {
		_, err := client.ToolSearch().SearchOrSets(ctx, decode[sdk.ToolSearchSearchOrSetsParams](`{"query":"sample","workspaceId":"sample"}`))
		return err
	})
	run("TenantService_ListTenants", func() error {
		page, err := client.Tenants().List(ctx, decode[sdk.TenantListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"query":"sample","sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("TenantService_GetTenant", func() error {
		_, err := client.Tenants().Retrieve(ctx, "sample", decode[sdk.TenantRetrieveParams](`{"includeInfo":true,"workspaceId":"sample"}`))
		return err
	})
	run("TenantService_DeleteTenant", func() error {
		_, err := client.Tenants().Delete(ctx, "sample", decode[sdk.TenantDeleteParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("TenantService_ListTenantSubjects", func() error {
		page, err := client.Tenants().ListSubjects(ctx, "sample", decode[sdk.TenantListSubjectsParams](`{"cursor":"sample","includeInfo":true,"limit":1,"query":"sample","sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ToolService_ListToolSets", func() error {
		page, err := client.ToolSets().List(ctx, decode[sdk.ToolSetListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","state":"STATE_UNSPECIFIED","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ToolService_CreateToolSet", func() error {
		_, err := client.ToolSets().Create(ctx, decode[sdk.ToolSetCreateParams](`{"metadata":{"name":"sample"},"spec":{"adapter":{"mcp":{},"type":"mcp"}},"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_GetToolSet", func() error {
		_, err := client.ToolSets().Retrieve(ctx, "sample", decode[sdk.ToolSetRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_DeleteToolSet", func() error {
		return client.ToolSets().Delete(ctx, "sample", decode[sdk.ToolSetDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("ToolService_UpdateToolSet", func() error {
		_, err := client.ToolSets().Update(ctx, "sample", decode[sdk.ToolSetUpdateParams](`{"metadata":{"name":"sample"},"spec":{"adapter":{"mcp":{},"type":"mcp"}},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("ToolService_ArchiveToolSet", func() error {
		_, err := client.ToolSets().Archive(ctx, "sample", decode[sdk.ToolSetArchiveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_UnarchiveToolSet", func() error {
		_, err := client.ToolSets().Unarchive(ctx, "sample", decode[sdk.ToolSetUnarchiveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_ListToolSetEvents", func() error {
		page, err := client.ToolSets().ListEvents(ctx, "sample", decode[sdk.ToolSetListEventsParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ToolService_GetToolSetOpenAPISpec", func() error {
		_, err := client.ToolSets().RetrieveOpenAPISpec(ctx, "sample", decode[sdk.ToolSetRetrieveOpenAPISpecParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_ListToolSetUsage", func() error {
		page, err := client.ToolSets().ListUsage(ctx, "sample", decode[sdk.ToolSetListUsageParams](`{"cursor":"sample","limit":1,"sortOrder":"sample","toolId":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ToolService_ListToolSetSecrets", func() error {
		page, err := client.ToolSets().Secrets().List(ctx, "sample", decode[sdk.ToolSetSecretListParams](`{"cursor":"sample","includeInfo":true,"limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ToolService_CreateToolSetSecret", func() error {
		_, err := client.ToolSets().Secrets().Create(ctx, "sample", decode[sdk.ToolSetSecretCreateParams](`{"metadata":{"name":"sample"},"spec":{},"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_GetToolSetSecret", func() error {
		_, err := client.ToolSets().Secrets().Retrieve(ctx, "sample", "sample", decode[sdk.ToolSetSecretRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_DeleteToolSetSecret", func() error {
		return client.ToolSets().Secrets().Delete(ctx, "sample", "sample", decode[sdk.ToolSetSecretDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("ToolService_UpdateToolSetSecret", func() error {
		_, err := client.ToolSets().Secrets().Update(ctx, "sample", "sample", decode[sdk.ToolSetSecretUpdateParams](`{"metadata":{"name":"sample"},"spec":{},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("ToolService_ListTools", func() error {
		page, err := client.ToolSets().Tools().List(ctx, "sample", decode[sdk.ToolListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"names":["sample"],"overlays":["sample"],"prefix":"sample","query":"sample","requiresApproval":true,"sortOrder":"sample","states":["STATE_UNSPECIFIED"],"workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("ToolService_CreateTool", func() error {
		_, err := client.ToolSets().Tools().Create(ctx, "sample", decode[sdk.ToolCreateParams](`{"metadata":{"name":"sample"},"spec":{"config":{"http":{"requestMethod":"HTTP_METHOD_UNSPECIFIED"},"type":"http"},"description":"sample","parameters":{},"requiresApproval":true},"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_GetTool", func() error {
		_, err := client.ToolSets().Tools().Retrieve(ctx, "sample", "sample", decode[sdk.ToolRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_DeleteTool", func() error {
		return client.ToolSets().Tools().Delete(ctx, "sample", "sample", decode[sdk.ToolDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("ToolService_UpdateTool", func() error {
		_, err := client.ToolSets().Tools().Update(ctx, "sample", "sample", decode[sdk.ToolUpdateParams](`{"metadata":{"name":"sample"},"spec":{"config":{"http":{"requestMethod":"HTTP_METHOD_UNSPECIFIED"},"type":"http"},"description":"sample","parameters":{},"requiresApproval":true},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("ToolService_OmitTool", func() error {
		_, err := client.ToolSets().Tools().Omit(ctx, "sample", "sample", decode[sdk.ToolOmitParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("ToolService_RestoreTool", func() error {
		_, err := client.ToolSets().Tools().Restore(ctx, "sample", "sample", decode[sdk.ToolRestoreParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("UploadService_CreateUpload", func() error {
		_, err := client.Uploads().Create(ctx, decode[sdk.UploadCreateParams](`{"metadata":{"name":"sample"},"spec":{"contentType":"sample","filename":"sample","sizeBytes":"sample"},"workspaceId":"sample"}`))
		return err
	})
	run("UploadService_GetUpload", func() error {
		_, err := client.Uploads().Retrieve(ctx, "sample", decode[sdk.UploadRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WidgetSessionService_ListWidgetSessions", func() error {
		page, err := client.WidgetSessions().List(ctx, decode[sdk.WidgetSessionListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"sortOrder":"sample","state":"STATE_UNSPECIFIED","subjectId":"sample","tenantId":"sample","widgetId":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("WidgetSessionService_CreateWidgetSession", func() error {
		_, err := client.WidgetSessions().Create(ctx, decode[sdk.WidgetSessionCreateParams](`{"metadata":{},"secrets":[{}],"spec":{"widgetId":"sample"},"workspaceId":"sample"}`))
		return err
	})
	run("WidgetSessionService_DeleteTenantWidgetSessions", func() error {
		_, err := client.WidgetSessions().DeleteTenant(ctx, decode[sdk.WidgetSessionDeleteTenantParams](`{"tenantId":"sample","workspaceId":"sample"}`))
		return err
	})
	run("WidgetSessionService_GetWidgetSession", func() error {
		_, err := client.WidgetSessions().Retrieve(ctx, "sample", decode[sdk.WidgetSessionRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WidgetSessionService_DeleteWidgetSession", func() error {
		return client.WidgetSessions().Delete(ctx, "sample", decode[sdk.WidgetSessionDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("WidgetSessionService_RevokeWidgetSession", func() error {
		_, err := client.WidgetSessions().Revoke(ctx, "sample", decode[sdk.WidgetSessionRevokeParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WidgetService_ListWidgets", func() error {
		page, err := client.Widgets().List(ctx, decode[sdk.WidgetListParams](`{"agentId":"sample","cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("WidgetService_CreateWidget", func() error {
		_, err := client.Widgets().Create(ctx, decode[sdk.WidgetCreateParams](`{"metadata":{"name":"sample"},"spec":{"agentId":"sample"},"workspaceId":"sample"}`))
		return err
	})
	run("WidgetService_GetWidget", func() error {
		_, err := client.Widgets().Retrieve(ctx, "sample", decode[sdk.WidgetRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WidgetService_DeleteWidget", func() error {
		return client.Widgets().Delete(ctx, "sample", decode[sdk.WidgetDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("WidgetService_UpdateWidget", func() error {
		_, err := client.Widgets().Update(ctx, "sample", decode[sdk.WidgetUpdateParams](`{"metadata":{"name":"sample"},"spec":{"agentId":"sample"},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	run("WidgetService_ArchiveWidget", func() error {
		_, err := client.Widgets().Archive(ctx, "sample", decode[sdk.WidgetArchiveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WidgetService_UnarchiveWidget", func() error {
		_, err := client.Widgets().Unarchive(ctx, "sample", decode[sdk.WidgetUnarchiveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WorkspaceSecretService_ListWorkspaceSecrets", func() error {
		page, err := client.WorkspaceSecrets().List(ctx, decode[sdk.WorkspaceSecretListParams](`{"cursor":"sample","includeInfo":true,"labels":"sample","limit":1,"prefix":"sample","query":"sample","sortOrder":"sample","workspaceId":"sample"}`))
		if err != nil {
			return err
		}
		items, err := page.All(ctx)
		if err != nil {
			return err
		}
		if len(items) != 2 {
			return fmt.Errorf("expected 2 items across pages, got %d", len(items))
		}
		return nil
	})
	run("WorkspaceSecretService_CreateWorkspaceSecret", func() error {
		_, err := client.WorkspaceSecrets().Create(ctx, decode[sdk.WorkspaceSecretCreateParams](`{"metadata":{"name":"sample"},"spec":{},"workspaceId":"sample"}`))
		return err
	})
	run("WorkspaceSecretService_GetWorkspaceSecret", func() error {
		_, err := client.WorkspaceSecrets().Retrieve(ctx, "sample", decode[sdk.WorkspaceSecretRetrieveParams](`{"workspaceId":"sample"}`))
		return err
	})
	run("WorkspaceSecretService_DeleteWorkspaceSecret", func() error {
		return client.WorkspaceSecrets().Delete(ctx, "sample", decode[sdk.WorkspaceSecretDeleteParams](`{"workspaceId":"sample"}`))
	})
	run("WorkspaceSecretService_UpdateWorkspaceSecret", func() error {
		_, err := client.WorkspaceSecrets().Update(ctx, "sample", decode[sdk.WorkspaceSecretUpdateParams](`{"metadata":{"name":"sample"},"spec":{},"updateMask":"sample","workspaceId":"sample"}`))
		return err
	})
	os.Exit(min(failures, 1))
}
